// [id, name, nameEn|null, birthDate(YYYY-MM-DD), birthHour|null, group|null, emoji, ...tags]
export default [
  // ===== 축구 (Football) =====
  ['ath-sonheungmin', '손흥민', 'Son Heung-min', '1992-07-08', null, '토트넘', '⚽', '축구', '공격수', '프리미어리그'],
  ['ath-parkjisung', '박지성', 'Park Ji-sung', '1981-02-25', null, null, '⚽', '축구', '미드필더', '레전드'],
  ['ath-leekangin', '이강인', 'Lee Kang-in', '2001-02-19', null, 'PSG', '⚽', '축구', '미드필더', '라리가'],
  ['ath-kimminjae', '김민재', 'Kim Min-jae', '1996-11-15', null, '바이에른 뮌헨', '⚽', '축구', '수비수', '분데스리가'],
  ['ath-hwangheechan', '황희찬', 'Hwang Hee-chan', '1996-01-26', null, '울버햄튼', '⚽', '축구', '공격수', '프리미어리그'],
  ['ath-leechungyong', '이청용', 'Lee Chung-yong', '1988-07-02', null, null, '⚽', '축구', '미드필더', '프리미어리그'],
  ['ath-kisungyueng', '기성용', 'Ki Sung-yueng', '1989-01-24', null, null, '⚽', '축구', '미드필더', '프리미어리그'],
  ['ath-chabumgeun', '차범근', 'Cha Bum-geun', '1953-05-22', null, null, '⚽', '축구', '공격수', '레전드'],
  ['ath-hongmyungbo', '홍명보', 'Hong Myung-bo', '1969-02-12', null, null, '⚽', '축구', '수비수', '레전드'],
  ['ath-ahnjunghwan', '안정환', 'Ahn Jung-hwan', '1976-01-27', null, null, '⚽', '축구', '공격수', '레전드'],
  ['ath-leeyoungpyo', '이영표', 'Lee Young-pyo', '1977-04-23', null, null, '⚽', '축구', '수비수', '레전드'],
  ['ath-chaduri', '차두리', 'Cha Du-ri', '1980-07-25', null, null, '⚽', '축구', '수비수', '분데스리가'],
  ['ath-chogyusung', '조규성', 'Cho Gue-sung', '1998-01-25', null, '미트윌란', '⚽', '축구', '공격수', '국가대표'],
  ['ath-leedonggook', '이동국', 'Lee Dong-gook', '1979-04-29', null, null, '⚽', '축구', '공격수', '레전드'],
  ['ath-leeulyong', '이을용', 'Lee Eul-yong', '1975-12-05', null, null, '⚽', '축구', '미드필더', '레전드'],
  ['ath-hwangsunhong', '황선홍', 'Hwang Sun-hong', '1968-07-14', null, null, '⚽', '축구', '공격수', '레전드'],
  ['ath-yoosangchul', '유상철', 'Yoo Sang-chul', '1971-10-18', null, null, '⚽', '축구', '미드필더', '레전드'],
  ['ath-seolyoungwoo', '설영우', 'Seol Young-woo', '2003-08-27', null, null, '⚽', '축구', '미드필더', '유망주'],
  ['ath-yangminhyuk', '양민혁', 'Yang Min-hyeok', '2005-02-12', null, '토트넘', '⚽', '축구', '공격수', '유망주'],
  ['ath-baekseungho', '백승호', 'Paik Seung-ho', '1997-03-17', null, null, '⚽', '축구', '미드필더', 'K리그'],
  ['ath-leejaesung', '이재성', 'Lee Jae-sung', '1992-08-10', null, '마인츠', '⚽', '축구', '미드필더', '분데스리가'],
  ['ath-jungwooyoung', '정우영', 'Jeong Woo-yeong', '1999-01-20', null, '프라이부르크', '⚽', '축구', '공격수', '분데스리가'],
  ['ath-chohyunwoo', '조현우', 'Jo Hyeon-woo', '1991-09-25', null, '울산', '⚽', '축구', '골키퍼', 'K리그'],
  ['ath-kimseunggyu', '김승규', 'Kim Seung-gyu', '1990-09-30', null, null, '⚽', '축구', '골키퍼', 'K리그'],
  ['ath-junghaewon', '정해원', 'Jeong Hae-won', '2003-04-15', null, null, '⚽', '축구', '미드필더', '유망주'],
  ['ath-baejunho', '배준호', 'Bae Jun-ho', '2004-03-13', null, '스토크시티', '⚽', '축구', '미드필더', '유망주'],
  ['ath-kimyoungwon', '김영권', 'Kim Young-gwon', '1990-02-27', null, '울산', '⚽', '축구', '수비수', 'K리그'],
  ['ath-jongwoopark', '박종우', 'Park Jong-woo', '1989-03-10', null, null, '⚽', '축구', '미드필더', '올림픽'],
  ['ath-gusungpark', '박구성', null, '1985-06-12', null, null, '⚽', '축구', '수비수', 'K리그'],
  ['ath-kimjinsu', '김진수', 'Kim Jin-su', '1992-06-13', null, '전북', '⚽', '축구', '수비수', 'K리그'],
  ['ath-kwonchanghoon', '권창훈', 'Kwon Chang-hoon', '1994-06-30', null, '김천', '⚽', '축구', '미드필더', 'K리그'],
  ['ath-namtaehee', '남태희', 'Nam Tae-hee', '1991-07-12', null, null, '⚽', '축구', '미드필더', '중동리그'],
  ['ath-songjuho', '송주호', null, '1993-05-03', null, null, '⚽', '축구', '미드필더', 'K리그'],
  ['ath-kimshinwook', '김신욱', 'Kim Shin-wook', '1988-04-14', null, null, '⚽', '축구', '공격수', 'K리그'],
  ['ath-jikiyoung', '지기영', null, '1994-11-20', null, null, '⚽', '축구', '미드필더', 'K리그'],
  ['ath-hwanginkyu', '황인범', 'Hwang In-beom', '1996-09-20', null, '페예노르트', '⚽', '축구', '미드필더', '에레디비시'],
  ['ath-songminkyu', '송민규', 'Song Min-kyu', '1999-09-12', null, null, '⚽', '축구', '공격수', 'K리그'],
  ['ath-ohnhyunju', '오현규', 'Oh Hyeon-gyu', '2001-01-12', null, '셀틱', '⚽', '축구', '공격수', '스코틀랜드'],
  ['ath-jeongsanggyo', '정상교', null, '2001-05-05', null, null, '⚽', '축구', '수비수', 'K리그'],
  ['ath-seoljuhwan', '설주환', null, '1999-08-12', null, null, '⚽', '축구', '수비수', 'K리그'],
  ['ath-choisunyong', '최선용', null, '2002-03-19', null, null, '⚽', '축구', '미드필더', '유망주'],
  ['ath-leekiwoon', '이기운', null, '2004-01-22', null, null, '⚽', '축구', '공격수', '유망주'],
  ['ath-parkkwangil', '박광일', null, '1999-07-14', null, null, '⚽', '축구', '미드필더', 'K리그'],
  ['ath-choijihoon', '최지훈', null, '2003-12-02', null, null, '⚽', '축구', '수비수', '유망주'],
  ['ath-yooseungjin', '유승진', null, '2001-06-08', null, null, '⚽', '축구', '미드필더', '유망주'],
  ['ath-kimtaehwan', '김태환', 'Kim Tae-hwan', '1989-07-24', null, '울산', '⚽', '축구', '수비수', 'K리그'],
  ['ath-hongchul', '홍철', 'Hong Chul', '1990-09-17', null, '대구', '⚽', '축구', '수비수', 'K리그'],
  ['ath-leemyungjoo', '이명주', 'Lee Myung-joo', '1990-02-14', null, null, '⚽', '축구', '미드필더', 'K리그'],
  ['ath-seokhyunjun', '석현준', 'Seok Hyun-jun', '1991-06-29', null, null, '⚽', '축구', '미드필더', '유럽리그'],
  ['ath-kimgeonhee', '김건희', null, '2000-11-01', null, null, '⚽', '축구', '공격수', 'K리그'],
  ['ath-leesanghyub', '이상협', null, '2002-08-22', null, null, '⚽', '축구', '미드필더', '유망주'],
  ['ath-leesungmin', '이승민', null, '2003-02-14', null, null, '⚽', '축구', '수비수', '유망주'],
  ['ath-parkyeonwoo', '박연우', null, '2005-01-09', null, null, '⚽', '축구', '공격수', '유망주'],

  // 해외 축구 레전드 (International Football Legends)
  ['ath-messi', '리오넬 메시', 'Lionel Messi', '1987-06-24', null, '인터 마이애미', '⚽', '축구', '공격수', '아르헨티나'],
  ['ath-ronaldo', '크리스티아누 호날두', 'Cristiano Ronaldo', '1985-02-05', null, '알 나스르', '⚽', '축구', '공격수', '포르투갈'],
  ['ath-neymar', '네이마르', 'Neymar Jr', '1992-02-05', null, '알 힐랄', '⚽', '축구', '공격수', '브라질'],
  ['ath-mbappe', '킬리안 음바페', 'Kylian Mbappe', '1998-12-20', null, '레알 마드리드', '⚽', '축구', '공격수', '프랑스'],
  ['ath-haaland', '엘링 홀란드', 'Erling Haaland', '2000-07-21', null, '맨시티', '⚽', '축구', '공격수', '노르웨이'],
  ['ath-beckham', '데이비드 베컴', 'David Beckham', '1975-05-02', null, null, '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-zidane', '지네딘 지단', 'Zinedine Zidane', '1972-06-23', null, null, '⚽', '축구', '미드필더', '프랑스'],
  ['ath-maradona', '디에고 마라도나', 'Diego Maradona', '1960-10-30', null, null, '⚽', '축구', '공격수', '아르헨티나'],
  ['ath-pele', '펠레', 'Pele', '1940-10-23', null, null, '⚽', '축구', '공격수', '브라질'],
  ['ath-rooney', '웨인 루니', 'Wayne Rooney', '1985-10-24', null, null, '⚽', '축구', '공격수', '잉글랜드'],
  ['ath-debruyne', '케빈 더브라위너', 'Kevin De Bruyne', '1991-06-28', null, '맨시티', '⚽', '축구', '미드필더', '벨기에'],
  ['ath-salah', '모하메드 살라', 'Mohamed Salah', '1992-06-15', null, '리버풀', '⚽', '축구', '공격수', '이집트'],
  ['ath-bellingham', '주드 벨링엄', 'Jude Bellingham', '2003-06-29', null, '레알 마드리드', '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-vinicius', '비니시우스 주니어', 'Vinicius Jr', '2000-07-12', null, '레알 마드리드', '⚽', '축구', '공격수', '브라질'],
  ['ath-modric', '루카 모드리치', 'Luka Modric', '1985-09-09', null, '레알 마드리드', '⚽', '축구', '미드필더', '크로아티아'],
  ['ath-kroos', '토니 크로스', 'Toni Kroos', '1990-01-04', null, null, '⚽', '축구', '미드필더', '독일'],
  ['ath-lewandowski', '로베르트 레반도프스키', 'Robert Lewandowski', '1988-08-21', null, '바르셀로나', '⚽', '축구', '공격수', '폴란드'],
  ['ath-kanagawa', '미토마 카오루', 'Mitoma Kaoru', '1997-05-20', null, '브라이튼', '⚽', '축구', '공격수', '일본'],
  ['ath-kubo', '쿠보 타케후사', 'Kubo Takefusa', '2001-06-04', null, '레알 소시에다드', '⚽', '축구', '공격수', '일본'],
  ['ath-suarez', '루이스 수아레스', 'Luis Suarez', '1987-01-24', null, '인터 마이애미', '⚽', '축구', '공격수', '우루과이'],
  ['ath-dembele', '우스만 뎀벨레', 'Ousmane Dembele', '1997-05-15', null, 'PSG', '⚽', '축구', '공격수', '프랑스'],
  ['ath-saka', '부카요 사카', 'Bukayo Saka', '2001-09-05', null, '아스날', '⚽', '축구', '공격수', '잉글랜드'],
  ['ath-pedri', '페드리', 'Pedri', '2002-11-25', null, '바르셀로나', '⚽', '축구', '미드필더', '스페인'],
  ['ath-gavi', '가비', 'Gavi', '2004-08-05', null, '바르셀로나', '⚽', '축구', '미드필더', '스페인'],
  ['ath-yamal', '라민 야말', 'Lamine Yamal', '2007-07-13', null, '바르셀로나', '⚽', '축구', '공격수', '스페인'],
  ['ath-vandijk', '버질 반 다이크', 'Virgil van Dijk', '1991-07-08', null, '리버풀', '⚽', '축구', '수비수', '네덜란드'],
  ['ath-ramos', '세르히오 라모스', 'Sergio Ramos', '1986-03-30', null, null, '⚽', '축구', '수비수', '스페인'],
  ['ath-ibrahimovic', '즐라탄 이브라히모비치', 'Zlatan Ibrahimovic', '1981-10-03', null, null, '⚽', '축구', '공격수', '스웨덴'],
  ['ath-xavi', '사비', 'Xavi', '1980-01-25', null, null, '⚽', '축구', '미드필더', '스페인'],
  ['ath-iniesta', '이니에스타', 'Andres Iniesta', '1984-05-11', null, null, '⚽', '축구', '미드필더', '스페인'],
  ['ath-ronaldinho', '호나우지뉴', 'Ronaldinho', '1980-03-21', null, null, '⚽', '축구', '공격수', '브라질'],
  ['ath-henry', '티에리 앙리', 'Thierry Henry', '1977-08-17', null, null, '⚽', '축구', '공격수', '프랑스'],
  ['ath-guardiola', '펩 과르디올라', 'Pep Guardiola', '1971-01-18', null, '맨시티', '⚽', '축구', '감독', '스페인'],
  ['ath-klopp', '위르겐 클롭', 'Jurgen Klopp', '1967-06-16', null, null, '⚽', '축구', '감독', '독일'],

  // ===== 야구 (Baseball) =====
  ['ath-ryuhyunjin', '류현진', 'Ryu Hyun-jin', '1987-03-25', null, '한화', '⚽', '야구', '투수', 'MLB'],
  ['ath-chooshinsu', '추신수', 'Choo Shin-soo', '1982-07-13', null, null, '⚽', '야구', '외야수', 'MLB'],
  ['ath-parkchanho', '박찬호', 'Park Chan-ho', '1973-06-29', null, null, '⚽', '야구', '투수', 'MLB레전드'],
  ['ath-kimkwanghyun', '김광현', 'Kim Kwang-hyun', '1988-07-22', null, 'SSG', '⚽', '야구', '투수', 'KBO'],
  ['ath-leedaeho', '이대호', 'Lee Dae-ho', '1982-06-21', null, null, '⚽', '야구', '내야수', 'KBO레전드'],
  ['ath-parkbyungho', '박병호', 'Park Byung-ho', '1986-07-10', null, '키움', '⚽', '야구', '내야수', 'KBO'],
  ['ath-kangjungho', '강정호', 'Kang Jung-ho', '1987-04-05', null, null, '⚽', '야구', '내야수', 'MLB'],
  ['ath-ohseunghwan', '오승환', 'Oh Seung-hwan', '1982-07-15', null, null, '⚽', '야구', '투수', 'MLB'],
  ['ath-kimhasung', '김하성', 'Kim Ha-seong', '1995-10-17', null, '샌디에이고', '⚽', '야구', '내야수', 'MLB'],
  ['ath-leejeonghu', '이정후', 'Lee Jung-hoo', '1998-08-20', null, 'SF 자이언츠', '⚽', '야구', '외야수', 'MLB'],
  ['ath-yanghyunjong', '양현종', 'Yang Hyeon-jong', '1988-03-01', null, 'KIA', '⚽', '야구', '투수', 'KBO'],
  ['ath-nasungbum', '나성범', 'Na Sung-bum', '1989-10-03', null, 'NC', '⚽', '야구', '외야수', 'KBO'],
  ['ath-choijung', '최정', 'Choi Jeong', '1987-02-28', null, 'SSG', '⚽', '야구', '내야수', 'KBO'],
  ['ath-leeseungyeop', '이승엽', 'Lee Seung-yeop', '1976-08-18', null, null, '⚽', '야구', '내야수', 'KBO레전드'],
  ['ath-parksehyung', '박세혁', null, '1993-05-22', null, '두산', '⚽', '야구', '내야수', 'KBO'],
  ['ath-kimjaehan', '김재환', null, '1988-09-02', null, '두산', '⚽', '야구', '외야수', 'KBO'],
  ['ath-yangwisan', '양의지', null, '1987-06-05', null, 'NC', '⚽', '야구', '포수', 'KBO'],
  ['ath-leejeonghoo2', '이정후', null, '1998-08-20', null, 'SF', '⚽', '야구', '외야수', 'MLB'],
  ['ath-kujaehyuk', '구자혁', null, '2003-06-15', null, null, '⚽', '야구', '투수', '유망주'],
  ['ath-junwuyoung', '전의산', null, '2001-01-12', null, null, '⚽', '야구', '투수', 'KBO'],
  ['ath-kimhyunsoo', '김현수', 'Kim Hyun-soo', '1988-01-12', null, 'LG', '⚽', '야구', '외야수', 'KBO'],
  ['ath-parkyongtaek', '박용택', 'Park Yong-taik', '1979-09-10', null, null, '⚽', '야구', '외야수', 'KBO레전드'],
  ['ath-sondongwon', '손동원', null, '1985-05-18', null, null, '⚽', '야구', '투수', 'KBO'],
  ['ath-ohjaeil', '오재일', null, '1990-03-15', null, '두산', '⚽', '야구', '내야수', 'KBO'],
  ['ath-leewonseok', '이원석', null, '2002-03-30', null, '삼성', '⚽', '야구', '외야수', 'KBO'],
  ['ath-hwangjunwoo', '황준우', null, '2005-04-12', null, null, '⚽', '야구', '투수', '유망주'],
  ['ath-ohtani', '오타니 쇼헤이', 'Shohei Ohtani', '1994-07-05', null, 'LA 다저스', '⚽', '야구', '투수겸타자', 'MLB'],
  ['ath-trout', '마이크 트라웃', 'Mike Trout', '1991-08-07', null, 'LA 에인절스', '⚽', '야구', '외야수', 'MLB'],
  ['ath-judge', '에런 저지', 'Aaron Judge', '1992-04-26', null, 'NY 양키스', '⚽', '야구', '외야수', 'MLB'],
  ['ath-tatis', '페르난도 타티스 주니어', 'Fernando Tatis Jr', '1999-01-02', null, '샌디에이고', '⚽', '야구', '외야수', 'MLB'],
  ['ath-acuna', '로날드 아쿠냐 주니어', 'Ronald Acuna Jr', '1997-12-18', null, '애틀란타', '⚽', '야구', '외야수', 'MLB'],
  ['ath-soto', '후안 소토', 'Juan Soto', '1998-10-25', null, 'NY 양키스', '⚽', '야구', '외야수', 'MLB'],
  ['ath-betts', '무키 베츠', 'Mookie Betts', '1992-10-07', null, 'LA 다저스', '⚽', '야구', '외야수', 'MLB'],

  // ===== 피겨/빙상 (Figure Skating / Speed Skating) =====
  ['ath-kimyuna', '김연아', 'Kim Yuna', '1990-09-05', null, null, '⚽', '피겨스케이팅', '올림픽금메달', '국민여동생'],
  ['ath-parktaehwan', '박태환', 'Park Tae-hwan', '1989-09-27', null, null, '⚽', '수영', '올림픽금메달', '마린보이'],
  ['ath-leesanghwa', '이상화', 'Lee Sang-hwa', '1989-02-25', null, null, '⚽', '스피드스케이팅', '올림픽금메달', '빙속여제'],
  ['ath-hwangdaeheon', '황대헌', 'Hwang Dae-heon', '1999-05-01', null, null, '⚽', '쇼트트랙', '올림픽금메달', '국가대표'],
  ['ath-limhyojun', '임효준', 'Lim Hyo-jun', '1996-06-29', null, null, '⚽', '쇼트트랙', '올림픽금메달', '국가대표'],
  ['ath-choiminjeong', '최민정', 'Choi Min-jung', '1998-01-06', null, null, '⚽', '쇼트트랙', '올림픽금메달', '국가대표'],
  ['ath-kimarang', '김아랑', 'Kim A-lang', '1995-07-05', null, null, '⚽', '쇼트트랙', '올림픽금메달', '국가대표'],
  ['ath-chodalin', '차준환', 'Cha Jun-hwan', '2001-10-21', null, null, '⚽', '피겨스케이팅', '국가대표', '올림픽'],
  ['ath-kimboyang', '김보양', null, '2001-03-17', null, null, '⚽', '피겨스케이팅', '국가대표', '여자'],
  ['ath-parkseunghi', '박승희', 'Park Seung-hi', '1992-11-25', null, null, '⚽', '쇼트트랙', '올림픽금메달', '레전드'],
  ['ath-shimsukhee', '심석희', 'Shim Suk-hee', '1997-01-03', null, null, '⚽', '쇼트트랙', '올림픽금메달', '국가대표'],
  ['ath-leejunso', '이준서', null, '2002-08-15', null, null, '⚽', '쇼트트랙', '국가대표', '유망주'],
  ['ath-kimdongsung', '김동성', 'Kim Dong-sung', '1980-02-08', null, null, '⚽', '쇼트트랙', '올림픽금메달', '레전드'],
  ['ath-chokyungae', '전이경', 'Jeon Lee-kyung', '1972-01-06', null, null, '⚽', '쇼트트랙', '올림픽금메달', '레전드'],
  ['ath-motheeyun', '모태범', 'Mo Tae-bum', '1989-02-15', null, null, '⚽', '스피드스케이팅', '올림픽금메달', '국가대표'],
  ['ath-leeseuengoon', '이승훈', 'Lee Seung-hoon', '1988-03-06', null, null, '⚽', '스피드스케이팅', '올림픽금메달', '국가대표'],
  ['ath-kimminseok', '김민석', 'Kim Min-seok', '1999-03-04', null, null, '⚽', '스피드스케이팅', '올림픽메달', '국가대표'],
  ['ath-jeongjaewon', '정재원', null, '2000-07-22', null, null, '⚽', '스피드스케이팅', '국가대표', '유망주'],

  // ===== 사격/양궁/기타 올림픽 (Shooting/Archery/Other Olympics) =====
  ['ath-jinjongoh', '진종오', 'Jin Jong-oh', '1979-09-24', null, null, '⚽', '사격', '올림픽금메달', '레전드'],
  ['ath-ansan', '안산', 'An San', '2001-02-27', null, null, '⚽', '양궁', '올림픽금메달', '삼관왕'],
  ['ath-anseyoung', '안세영', 'An Se-young', '2002-02-17', null, null, '⚽', '배드민턴', '올림픽금메달', '국가대표'],
  ['ath-shinyubin', '신유빈', 'Shin Yu-bin', '2004-07-05', null, null, '⚽', '탁구', '올림픽메달', '국가대표'],
  ['ath-limsihyun', '임시현', 'Lim Si-hyeon', '2004-04-18', null, null, '⚽', '양궁', '올림픽금메달', '국가대표'],
  ['ath-woosanghyuk', '우상혁', 'Woo Sang-hyeok', '1996-04-20', null, null, '⚽', '높이뛰기', '올림픽메달', '국가대표'],
  ['ath-jeonhunyoung', '전훈영', 'Jeon Hun-young', '2001-12-10', null, null, '⚽', '양궁', '올림픽금메달', '국가대표'],
  ['ath-leeunji', '이은지', 'Lee Eun-ji', '2002-06-28', null, null, '⚽', '양궁', '올림픽금메달', '국가대표'],
  ['ath-kimwoomin', '김우민', 'Kim Woo-min', '1997-03-31', null, null, '⚽', '수영', '올림픽메달', '국가대표'],
  ['ath-jeonghyosung', '전효성', 'Jun Hyo-seong', '1989-10-13', null, null, '⚽', '양궁', '올림픽금메달', '국가대표'],
  ['ath-changhyejin', '장혜진', 'Chang Hye-jin', '1987-05-13', null, null, '⚽', '양궁', '올림픽금메달', '국가대표'],
  ['ath-kijabae', '기보배', 'Ki Bo-bae', '1988-02-20', null, null, '⚽', '양궁', '올림픽금메달', '레전드'],
  ['ath-ohjin', '오진혁', 'Oh Jin-hyek', '1981-08-15', null, null, '⚽', '양궁', '올림픽금메달', '레전드'],
  ['ath-kuyonggi', '구본길', 'Gu Bon-gil', '1989-05-12', null, null, '⚽', '펜싱', '올림픽금메달', '국가대표'],
  ['ath-kimahnah', '김지연', 'Kim Ji-yeon', '1988-12-07', null, null, '⚽', '펜싱', '올림픽금메달', '국가대표'],
  ['ath-parksonghee', '박상영', 'Park Sang-young', '1995-06-15', null, null, '⚽', '펜싱', '올림픽금메달', '국가대표'],
  ['ath-songyeajin', '송아인', null, '1999-03-12', null, null, '⚽', '펜싱', '국가대표', '올림픽'],
  ['ath-ohsangyuk', '오상욱', 'Oh Sang-uk', '1996-06-13', null, null, '⚽', '펜싱', '올림픽금메달', '국가대표'],
  ['ath-leejuyeon', '이주연', null, '2001-10-05', null, null, '⚽', '태권도', '국가대표', '올림픽'],
  ['ath-parktugeon', '박태건', null, '1998-04-19', null, null, '⚽', '태권도', '국가대표', '올림픽'],
  ['ath-leodahbin', '이다빈', 'Lee Da-bin', '2001-03-02', null, null, '⚽', '태권도', '올림픽메달', '국가대표'],
  ['ath-hwangkyungseon', '황경선', 'Hwang Kyung-seon', '1986-06-29', null, null, '⚽', '태권도', '올림픽금메달', '레전드'],
  ['ath-simkwanchul', '심권호', 'Sim Kwon-ho', '1976-01-12', null, null, '⚽', '레슬링', '올림픽금메달', '레전드'],
  ['ath-yanghakhseon', '양학선', 'Yang Hak-seon', '1992-12-05', null, null, '⚽', '체조', '올림픽금메달', '도마왕'],
  ['ath-yeoeseo', '여서정', 'Yeo Seo-jeong', '2002-03-17', null, null, '⚽', '체조', '올림픽메달', '국가대표'],

  // ===== 복싱/격투기 (Boxing/MMA) =====
  ['ath-choosung', '추성훈', 'Choo Sung-hoon', '1975-10-20', null, null, '⚽', '격투기', 'MMA', '한일'],
  ['ath-kimdonghyun', '김동현', 'Kim Dong-hyun', '1981-02-01', null, null, '⚽', '격투기', 'MMA', 'UFC'],
  ['ath-jungchansung', '정찬성', 'Jung Chan-sung', '1987-03-17', null, null, '⚽', '격투기', 'UFC', '코리안좀비'],
  ['ath-songyadong', '송야동', 'Song Yadong', '1997-12-04', null, null, '⚽', '격투기', 'UFC', '중국'],
  ['ath-mcgregor', '코너 맥그리거', 'Conor McGregor', '1988-07-14', null, null, '⚽', '격투기', 'UFC', '아일랜드'],
  ['ath-khabib', '하빕 누르마고메도프', 'Khabib Nurmagomedov', '1988-09-20', null, null, '⚽', '격투기', 'UFC', '러시아'],
  ['ath-choiminki', '최민기', null, '1993-08-12', null, null, '⚽', '격투기', 'MMA', '한국'],
  ['ath-kimjiyeon', '김지연', null, '1990-02-14', null, null, '⚽', '복싱', '국가대표', '여성'],

  // ===== e스포츠 (Esports) =====
  ['ath-faker', '이상혁 (Faker)', 'Faker', '1996-05-07', null, 'T1', '⚽', 'e스포츠', 'LoL', '미드'],
  ['ath-deft', '김혁규 (Deft)', 'Deft', '1996-10-23', null, null, '⚽', 'e스포츠', 'LoL', '원딜'],
  ['ath-showmaker', '허수 (ShowMaker)', 'ShowMaker', '2000-04-22', null, 'DK', '⚽', 'e스포츠', 'LoL', '미드'],
  ['ath-canyon', '김건부 (Canyon)', 'Canyon', '2001-06-18', null, 'DK', '⚽', 'e스포츠', 'LoL', '정글'],
  ['ath-chovy', '정지훈 (Chovy)', 'Chovy', '2001-03-03', null, 'GEN', '⚽', 'e스포츠', 'LoL', '미드'],
  ['ath-ruler', '박재혁 (Ruler)', 'Ruler', '1998-08-10', null, null, '⚽', 'e스포츠', 'LoL', '원딜'],
  ['ath-keria', '류민석 (Keria)', 'Keria', '2002-08-14', null, 'T1', '⚽', 'e스포츠', 'LoL', '서포터'],
  ['ath-zeus', '최우제 (Zeus)', 'Zeus', '2004-02-23', null, 'T1', '⚽', 'e스포츠', 'LoL', '탑'],
  ['ath-gumayusi', '이민형 (Gumayusi)', 'Gumayusi', '2002-05-06', null, 'T1', '⚽', 'e스포츠', 'LoL', '원딜'],
  ['ath-beryl', '조건희 (BeryL)', 'BeryL', '1999-06-23', null, null, '⚽', 'e스포츠', 'LoL', '서포터'],
  ['ath-oner', '문현준 (Oner)', 'Oner', '2003-05-24', null, 'T1', '⚽', 'e스포츠', 'LoL', '정글'],
  ['ath-peyz', '김사우 (Peyz)', 'Peyz', '2005-09-03', null, 'GEN', '⚽', 'e스포츠', 'LoL', '원딜'],
  ['ath-lehends', '손시우 (Lehends)', 'Lehends', '1998-08-12', null, 'GEN', '⚽', 'e스포츠', 'LoL', '서포터'],
  ['ath-viper', '박도현 (Viper)', 'Viper', '2000-09-11', null, null, '⚽', 'e스포츠', 'LoL', '원딜'],
  ['ath-bengi', '배성웅 (Bengi)', 'Bengi', '1994-03-15', null, null, '⚽', 'e스포츠', 'LoL', '정글레전드'],
  ['ath-bang', '배준식 (Bang)', 'Bang', '1996-05-17', null, null, '⚽', 'e스포츠', 'LoL', '원딜레전드'],
  ['ath-wolf', '이재완 (Wolf)', 'Wolf', '1996-12-01', null, null, '⚽', 'e스포츠', 'LoL', '서포터레전드'],
  ['ath-mata', '조세형 (Mata)', 'Mata', '1994-05-27', null, null, '⚽', 'e스포츠', 'LoL', '서포터레전드'],
  ['ath-peanut', '한왕호 (Peanut)', 'Peanut', '1998-01-17', null, null, '⚽', 'e스포츠', 'LoL', '정글'],
  ['ath-nuguri', '장하권 (Nuguri)', 'Nuguri', '2000-03-06', null, null, '⚽', 'e스포츠', 'LoL', '탑'],
  ['ath-teddy', '박진성 (Teddy)', 'Teddy', '1998-02-03', null, null, '⚽', 'e스포츠', 'LoL', '원딜'],
  ['ath-bdd', '곽보성 (BDD)', 'BDD', '1999-03-19', null, null, '⚽', 'e스포츠', 'LoL', '미드'],
  ['ath-tarzan', '이승용 (Tarzan)', 'Tarzan', '1999-12-18', null, null, '⚽', 'e스포츠', 'LoL', '정글'],
  ['ath-smeb', '송경호 (Smeb)', 'Smeb', '1995-05-26', null, null, '⚽', 'e스포츠', 'LoL', '탑레전드'],
  ['ath-score', '고동빈 (Score)', 'Score', '1994-02-26', null, null, '⚽', 'e스포츠', 'LoL', '정글레전드'],
  ['ath-madlife', '홍민기 (MadLife)', 'MadLife', '1992-05-30', null, null, '⚽', 'e스포츠', 'LoL', '서포터레전드'],
  ['ath-flame', '이호종 (Flame)', 'Flame', '1994-02-28', null, null, '⚽', 'e스포츠', 'LoL', '탑레전드'],
  ['ath-imp', '구승빈 (imp)', 'imp', '1995-02-22', null, null, '⚽', 'e스포츠', 'LoL', '원딜레전드'],
  ['ath-ambition', '강찬용 (Ambition)', 'Ambition', '1992-03-06', null, null, '⚽', 'e스포츠', 'LoL', '미드레전드'],
  ['ath-t1-effort', '이상호 (Effort)', 'Effort', '2001-11-22', null, null, '⚽', 'e스포츠', 'LoL', '서포터'],
  // 스타크래프트
  ['ath-flash', '이영호 (Flash)', 'Flash', '1992-07-05', null, null, '⚽', 'e스포츠', '스타크래프트', '갓영호'],
  ['ath-jaedong', '이제동 (Jaedong)', 'Jaedong', '1990-09-09', null, null, '⚽', 'e스포츠', '스타크래프트', '이제동'],
  ['ath-bisu', '김택용 (Bisu)', 'Bisu', '1989-07-05', null, null, '⚽', 'e스포츠', '스타크래프트', '혁명가'],
  ['ath-stork', '송병구 (Stork)', 'Stork', '1988-10-20', null, null, '⚽', 'e스포츠', '스타크래프트', '완벽한 프로토스'],
  ['ath-nada', '이윤열 (NaDa)', 'NaDa', '1984-07-10', null, null, '⚽', 'e스포츠', '스타크래프트', '천재테란'],
  ['ath-boxer', '임요환 (BoxeR)', 'BoxeR', '1980-06-04', null, null, '⚽', 'e스포츠', '스타크래프트', '테란의황제'],
  ['ath-savior', '마재윤 (sAviOr)', 'sAviOr', '1986-02-02', null, null, '⚽', 'e스포츠', '스타크래프트', '저그의왕'],
  ['ath-july', '박성준 (JulyZerg)', 'July', '1986-09-13', null, null, '⚽', 'e스포츠', '스타크래프트', '신의손'],
  ['ath-fantasy', '정명훈 (FanTaSy)', 'FanTaSy', '1991-12-20', null, null, '⚽', 'e스포츠', '스타크래프트', '조폭테란'],
  ['ath-rain', '정윤종 (Rain)', 'Rain', '1988-01-19', null, null, '⚽', 'e스포츠', '스타크래프트', '완벽한 프로토스'],

  // ===== 골프 (Golf) =====
  ['ath-parkseungri', '박세리', 'Pak Se-ri', '1977-09-28', null, null, '⚽', '골프', 'LPGA', '레전드'],
  ['ath-gojinan', '고진영', 'Ko Jin-young', '1995-07-07', null, null, '⚽', '골프', 'LPGA', '세계랭킹1위'],
  ['ath-parkingee', '박인비', 'Park Inbee', '1988-07-12', null, null, '⚽', '골프', 'LPGA', '올림픽금메달'],
  ['ath-kimseoyoung', '김세영', 'Kim Sei-young', '1993-04-21', null, null, '⚽', '골프', 'LPGA', '국가대표'],
  ['ath-ryusooyeon', '유소연', 'Ryu So-yeon', '1990-06-24', null, null, '⚽', '골프', 'LPGA', '메이저우승'],
  ['ath-jeonginji', '전인지', 'Jeon In-gee', '1994-05-09', null, null, '⚽', '골프', 'LPGA', '메이저우승'],
  ['ath-choijinaeun', '최나은', null, '2000-02-15', null, null, '⚽', '골프', 'KLPGA', '신인'],
  ['ath-kimhyojoo', '김효주', 'Kim Hyo-joo', '1995-07-28', null, null, '⚽', '골프', 'LPGA', '올림픽메달'],
  ['ath-parkchaeyoung', '박채영', null, '2001-09-14', null, null, '⚽', '골프', 'KLPGA', '유망주'],
  ['ath-imsung', '임성재', 'Im Sung-jae', '1998-06-10', null, null, '⚽', '골프', 'PGA', '남자골프'],
  ['ath-kimjoohyung', '김주형', 'Tom Kim', '2002-06-21', null, null, '⚽', '골프', 'PGA', '남자골프'],
  ['ath-yangyoungin', '양용은', 'Y.E. Yang', '1972-01-15', null, null, '⚽', '골프', 'PGA', '레전드'],
  ['ath-choikyoungjoo', '최경주', 'K.J. Choi', '1970-05-19', null, null, '⚽', '골프', 'PGA', '레전드'],
  ['ath-leekeeunhee', '이근희', null, '2003-03-28', null, null, '⚽', '골프', 'KLPGA', '유망주'],
  ['ath-woodstiger', '타이거 우즈', 'Tiger Woods', '1975-12-30', null, null, '⚽', '골프', 'PGA', '미국'],
  ['ath-mcilroy', '로리 매킬로이', 'Rory McIlroy', '1989-05-04', null, null, '⚽', '골프', 'PGA', '북아일랜드'],
  ['ath-scheffler', '스코티 셰플러', 'Scottie Scheffler', '1996-06-21', null, null, '⚽', '골프', 'PGA', '미국'],

  // ===== 테니스 (Tennis) =====
  ['ath-chunghyeon', '정현', 'Chung Hyeon', '1996-05-19', null, null, '⚽', '테니스', 'ATP', '한국'],
  ['ath-kwonsoowoo', '권순우', 'Kwon Soon-woo', '1997-11-02', null, null, '⚽', '테니스', 'ATP', '한국'],
  ['ath-djokovic', '노박 조코비치', 'Novak Djokovic', '1987-05-22', null, null, '⚽', '테니스', 'ATP', '세르비아'],
  ['ath-nadal', '라파엘 나달', 'Rafael Nadal', '1986-06-03', null, null, '⚽', '테니스', 'ATP', '스페인'],
  ['ath-federer', '로저 페더러', 'Roger Federer', '1981-08-08', null, null, '⚽', '테니스', 'ATP', '스위스'],
  ['ath-sinner', '야닉 시너', 'Jannik Sinner', '2001-08-16', null, null, '⚽', '테니스', 'ATP', '이탈리아'],
  ['ath-alcaraz', '카를로스 알카라스', 'Carlos Alcaraz', '2003-05-05', null, null, '⚽', '테니스', 'ATP', '스페인'],
  ['ath-osaka', '오사카 나오미', 'Naomi Osaka', '1997-10-16', null, null, '⚽', '테니스', 'WTA', '일본'],
  ['ath-swiatek', '이가 시비옹텍', 'Iga Swiatek', '2001-05-31', null, null, '⚽', '테니스', 'WTA', '폴란드'],
  ['ath-williamss', '세리나 윌리엄스', 'Serena Williams', '1981-09-26', null, null, '⚽', '테니스', 'WTA', '미국'],

  // ===== 농구 (Basketball) =====
  ['ath-haseungjin', '하승진', 'Ha Seung-jin', '1985-08-04', null, null, '⚽', '농구', 'NBA', '한국'],
  ['ath-leehyunjung', '이현중', null, '2001-11-15', null, null, '⚽', '농구', 'KBL', '유망주'],
  ['ath-lebron', '르브론 제임스', 'LeBron James', '1984-12-30', null, 'LA 레이커스', '⚽', '농구', 'NBA', '미국'],
  ['ath-curry', '스테판 커리', 'Stephen Curry', '1988-03-14', null, 'GS 워리어스', '⚽', '농구', 'NBA', '미국'],
  ['ath-jordan', '마이클 조던', 'Michael Jordan', '1963-02-17', null, null, '⚽', '농구', 'NBA', '레전드'],
  ['ath-durant', '케빈 듀란트', 'Kevin Durant', '1988-09-29', null, '피닉스 선즈', '⚽', '농구', 'NBA', '미국'],
  ['ath-giannis', '야니스 안테토쿤보', 'Giannis Antetokounmpo', '1994-12-06', null, '밀워키 벅스', '⚽', '농구', 'NBA', '그리스'],
  ['ath-jokic', '니콜라 요키치', 'Nikola Jokic', '1995-02-19', null, '덴버 너겟츠', '⚽', '농구', 'NBA', '세르비아'],
  ['ath-luka', '루카 돈치치', 'Luka Doncic', '1999-02-28', null, 'LA 레이커스', '⚽', '농구', 'NBA', '슬로베니아'],
  ['ath-yao', '야오밍', 'Yao Ming', '1980-09-12', null, null, '⚽', '농구', 'NBA', '중국'],
  ['ath-wemby', '빅터 웸반야마', 'Victor Wembanyama', '2004-01-04', null, 'SA 스퍼스', '⚽', '농구', 'NBA', '프랑스'],
  ['ath-tatum', '제이슨 테이텀', 'Jayson Tatum', '1998-03-03', null, '보스턴 셀틱스', '⚽', '농구', 'NBA', '미국'],

  // ===== 배구 (Volleyball) =====
  ['ath-kimyeonkyoung', '김연경', 'Kim Yeon-koung', '1988-02-26', null, null, '⚽', '배구', 'V리그', '식신'],
  ['ath-kimsuyoung', '김수지', null, '1993-11-22', null, null, '⚽', '배구', 'V리그', '국가대표'],
  ['ath-yanghaoji', '양효진', null, '1990-03-25', null, null, '⚽', '배구', 'V리그', '국가대표'],
  ['ath-parkjeongah', '박정아', null, '1993-01-11', null, null, '⚽', '배구', 'V리그', '국가대표'],
  ['ath-leesoyoung', '이소영', null, '1994-07-18', null, null, '⚽', '배구', 'V리그', '국가대표'],

  // ===== 육상 (Track & Field) =====
  ['ath-bolt', '우사인 볼트', 'Usain Bolt', '1986-08-21', null, null, '⚽', '육상', '단거리', '자메이카'],
  ['ath-kipchoge', '엘리우드 킵초게', 'Eliud Kipchoge', '1984-11-05', null, null, '⚽', '육상', '마라톤', '케냐'],
  ['ath-leeboyoung', '이보영', null, '1994-04-22', null, null, '⚽', '육상', '높이뛰기', '한국'],
  ['ath-jeongyewon', '정예원', null, '2001-09-08', null, null, '⚽', '육상', '허들', '한국'],
  ['ath-kimnakwan', '김국영', null, '1991-01-22', null, null, '⚽', '육상', '단거리', '한국'],

  // ===== 수영 (Swimming) =====
  ['ath-phelps', '마이클 펠프스', 'Michael Phelps', '1985-06-30', null, null, '⚽', '수영', '올림픽금메달', '미국'],
  ['ath-hwangsunwoo', '황선우', 'Hwang Sun-woo', '2003-05-21', null, null, '⚽', '수영', '국가대표', '자유형'],
  ['ath-dressel', '케일럽 드레셀', 'Caeleb Dressel', '1996-08-16', null, null, '⚽', '수영', '올림픽금메달', '미국'],

  // ===== 종합격투기/복싱 추가 =====
  ['ath-pacquiao', '매니 파퀴아오', 'Manny Pacquiao', '1978-12-17', null, null, '⚽', '복싱', '세계챔피언', '필리핀'],
  ['ath-mayweather', '플로이드 메이웨더', 'Floyd Mayweather', '1977-02-24', null, null, '⚽', '복싱', '무패챔피언', '미국'],
  ['ath-tyson', '마이크 타이슨', 'Mike Tyson', '1966-06-30', null, null, '⚽', '복싱', '헤비급', '미국'],
  ['ath-fury', '타이슨 퓨리', 'Tyson Fury', '1988-08-12', null, null, '⚽', '복싱', '헤비급', '영국'],

  // ===== F1/모터스포츠 =====
  ['ath-hamilton', '루이스 해밀턴', 'Lewis Hamilton', '1985-01-07', null, '페라리', '⚽', 'F1', '드라이버', '영국'],
  ['ath-verstappen', '막스 페르스타펀', 'Max Verstappen', '1997-09-30', null, '레드불', '⚽', 'F1', '드라이버', '네덜란드'],
  ['ath-norris', '란도 노리스', 'Lando Norris', '1999-11-13', null, '맥라렌', '⚽', 'F1', '드라이버', '영국'],

  // ===== 체스/기타 마인드 스포츠 =====
  ['ath-leesedol', '이세돌', 'Lee Sedol', '1983-03-02', null, null, '⚽', '바둑', '9단', '레전드'],
  ['ath-shinminjun', '신민준', 'Shin Min-jun', '1999-01-11', null, null, '⚽', '바둑', '9단', '국가대표'],
  ['ath-parkjunghwan', '박정환', 'Park Jung-hwan', '1994-07-11', null, null, '⚽', '바둑', '9단', '국가대표'],
  ['ath-choejeong', '최정', 'Choi Jeong', '1996-12-26', null, null, '⚽', '바둑', '9단', '여성1인자'],
  ['ath-leechanbee', '이창호', 'Lee Chang-ho', '1975-07-29', null, null, '⚽', '바둑', '9단', '신산'],
  ['ath-chohunyun', '조훈현', 'Cho Hunhyun', '1953-03-10', null, null, '⚽', '바둑', '9단', '레전드'],
  ['ath-carlsen', '매그너스 칼센', 'Magnus Carlsen', '1990-11-30', null, null, '⚽', '체스', '그랜드마스터', '노르웨이'],

  // ===== 추가 한국 축구 (K리그/여자축구) =====
  ['ath-jisooyun', '지소연', 'Ji So-yun', '1991-02-21', null, null, '⚽', '축구', '여자축구', '레전드'],
  ['ath-leegeummin', '이금민', 'Lee Geum-min', '1994-02-26', null, null, '⚽', '축구', '여자축구', '국가대표'],
  ['ath-chosooyoung', '조소현', 'Cho So-hyun', '1988-06-24', null, null, '⚽', '축구', '여자축구', '국가대표'],
  ['ath-kimjung', '김정미', null, '1990-08-10', null, null, '⚽', '축구', '여자축구', '국가대표'],
  ['ath-parkeunseul', '박은선', null, '1986-11-27', null, null, '⚽', '축구', '여자축구', '레전드'],

  // ===== 추가 쇼트트랙/빙상 =====
  ['ath-anohyun', '안현수', 'Ahn Hyun-soo', '1985-11-23', null, null, '⚽', '쇼트트랙', '올림픽금메달', '빅토르안'],
  ['ath-kwakwingi', '곽윤기', 'Kwak Yun-gy', '1989-12-06', null, null, '⚽', '쇼트트랙', '올림픽메달', '국가대표'],
  ['ath-leejunho2', '이준호', null, '2002-04-10', null, null, '⚽', '쇼트트랙', '국가대표', '유망주'],
  ['ath-kimgunwoo', '김건우', null, '2003-01-18', null, null, '⚽', '쇼트트랙', '국가대표', '유망주'],

  // ===== 추가 야구 KBO/MLB =====
  ['ath-leejongbeom', '이종범', 'Lee Jong-beom', '1970-09-02', null, null, '⚽', '야구', '내야수', 'KBO레전드'],
  ['ath-leemansoo', '이만수', null, '1958-06-17', null, null, '⚽', '야구', '포수', 'KBO레전드'],
  ['ath-sundongryul', '선동열', 'Sun Dong-yol', '1963-01-10', null, null, '⚽', '야구', '투수', 'KBO레전드'],
  ['ath-parkchulsoon', '박철순', null, '1956-08-18', null, null, '⚽', '야구', '투수', 'KBO레전드'],
  ['ath-changhojae', '장호재', null, '2001-07-25', null, null, '⚽', '야구', '투수', 'KBO'],
  ['ath-kimhajoon', '김하준', null, '2004-02-08', null, null, '⚽', '야구', '내야수', '유망주'],
  ['ath-leeminhyuk', '이민혁', null, '2003-09-12', null, null, '⚽', '야구', '외야수', 'KBO'],
  ['ath-kimeunbi', '김은비', null, '2002-05-28', null, null, '⚽', '야구', '투수', '여자야구'],
  ['ath-naseungryul', '나승현', null, '2000-03-05', null, null, '⚽', '야구', '투수', 'KBO'],
  ['ath-juseunghwan', '주승환', null, '2001-11-03', null, null, '⚽', '야구', '투수', 'KBO'],
  ['ath-songjunho', '송주호', null, '2002-07-14', null, null, '⚽', '야구', '내야수', 'KBO'],
  ['ath-choiminjun', '최민준', null, '2003-04-22', null, null, '⚽', '야구', '외야수', '유망주'],

  // ===== 추가 국제 축구 =====
  ['ath-griezmann', '앙투안 그리즈만', 'Antoine Griezmann', '1991-03-21', null, '아틀레티코', '⚽', '축구', '공격수', '프랑스'],
  ['ath-benzema', '카림 벤제마', 'Karim Benzema', '1987-12-19', null, '알이티하드', '⚽', '축구', '공격수', '프랑스'],
  ['ath-bruno', '브루노 페르난데스', 'Bruno Fernandes', '1994-09-08', null, '맨유', '⚽', '축구', '미드필더', '포르투갈'],
  ['ath-foden', '필 포든', 'Phil Foden', '2000-05-28', null, '맨시티', '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-rice', '데클런 라이스', 'Declan Rice', '1999-01-14', null, '아스날', '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-dias', '루벤 디아스', 'Ruben Dias', '1997-05-14', null, '맨시티', '⚽', '축구', '수비수', '포르투갈'],
  ['ath-palmer', '콜 팔머', 'Cole Palmer', '2002-05-06', null, '첼시', '⚽', '축구', '공격수', '잉글랜드'],
  ['ath-watkins', '올리 왓킨스', 'Ollie Watkins', '1995-12-30', null, '아스톤빌라', '⚽', '축구', '공격수', '잉글랜드'],
  ['ath-kane', '해리 케인', 'Harry Kane', '1993-07-28', null, '바이에른 뮌헨', '⚽', '축구', '공격수', '잉글랜드'],
  ['ath-sonny-extra', '손준호', 'Son Jun-ho', '1992-03-12', null, null, '⚽', '축구', '미드필더', 'K리그'],

  // ===== 추가 골프/테니스 =====
  ['ath-nelyko', '넬리 코르다', 'Nelly Korda', '1998-07-28', null, null, '⚽', '골프', 'LPGA', '미국'],
  ['ath-hovland', '빅토르 호블란', 'Viktor Hovland', '1997-09-18', null, null, '⚽', '골프', 'PGA', '노르웨이'],
  ['ath-rahm', '존 람', 'Jon Rahm', '1994-11-10', null, null, '⚽', '골프', 'LIV', '스페인'],
  ['ath-koepka', '브룩스 켑카', 'Brooks Koepka', '1990-05-03', null, null, '⚽', '골프', 'LIV', '미국'],

  // ===== 추가 e스포츠 (오버워치/발로란트) =====
  ['ath-profit', '박준영 (Profit)', 'Profit', '1999-06-16', null, null, '⚽', 'e스포츠', '오버워치', 'DPS'],
  ['ath-carpe', '이재혁 (Carpe)', 'Carpe', '1998-08-21', null, null, '⚽', 'e스포츠', '오버워치', 'DPS'],
  ['ath-gesture', '홍재희 (Gesture)', 'Gesture', '1998-03-04', null, null, '⚽', 'e스포츠', '오버워치', '탱커'],
  ['ath-ryujehong', '류제홍 (ryujehong)', 'ryujehong', '1994-06-08', null, null, '⚽', 'e스포츠', '오버워치', '서포트'],
  ['ath-jjonak', '방성현 (JJoNak)', 'JJoNak', '1998-07-08', null, null, '⚽', 'e스포츠', '오버워치', '서포트'],
  ['ath-leave', '이원혁 (Leave)', 'Leave', '2002-04-15', null, null, '⚽', 'e스포츠', '오버워치', 'DPS'],
  ['ath-shu', '김진서 (Shu)', 'Shu', '2000-12-22', null, null, '⚽', 'e스포츠', '오버워치', '서포트'],
  ['ath-mako', '김동현 (MaKo)', 'MaKo', '2001-05-11', null, null, '⚽', 'e스포츠', '오버워치', '탱커'],

  // ===== 클라이밍/신종목 =====
  ['ath-chungjongwon', '천종원', null, '2002-09-15', null, null, '⚽', '스포츠클라이밍', '국가대표', '올림픽'],
  ['ath-seojuwan', '서채현', null, '2003-01-08', null, null, '⚽', '스포츠클라이밍', '국가대표', '올림픽'],

  // ===== 추가 국제 농구 =====
  ['ath-embiid', '조엘 엠비드', 'Joel Embiid', '1994-03-16', null, '필라 76ers', '⚽', '농구', 'NBA', '카메룬'],
  ['ath-morant', '자 모랜트', 'Ja Morant', '1999-08-10', null, '멤피스', '⚽', '농구', 'NBA', '미국'],
  ['ath-edwards', '앤서니 에드워즈', 'Anthony Edwards', '2001-08-05', null, '미네소타', '⚽', '농구', 'NBA', '미국'],
  ['ath-kobe', '코비 브라이언트', 'Kobe Bryant', '1978-08-23', null, null, '⚽', '농구', 'NBA', '레전드'],
  ['ath-shaq', '샤킬 오닐', 'Shaquille ONeal', '1972-03-06', null, null, '⚽', '농구', 'NBA', '레전드'],
  ['ath-iverson', '앨런 아이버슨', 'Allen Iverson', '1975-06-07', null, null, '⚽', '농구', 'NBA', '레전드'],
  ['ath-duncan', '팀 던컨', 'Tim Duncan', '1976-04-25', null, null, '⚽', '농구', 'NBA', '레전드'],

  // ===== 피겨 국제 =====
  ['ath-hanyu', '하뉴 유즈루', 'Yuzuru Hanyu', '1994-12-07', null, null, '⚽', '피겨스케이팅', '올림픽금메달', '일본'],
  ['ath-chen', '네이선 첸', 'Nathan Chen', '1999-05-05', null, null, '⚽', '피겨스케이팅', '올림픽금메달', '미국'],
  ['ath-zagitova', '알리나 자기토바', 'Alina Zagitova', '2002-05-18', null, null, '⚽', '피겨스케이팅', '올림픽금메달', '러시아'],

  // ===== 추가 한국 올림픽 종목 =====
  ['ath-songgina', '송기나', null, '1997-08-25', null, null, '⚽', '유도', '국가대표', '올림픽'],
  ['ath-kimwonhi', '김원진', null, '1995-04-08', null, null, '⚽', '유도', '국가대표', '올림픽메달'],
  ['ath-anbaul', '안바울', null, '1994-04-15', null, null, '⚽', '유도', '올림픽메달', '국가대표'],
  ['ath-anchangrim', '안창림', 'An Chang-rim', '1994-09-15', null, null, '⚽', '유도', '올림픽동메달', '국가대표'],
  ['ath-kimsojung', '김소정', null, '2003-06-30', null, null, '⚽', '유도', '국가대표', '유망주'],
  ['ath-jungjae', '이준재', null, '1998-03-27', null, null, '⚽', '사격', '국가대표', '올림픽'],
  ['ath-kimyeji', '김예지', 'Kim Ye-ji', '1992-07-20', null, null, '⚽', '사격', '올림픽은메달', '국가대표'],
  ['ath-leewonje', '오상은', null, '2001-05-19', null, null, '⚽', '사격', '국가대표', '유망주'],
  ['ath-banthomas', '반효진', 'Ban Hyo-jin', '2004-04-17', null, null, '⚽', '사격', '올림픽금메달', '국가대표'],

  // ===== 추가 전설적 국제 선수 =====
  ['ath-ali', '무하마드 알리', 'Muhammad Ali', '1942-01-17', null, null, '⚽', '복싱', '헤비급', '레전드'],
  ['ath-schumacher', '미하엘 슈마허', 'Michael Schumacher', '1969-01-03', null, null, '⚽', 'F1', '드라이버', '독일'],
  ['ath-senna', '아일턴 세나', 'Ayrton Senna', '1960-03-21', null, null, '⚽', 'F1', '드라이버', '브라질'],
  ['ath-gretzky', '웨인 그레츠키', 'Wayne Gretzky', '1961-01-26', null, null, '⚽', '아이스하키', 'NHL', '캐나다'],
  ['ath-ruth', '베이브 루스', 'Babe Ruth', '1895-02-06', null, null, '⚽', '야구', '외야수', 'MLB레전드'],
  ['ath-brady', '톰 브래디', 'Tom Brady', '1977-08-03', null, null, '⚽', '미식축구', 'NFL', '미국'],
  ['ath-mahomes', '패트릭 마홈스', 'Patrick Mahomes', '1995-09-17', null, '캔자스시티', '⚽', '미식축구', 'NFL', '미국'],
  ['ath-ronaldo-br', '호나우두', 'Ronaldo', '1976-09-18', null, null, '⚽', '축구', '공격수', '브라질레전드'],
  ['ath-platini', '미셸 플라티니', 'Michel Platini', '1955-06-21', null, null, '⚽', '축구', '미드필더', '프랑스레전드'],
  ['ath-cruyff', '요한 크라위프', 'Johan Cruyff', '1947-04-25', null, null, '⚽', '축구', '공격수', '네덜란드레전드'],
  ['ath-bergkamp', '데니스 베르캄프', 'Dennis Bergkamp', '1969-05-10', null, null, '⚽', '축구', '공격수', '네덜란드레전드'],
  ['ath-baggio', '로베르토 바조', 'Roberto Baggio', '1967-02-18', null, null, '⚽', '축구', '공격수', '이탈리아'],

  // ===== 추가 한국 운동선수 (다양한 종목) =====
  ['ath-parkjongwoo', '박종호', null, '2003-08-07', null, null, '⚽', '탁구', '국가대표', '유망주'],
  ['ath-leesangsoo', '이상수', null, '1991-01-30', null, null, '⚽', '탁구', '국가대표', '올림픽'],
  ['ath-jeongjunghwa', '정정화', null, '1969-04-20', null, null, '⚽', '탁구', '올림픽금메달', '레전드'],
  ['ath-hyungunghee', '현정화', null, '1969-10-06', null, null, '⚽', '탁구', '올림픽금메달', '레전드'],
  ['ath-leeyakyung', '이다영', null, '1996-07-15', null, null, '⚽', '배구', 'V리그', '국가대표'],
  ['ath-leejain', '이재영', null, '1996-07-15', null, null, '⚽', '배구', 'V리그', '국가대표'],
  ['ath-kimheeojin', '김희진', null, '1995-02-24', null, null, '⚽', '배구', 'V리그', '국가대표'],
  ['ath-kimyongjae', '김용대', null, '1990-02-12', null, null, '⚽', '핸드볼', '국가대표', '올림픽'],
  ['ath-leegwanlae', '이관래', null, '1998-09-17', null, null, '⚽', '핸드볼', '국가대표', '올림픽'],

  // ===== 추가 e스포츠 (발로란트/기타) =====
  ['ath-stax', '김구택 (stax)', 'stax', '1999-02-12', null, null, '⚽', 'e스포츠', '발로란트', 'DRX'],
  ['ath-rb', '고석현 (Rb)', 'Rb', '2002-11-30', null, null, '⚽', 'e스포츠', '발로란트', 'DRX'],
  ['ath-zest', '김기석 (Zest)', 'Zest', '2002-09-07', null, null, '⚽', 'e스포츠', '발로란트', 'DRX'],
  ['ath-mako2', '김명관 (MaKo)', 'MaKo', '2001-01-03', null, null, '⚽', 'e스포츠', '발로란트', 'DRX'],
  ['ath-buzz', '유서준 (BuZz)', 'BuZz', '2002-09-15', null, null, '⚽', 'e스포츠', '발로란트', 'DRX'],
  ['ath-s1mple', '알렉산더 코스틸리에프 (s1mple)', 's1mple', '1997-10-02', null, null, '⚽', 'e스포츠', 'CS2', '우크라이나'],
  ['ath-device', '니콜라이 리데츠 (dev1ce)', 'dev1ce', '1995-09-08', null, null, '⚽', 'e스포츠', 'CS2', '덴마크'],

  // ===== 럭비/크리켓/기타 =====
  ['ath-lomu', '조나 로무', 'Jonah Lomu', '1975-05-12', null, null, '⚽', '럭비', '전설', '뉴질랜드'],
  ['ath-kohli', '비랏 콜리', 'Virat Kohli', '1988-11-05', null, null, '⚽', '크리켓', '타자', '인도'],
  ['ath-tendulkar', '사친 텐둘카', 'Sachin Tendulkar', '1973-04-24', null, null, '⚽', '크리켓', '전설', '인도'],

  // ===== 추가 동계 스포츠 =====
  ['ath-shaun', '숀 화이트', 'Shaun White', '1986-09-03', null, null, '⚽', '스노보드', '올림픽금메달', '미국'],
  ['ath-chloekim', '클로이 김', 'Chloe Kim', '2000-04-23', null, null, '⚽', '스노보드', '올림픽금메달', '미국'],
  ['ath-leesanghee', '이상호', 'Lee Sang-ho', '1995-02-09', null, null, '⚽', '스노보드', '올림픽메달', '한국'],
  ['ath-yunchaeongeum', '윤성빈', 'Yun Sung-bin', '1994-05-23', null, null, '⚽', '스켈레톤', '올림픽금메달', '한국'],
  ['ath-kimsibeon', '김지수', null, '2002-12-05', null, null, '⚽', '컬링', '국가대표', '올림픽'],
  ['ath-kimeunji2', '김은정', 'Kim Eun-jung', '1990-11-29', null, null, '⚽', '컬링', '올림픽은메달', '팀킴'],
  ['ath-kimseonji', '김선영', null, '1994-09-04', null, null, '⚽', '컬링', '올림픽은메달', '팀킴'],
  ['ath-kimyeongmi', '김영미', null, '1990-02-06', null, null, '⚽', '컬링', '올림픽은메달', '팀킴'],
  ['ath-kimkyeonae', '김경애', null, '1991-11-05', null, null, '⚽', '컬링', '올림픽은메달', '팀킴'],
  ['ath-kimchoyoung', '김초희', null, '1995-07-15', null, null, '⚽', '컬링', '올림픽은메달', '팀킴'],

  // ===== 추가 국제 축구 선수 =====
  ['ath-drogba', '디디에 드로그바', 'Didier Drogba', '1978-03-11', null, null, '⚽', '축구', '공격수', '코트디부아르'],
  ['ath-etoo', '사무엘 에투', 'Samuel Etoo', '1981-03-10', null, null, '⚽', '축구', '공격수', '카메룬'],
  ['ath-cafu', '카푸', 'Cafu', '1970-06-07', null, null, '⚽', '축구', '수비수', '브라질레전드'],
  ['ath-pirlo', '안드레아 피를로', 'Andrea Pirlo', '1979-05-19', null, null, '⚽', '축구', '미드필더', '이탈리아'],
  ['ath-kaka', '카카', 'Kaka', '1982-04-22', null, null, '⚽', '축구', '미드필더', '브라질'],
  ['ath-lampard', '프랭크 램파드', 'Frank Lampard', '1978-06-20', null, null, '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-gerrard', '스티븐 제라드', 'Steven Gerrard', '1980-05-30', null, null, '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-scholes', '폴 스콜스', 'Paul Scholes', '1974-11-16', null, null, '⚽', '축구', '미드필더', '잉글랜드'],
  ['ath-cantona', '에릭 칸토나', 'Eric Cantona', '1966-05-24', null, null, '⚽', '축구', '공격수', '프랑스'],
  ['ath-totti', '프란체스코 토티', 'Francesco Totti', '1976-09-27', null, null, '⚽', '축구', '공격수', '이탈리아'],
  ['ath-delpieo', '알레산드로 델 피에로', 'Alessandro Del Piero', '1974-11-09', null, null, '⚽', '축구', '공격수', '이탈리아'],
  ['ath-raul', '라울', 'Raul', '1977-06-27', null, null, '⚽', '축구', '공격수', '스페인'],
  ['ath-rivaldo', '리발도', 'Rivaldo', '1972-04-19', null, null, '⚽', '축구', '공격수', '브라질'],
  ['ath-seedorf', '클라렌스 시도르프', 'Clarence Seedorf', '1976-04-01', null, null, '⚽', '축구', '미드필더', '네덜란드'],
  ['ath-puyol', '카를레스 푸욜', 'Carles Puyol', '1978-04-13', null, null, '⚽', '축구', '수비수', '스페인'],
  ['ath-maldini', '파올로 말디니', 'Paolo Maldini', '1968-06-26', null, null, '⚽', '축구', '수비수', '이탈리아'],
  ['ath-nesta', '알레산드로 네스타', 'Alessandro Nesta', '1976-03-19', null, null, '⚽', '축구', '수비수', '이탈리아'],
  ['ath-buffon', '잔루이지 부폰', 'Gianluigi Buffon', '1978-01-28', null, null, '⚽', '축구', '골키퍼', '이탈리아'],
  ['ath-casillas', '이케르 카시야스', 'Iker Casillas', '1981-05-20', null, null, '⚽', '축구', '골키퍼', '스페인'],
  ['ath-neuer', '마누엘 노이어', 'Manuel Neuer', '1986-03-27', null, null, '⚽', '축구', '골키퍼', '독일'],
  ['ath-muller', '토마스 뮐러', 'Thomas Muller', '1989-09-13', null, '바이에른', '⚽', '축구', '공격수', '독일'],
  ['ath-havertz', '카이 하베르츠', 'Kai Havertz', '1999-06-11', null, '아스날', '⚽', '축구', '공격수', '독일'],
  ['ath-wirtz', '플로리안 비르츠', 'Florian Wirtz', '2003-05-03', null, '레버쿠젠', '⚽', '축구', '미드필더', '독일'],
  ['ath-saliba', '윌리엄 살리바', 'William Saliba', '2001-03-24', null, '아스날', '⚽', '축구', '수비수', '프랑스'],
  ['ath-tchouameni', '오렐리앙 추아메니', 'Aurelien Tchouameni', '2000-01-27', null, '레알 마드리드', '⚽', '축구', '미드필더', '프랑스'],
  ['ath-osimhen', '빅터 오시멘', 'Victor Osimhen', '1998-12-29', null, null, '⚽', '축구', '공격수', '나이지리아'],
  ['ath-nunez', '다르윈 누녜스', 'Darwin Nunez', '1999-06-24', null, '리버풀', '⚽', '축구', '공격수', '우루과이'],
]
