// [id, name, nameEn|null, birthDate(YYYY-MM-DD), birthHour|null, group|null, emoji, ...tags]
export default [
  // ===== WESTERN MUSICIANS =====
  // --- Pop / Solo Artists ---
  ['gl-taylor-swift', '테일러 스위프트', 'Taylor Swift', '1989-12-13', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-billie-eilish', '빌리 아일리시', 'Billie Eilish', '2001-12-18', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-olivia-rodrigo', '올리비아 로드리고', 'Olivia Rodrigo', '2003-02-20', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-ariana-grande', '아리아나 그란데', 'Ariana Grande', '1993-06-26', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-beyonce', '비욘세', 'Beyoncé', '1981-09-04', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-rihanna', '리한나', 'Rihanna', '1988-02-20', null, null, '🌍', '가수', '팝스타', '바베이도스'],
  ['gl-lady-gaga', '레이디 가가', 'Lady Gaga', '1986-03-28', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-adele', '아델', 'Adele', '1988-05-05', null, null, '🌍', '가수', '팝스타', '영국'],
  ['gl-ed-sheeran', '에드 시런', 'Ed Sheeran', '1991-02-17', null, null, '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-bruno-mars', '브루노 마스', 'Bruno Mars', '1985-10-08', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-the-weeknd', '더 위켄드', 'The Weeknd', '1990-02-16', null, null, '🌍', '가수', 'R&B', '캐나다'],
  ['gl-drake', '드레이크', 'Drake', '1986-10-24', null, null, '🌍', '래퍼', '가수', '캐나다'],
  ['gl-post-malone', '포스트 말론', 'Post Malone', '1995-07-04', null, null, '🌍', '가수', '래퍼', '미국'],
  ['gl-dua-lipa', '두아 리파', 'Dua Lipa', '1995-08-22', null, null, '🌍', '가수', '팝스타', '영국'],
  ['gl-harry-styles', '해리 스타일스', 'Harry Styles', '1994-02-01', null, 'One Direction', '🌍', '가수', '팝스타', '영국'],
  ['gl-zayn-malik', '제인 말릭', 'Zayn Malik', '1993-01-12', null, 'One Direction', '🌍', '가수', '팝스타', '영국'],
  ['gl-louis-tomlinson', '루이 톰린슨', 'Louis Tomlinson', '1991-12-24', null, 'One Direction', '🌍', '가수', '팝스타', '영국'],
  ['gl-niall-horan', '나일 호란', 'Niall Horan', '1993-09-13', null, 'One Direction', '🌍', '가수', '팝스타', '아일랜드'],
  ['gl-liam-payne', '리암 페인', 'Liam Payne', '1993-08-29', null, 'One Direction', '🌍', '가수', '팝스타', '영국'],
  ['gl-justin-bieber', '저스틴 비버', 'Justin Bieber', '1994-03-01', null, null, '🌍', '가수', '팝스타', '캐나다'],
  ['gl-selena-gomez', '셀레나 고메즈', 'Selena Gomez', '1992-07-22', null, null, '🌍', '가수', '배우', '미국'],
  ['gl-demi-lovato', '데미 로바토', 'Demi Lovato', '1992-08-20', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-miley-cyrus', '마일리 사이러스', 'Miley Cyrus', '1992-11-23', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-shawn-mendes', '숀 멘데스', 'Shawn Mendes', '1998-08-08', null, null, '🌍', '가수', '싱어송라이터', '캐나다'],
  ['gl-charlie-puth', '찰리 푸스', 'Charlie Puth', '1991-12-02', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-sabrina-carpenter', '사브리나 카펜터', 'Sabrina Carpenter', '1999-05-11', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-chappell-roan', '채플 론', 'Chappell Roan', '1998-02-19', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-gracie-abrams', '그레이시 에이브럼스', 'Gracie Abrams', '1999-09-07', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-ice-spice', '아이스 스파이스', 'Ice Spice', '2000-01-01', null, null, '🌍', '래퍼', '미국'],
  ['gl-sza', 'SZA', 'SZA', '1989-11-08', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-doja-cat', '도자 캣', 'Doja Cat', '1995-10-21', null, null, '🌍', '가수', '래퍼', '미국'],
  ['gl-megan-thee-stallion', '메간 더 스탤리언', 'Megan Thee Stallion', '1995-02-15', null, null, '🌍', '래퍼', '미국'],
  ['gl-nicki-minaj', '니키 미나즈', 'Nicki Minaj', '1982-12-08', null, null, '🌍', '래퍼', '가수', '트리니다드토바고'],
  ['gl-cardi-b', '카디 비', 'Cardi B', '1992-10-11', null, null, '🌍', '래퍼', '미국'],
  ['gl-travis-scott', '트래비스 스캇', 'Travis Scott', '1991-04-30', null, null, '🌍', '래퍼', '미국'],
  ['gl-kanye-west', '카니예 웨스트', 'Kanye West', '1977-06-08', null, null, '🌍', '래퍼', '프로듀서', '미국'],
  ['gl-jay-z', '제이지', 'Jay-Z', '1969-12-04', null, null, '🌍', '래퍼', '사업가', '미국'],
  ['gl-eminem', '에미넴', 'Eminem', '1972-10-17', null, null, '🌍', '래퍼', '미국'],
  ['gl-kendrick-lamar', '켄드릭 라마', 'Kendrick Lamar', '1987-06-17', null, null, '🌍', '래퍼', '미국'],
  ['gl-j-cole', '제이 콜', 'J. Cole', '1985-01-28', null, null, '🌍', '래퍼', '미국'],
  ['gl-21-savage', '21 새비지', '21 Savage', '1992-10-22', null, null, '🌍', '래퍼', '영국'],
  ['gl-lil-nas-x', '릴 나스 엑스', 'Lil Nas X', '1999-04-09', null, null, '🌍', '래퍼', '가수', '미국'],
  ['gl-bad-bunny', '배드 버니', 'Bad Bunny', '1994-03-10', null, null, '🌍', '가수', '래퍼', '푸에르토리코'],
  ['gl-rosalia', '로살리아', 'Rosalía', '1992-09-25', null, null, '🌍', '가수', '스페인'],
  ['gl-troye-sivan', '트로이 시반', 'Troye Sivan', '1995-06-05', null, null, '🌍', '가수', '배우', '호주'],
  ['gl-lana-del-rey', '라나 델 레이', 'Lana Del Rey', '1985-06-21', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-halsey', '홀시', 'Halsey', '1994-09-29', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-lizzo', '리조', 'Lizzo', '1988-04-27', null, null, '🌍', '가수', '래퍼', '미국'],
  ['gl-sam-smith', '샘 스미스', 'Sam Smith', '1992-05-19', null, null, '🌍', '가수', '팝스타', '영국'],
  ['gl-frank-ocean', '프랭크 오션', 'Frank Ocean', '1987-10-28', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-tyler-the-creator', '타일러 더 크리에이터', 'Tyler, the Creator', '1991-03-06', null, null, '🌍', '래퍼', '프로듀서', '미국'],
  ['gl-steve-lacy', '스티브 레이시', 'Steve Lacy', '1998-05-23', null, null, '🌍', '가수', '기타리스트', '미국'],
  ['gl-kevin-parker', '케빈 파커', 'Kevin Parker', '1986-01-20', null, 'Tame Impala', '🌍', '가수', '뮤지션', '호주'],
  ['gl-pharrell-williams', '퍼렐 윌리엄스', 'Pharrell Williams', '1973-04-05', null, null, '🌍', '프로듀서', '가수', '미국'],
  ['gl-john-legend', '존 레전드', 'John Legend', '1978-12-28', null, null, '🌍', '가수', '피아니스트', '미국'],
  ['gl-michael-buble', '마이클 부블레', 'Michael Bublé', '1975-09-09', null, null, '🌍', '가수', '캐나다'],
  ['gl-hozier', '호지어', 'Hozier', '1990-03-17', null, null, '🌍', '가수', '싱어송라이터', '아일랜드'],
  ['gl-lewis-capaldi', '루이스 카팔디', 'Lewis Capaldi', '1996-10-07', null, null, '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-olivia-dean', '올리비아 딘', 'Olivia Dean', '1999-07-14', null, null, '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-tate-mcrae', '테이트 맥래', 'Tate McRae', '2003-07-01', null, null, '🌍', '가수', '댄서', '캐나다'],
  ['gl-benson-boone', '벤슨 분', 'Benson Boone', '2002-06-25', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-noah-kahan', '노아 칸', 'Noah Kahan', '1997-01-01', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-mitski', '미츠키', 'Mitski', '1990-09-27', null, null, '🌍', '가수', '싱어송라이터', '일본계미국'],
  ['gl-phoebe-bridgers', '피비 브리저스', 'Phoebe Bridgers', '1994-08-17', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-boygenius-julien', '줄리엔 베이커', 'Julien Baker', '1995-09-29', null, 'boygenius', '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-boygenius-lucy', '루시 다커스', 'Lucy Dacus', '1995-05-02', null, 'boygenius', '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-victoria-monet', '빅토리아 모네', 'Victoria Monét', '1989-05-01', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-madison-beer', '매디슨 비어', 'Madison Beer', '1999-03-05', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-dove-cameron', '도브 카메론', 'Dove Cameron', '1996-01-15', null, null, '🌍', '가수', '배우', '미국'],
  ['gl-sia', '시아', 'Sia', '1975-12-18', null, null, '🌍', '가수', '싱어송라이터', '호주'],
  ['gl-lorde', '로드', 'Lorde', '1996-11-07', null, null, '🌍', '가수', '싱어송라이터', '뉴질랜드'],
  ['gl-charli-xcx', '찰리 XCX', 'Charli XCX', '1992-08-02', null, null, '🌍', '가수', '팝스타', '영국'],
  ['gl-aurora', '오로라', 'Aurora', '1996-06-15', null, null, '🌍', '가수', '싱어송라이터', '노르웨이'],
  ['gl-camila-cabello', '카밀라 카베요', 'Camila Cabello', '1997-03-03', null, null, '🌍', '가수', '팝스타', '쿠바계미국'],
  ['gl-normani', '노마니', 'Normani', '1996-05-31', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-becky-g', '베키 지', 'Becky G', '1997-03-02', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-rina-sawayama', '리나 사와야마', 'Rina Sawayama', '1990-08-16', null, null, '🌍', '가수', '싱어송라이터', '일본계영국'],
  ['gl-grimes', '그라임스', 'Grimes', '1988-03-17', null, null, '🌍', '가수', '뮤지션', '캐나다'],
  ['gl-tyla', '타일라', 'Tyla', '2002-01-30', null, null, '🌍', '가수', '팝스타', '남아프리카'],
  ['gl-raye', '레이', 'Raye', '1997-10-24', null, null, '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-jessie-ware', '제시 웨어', 'Jessie Ware', '1984-10-15', null, null, '🌍', '가수', '팝스타', '영국'],
  ['gl-jorja-smith', '조자 스미스', 'Jorja Smith', '1997-06-11', null, null, '🌍', '가수', 'R&B', '영국'],
  ['gl-arlo-parks', '알로 파크스', 'Arlo Parks', '2000-08-09', null, null, '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-fka-twigs', 'FKA 트위그스', 'FKA Twigs', '1988-01-16', null, null, '🌍', '가수', '아티스트', '영국'],
  ['gl-ashnikko', '애쉬니코', 'Ashnikko', '1996-02-19', null, null, '🌍', '래퍼', '가수', '미국'],
  ['gl-clairo', '클레이로', 'Clairo', '1998-08-18', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-maggie-rogers', '매기 로저스', 'Maggie Rogers', '1994-04-25', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-kehlani', '켈라니', 'Kehlani', '1995-04-24', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-summers-walker', '서머 워커', 'Summer Walker', '1996-04-11', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-jhene-aiko', '제이네 아이코', 'Jhené Aiko', '1988-03-16', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-kali-uchis', '칼리 우치스', 'Kali Uchis', '1994-07-17', null, null, '🌍', '가수', 'R&B', '콜롬비아계미국'],
  ['gl-anitta', '아니타', 'Anitta', '1993-03-30', null, null, '🌍', '가수', '팝스타', '브라질'],
  ['gl-shakira', '샤키라', 'Shakira', '1977-02-02', null, null, '🌍', '가수', '팝스타', '콜롬비아'],
  ['gl-jennifer-lopez', '제니퍼 로페즈', 'Jennifer Lopez', '1969-07-24', null, null, '🌍', '가수', '배우', '미국'],
  ['gl-katy-perry', '케이티 페리', 'Katy Perry', '1984-10-25', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-pink', '핑크', 'P!nk', '1979-09-08', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-alicia-keys', '앨리샤 키스', 'Alicia Keys', '1981-01-25', null, null, '🌍', '가수', '피아니스트', '미국'],
  ['gl-tinashe', '티나셰', 'Tinashe', '1993-02-06', null, null, '🌍', '가수', 'R&B', '미국'],

  // --- BLACKPINK (as global stars) ---
  ['gl-jisoo', '지수', 'Jisoo', '1995-01-03', null, 'BLACKPINK', '🌍', '가수', '아이돌', '한국'],
  ['gl-jennie', '제니', 'Jennie', '1996-01-16', null, 'BLACKPINK', '🌍', '가수', '아이돌', '한국'],
  ['gl-rose', '로제', 'Rosé', '1997-02-11', null, 'BLACKPINK', '🌍', '가수', '아이돌', '한국'],
  ['gl-lisa', '리사', 'Lisa', '1997-03-27', null, 'BLACKPINK', '🌍', '가수', '아이돌', '태국'],

  // --- BTS (as global stars) ---
  ['gl-rm', 'RM', 'RM', '1994-09-12', null, 'BTS', '🌍', '가수', '래퍼', '한국'],
  ['gl-jin', '진', 'Jin', '1992-12-04', null, 'BTS', '🌍', '가수', '아이돌', '한국'],
  ['gl-suga', '슈가', 'Suga', '1993-03-09', null, 'BTS', '🌍', '가수', '래퍼', '한국'],
  ['gl-jhope', '제이홉', 'J-Hope', '1994-02-18', null, 'BTS', '🌍', '가수', '댄서', '한국'],
  ['gl-jimin', '지민', 'Jimin', '1995-10-13', null, 'BTS', '🌍', '가수', '댄서', '한국'],
  ['gl-v', '뷔', 'V', '1995-12-30', null, 'BTS', '🌍', '가수', '배우', '한국'],
  ['gl-jungkook', '정국', 'Jungkook', '1997-09-01', null, 'BTS', '🌍', '가수', '아이돌', '한국'],

  // --- Coldplay ---
  ['gl-chris-martin', '크리스 마틴', 'Chris Martin', '1977-03-02', null, 'Coldplay', '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-jonny-buckland', '조니 버클랜드', 'Jonny Buckland', '1977-09-11', null, 'Coldplay', '🌍', '기타리스트', '영국'],
  ['gl-guy-berryman', '가이 베리먼', 'Guy Berryman', '1978-04-12', null, 'Coldplay', '🌍', '베이시스트', '영국'],
  ['gl-will-champion', '윌 챔피언', 'Will Champion', '1978-07-31', null, 'Coldplay', '🌍', '드러머', '영국'],

  // --- Imagine Dragons ---
  ['gl-dan-reynolds', '댄 레이놀즈', 'Dan Reynolds', '1987-07-14', null, 'Imagine Dragons', '🌍', '가수', '록밴드', '미국'],
  ['gl-wayne-sermon', '웨인 서먼', 'Wayne Sermon', '1984-06-15', null, 'Imagine Dragons', '🌍', '기타리스트', '미국'],
  ['gl-ben-mckee', '벤 매키', 'Ben McKee', '1985-04-07', null, 'Imagine Dragons', '🌍', '베이시스트', '미국'],
  ['gl-daniel-platzman', '대니얼 플레츠먼', 'Daniel Platzman', '1986-09-28', null, 'Imagine Dragons', '🌍', '드러머', '미국'],

  // --- Maroon 5 ---
  ['gl-adam-levine', '아담 레빈', 'Adam Levine', '1979-03-18', null, 'Maroon 5', '🌍', '가수', '록밴드', '미국'],

  // --- OneRepublic ---
  ['gl-ryan-tedder', '라이언 테더', 'Ryan Tedder', '1979-06-26', null, 'OneRepublic', '🌍', '가수', '프로듀서', '미국'],

  // --- twenty one pilots ---
  ['gl-tyler-joseph', '타일러 조셉', 'Tyler Joseph', '1988-12-01', null, 'twenty one pilots', '🌍', '가수', '뮤지션', '미국'],
  ['gl-josh-dun', '조시 던', 'Josh Dun', '1988-06-18', null, 'twenty one pilots', '🌍', '드러머', '미국'],

  // --- Panic! at the Disco ---
  ['gl-brendon-urie', '브렌던 유리', 'Brendon Urie', '1987-04-12', null, 'Panic! at the Disco', '🌍', '가수', '뮤지션', '미국'],

  // --- Fall Out Boy ---
  ['gl-patrick-stump', '패트릭 스텀프', 'Patrick Stump', '1984-04-27', null, 'Fall Out Boy', '🌍', '가수', '록밴드', '미국'],
  ['gl-pete-wentz', '피트 웬츠', 'Pete Wentz', '1979-06-05', null, 'Fall Out Boy', '🌍', '베이시스트', '록밴드', '미국'],
  ['gl-joe-trohman', '조 트로먼', 'Joe Trohman', '1984-09-01', null, 'Fall Out Boy', '🌍', '기타리스트', '미국'],
  ['gl-andy-hurley', '앤디 헐리', 'Andy Hurley', '1980-05-31', null, 'Fall Out Boy', '🌍', '드러머', '미국'],

  // --- Green Day ---
  ['gl-billie-joe-armstrong', '빌리 조 암스트롱', 'Billie Joe Armstrong', '1972-02-17', null, 'Green Day', '🌍', '가수', '기타리스트', '미국'],
  ['gl-mike-dirnt', '마이크 던트', 'Mike Dirnt', '1972-05-04', null, 'Green Day', '🌍', '베이시스트', '미국'],
  ['gl-tre-cool', '트레 쿨', 'Tré Cool', '1972-12-09', null, 'Green Day', '🌍', '드러머', '미국'],

  // --- Foo Fighters ---
  ['gl-dave-grohl', '데이브 그롤', 'Dave Grohl', '1969-01-14', null, 'Foo Fighters', '🌍', '가수', '드러머', '미국'],

  // --- Red Hot Chili Peppers ---
  ['gl-anthony-kiedis', '앤서니 키디스', 'Anthony Kiedis', '1962-11-01', null, 'Red Hot Chili Peppers', '🌍', '가수', '록밴드', '미국'],
  ['gl-flea', '플리', 'Flea', '1962-10-16', null, 'Red Hot Chili Peppers', '🌍', '베이시스트', '호주'],
  ['gl-chad-smith', '채드 스미스', 'Chad Smith', '1961-10-25', null, 'Red Hot Chili Peppers', '🌍', '드러머', '미국'],
  ['gl-john-frusciante', '존 프루시안테', 'John Frusciante', '1970-03-05', null, 'Red Hot Chili Peppers', '🌍', '기타리스트', '미국'],

  // --- Radiohead ---
  ['gl-thom-yorke', '톰 요크', 'Thom Yorke', '1968-10-07', null, 'Radiohead', '🌍', '가수', '뮤지션', '영국'],

  // --- Arctic Monkeys ---
  ['gl-alex-turner', '알렉스 터너', 'Alex Turner', '1986-01-06', null, 'Arctic Monkeys', '🌍', '가수', '기타리스트', '영국'],

  // --- The 1975 ---
  ['gl-matty-healy', '매티 힐리', 'Matty Healy', '1989-04-08', null, 'The 1975', '🌍', '가수', '뮤지션', '영국'],

  // ===== MUSIC LEGENDS =====
  ['gl-michael-jackson', '마이클 잭슨', 'Michael Jackson', '1958-08-29', null, null, '🌍', '가수', '팝의 황제', '미국'],
  ['gl-prince', '프린스', 'Prince', '1958-06-07', null, null, '🌍', '가수', '뮤지션', '미국'],
  ['gl-whitney-houston', '휘트니 휴스턴', 'Whitney Houston', '1963-08-09', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-freddie-mercury', '프레디 머큐리', 'Freddie Mercury', '1946-09-05', null, 'Queen', '🌍', '가수', '록밴드', '영국'],
  ['gl-david-bowie', '데이비드 보위', 'David Bowie', '1947-01-08', null, null, '🌍', '가수', '뮤지션', '영국'],
  ['gl-elvis-presley', '엘비스 프레슬리', 'Elvis Presley', '1935-01-08', null, null, '🌍', '가수', '록의 황제', '미국'],
  ['gl-john-lennon', '존 레넌', 'John Lennon', '1940-10-09', null, 'The Beatles', '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-paul-mccartney', '폴 매카트니', 'Paul McCartney', '1942-06-18', null, 'The Beatles', '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-george-harrison', '조지 해리슨', 'George Harrison', '1943-02-25', null, 'The Beatles', '🌍', '기타리스트', '영국'],
  ['gl-ringo-starr', '링고 스타', 'Ringo Starr', '1940-07-07', null, 'The Beatles', '🌍', '드러머', '영국'],
  ['gl-bob-dylan', '밥 딜런', 'Bob Dylan', '1941-05-24', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-madonna', '마돈나', 'Madonna', '1958-08-16', null, null, '🌍', '가수', '팝의 여왕', '미국'],
  ['gl-elton-john', '엘튼 존', 'Elton John', '1947-03-25', null, null, '🌍', '가수', '피아니스트', '영국'],
  ['gl-stevie-wonder', '스티비 원더', 'Stevie Wonder', '1950-05-13', null, null, '🌍', '가수', '뮤지션', '미국'],
  ['gl-mariah-carey', '머라이어 캐리', 'Mariah Carey', '1969-03-27', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-celine-dion', '셀린 디온', 'Céline Dion', '1968-03-30', null, null, '🌍', '가수', '팝스타', '캐나다'],
  ['gl-amy-winehouse', '에이미 와인하우스', 'Amy Winehouse', '1983-09-14', null, null, '🌍', '가수', '재즈', '영국'],
  ['gl-kurt-cobain', '커트 코베인', 'Kurt Cobain', '1967-02-20', null, 'Nirvana', '🌍', '가수', '그런지', '미국'],
  ['gl-tupac', '투팍', 'Tupac Shakur', '1971-06-16', null, null, '🌍', '래퍼', '미국'],
  ['gl-notorious-big', '노토리어스 B.I.G.', 'The Notorious B.I.G.', '1972-05-21', null, null, '🌍', '래퍼', '미국'],
  ['gl-bob-marley', '밥 말리', 'Bob Marley', '1945-02-06', null, null, '🌍', '가수', '레게', '자메이카'],
  ['gl-jimi-hendrix', '지미 헨드릭스', 'Jimi Hendrix', '1942-11-27', null, null, '🌍', '기타리스트', '록', '미국'],
  ['gl-janis-joplin', '재니스 조플린', 'Janis Joplin', '1943-01-19', null, null, '🌍', '가수', '록', '미국'],
  ['gl-aretha-franklin', '아레사 프랭클린', 'Aretha Franklin', '1942-03-25', null, null, '🌍', '가수', '소울의 여왕', '미국'],
  ['gl-ray-charles', '레이 찰스', 'Ray Charles', '1930-09-23', null, null, '🌍', '가수', '피아니스트', '미국'],
  ['gl-frank-sinatra', '프랭크 시나트라', 'Frank Sinatra', '1915-12-12', null, null, '🌍', '가수', '배우', '미국'],
  ['gl-nina-simone', '니나 시몬', 'Nina Simone', '1933-02-21', null, null, '🌍', '가수', '피아니스트', '미국'],
  ['gl-billie-holiday', '빌리 홀리데이', 'Billie Holiday', '1915-04-07', null, null, '🌍', '가수', '재즈', '미국'],
  ['gl-louis-armstrong', '루이 암스트롱', 'Louis Armstrong', '1901-08-04', null, null, '🌍', '트럼펫연주자', '재즈', '미국'],
  ['gl-miles-davis', '마일스 데이비스', 'Miles Davis', '1926-05-26', null, null, '🌍', '트럼펫연주자', '재즈', '미국'],

  // ===== MORE CONTEMPORARY ARTISTS =====
  ['gl-the-weeknd-alt', '위켄드', null, '1990-02-16', null, null, '🌍', '가수', 'R&B', '캐나다'],
  ['gl-jack-harlow', '잭 할로우', 'Jack Harlow', '1998-03-13', null, null, '🌍', '래퍼', '미국'],
  ['gl-metro-boomin', '메트로 부민', 'Metro Boomin', '1993-09-16', null, null, '🌍', '프로듀서', '미국'],
  ['gl-future', '퓨처', 'Future', '1983-11-20', null, null, '🌍', '래퍼', '미국'],
  ['gl-gunna', '거나', 'Gunna', '1993-06-14', null, null, '🌍', '래퍼', '미국'],
  ['gl-lil-baby', '릴 베이비', 'Lil Baby', '1994-12-03', null, null, '🌍', '래퍼', '미국'],
  ['gl-roddy-ricch', '로디 리치', 'Roddy Ricch', '1998-10-22', null, null, '🌍', '래퍼', '미국'],
  ['gl-juice-wrld', '주스 월드', 'Juice WRLD', '1998-12-02', null, null, '🌍', '래퍼', '미국'],
  ['gl-xxxtentacion', 'XXXTentacion', 'XXXTentacion', '1998-01-23', null, null, '🌍', '래퍼', '미국'],
  ['gl-mac-miller', '맥 밀러', 'Mac Miller', '1992-01-19', null, null, '🌍', '래퍼', '미국'],
  ['gl-childish-gambino', '차일디시 감비노', 'Childish Gambino', '1983-09-25', null, null, '🌍', '래퍼', '배우', '미국'],
  ['gl-chance-the-rapper', '챈스 더 래퍼', 'Chance the Rapper', '1993-04-16', null, null, '🌍', '래퍼', '미국'],
  ['gl-asap-rocky', '에이셉 라키', 'A$AP Rocky', '1988-10-03', null, null, '🌍', '래퍼', '미국'],
  ['gl-playboi-carti', '플레이보이 카르티', 'Playboi Carti', '1996-09-13', null, null, '🌍', '래퍼', '미국'],
  ['gl-don-toliver', '돈 톨리버', 'Don Toliver', '1994-06-12', null, null, '🌍', '래퍼', '가수', '미국'],
  ['gl-suki-waterhouse', '수키 워터하우스', 'Suki Waterhouse', '1992-01-05', null, null, '🌍', '가수', '모델', '영국'],
  ['gl-billie-marten', '빌리 마틴', 'Billie Marten', '1999-04-17', null, null, '🌍', '가수', '싱어송라이터', '영국'],
  ['gl-florence-welch', '플로렌스 웰치', 'Florence Welch', '1986-08-28', null, 'Florence and the Machine', '🌍', '가수', '록', '영국'],
  ['gl-haim-este', '에스테 하임', 'Este Haim', '1986-03-14', null, 'HAIM', '🌍', '베이시스트', '미국'],
  ['gl-haim-danielle', '다니엘 하임', 'Danielle Haim', '1989-02-16', null, 'HAIM', '🌍', '기타리스트', '미국'],
  ['gl-haim-alana', '알라나 하임', 'Alana Haim', '1991-12-15', null, 'HAIM', '🌍', '기타리스트', '미국'],
  ['gl-weyes-blood', '와이즈 블러드', 'Weyes Blood', '1988-06-11', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-caroline-polachek', '캐롤라인 폴라첵', 'Caroline Polachek', '1985-06-20', null, null, '🌍', '가수', '싱어송라이터', '미국'],
  ['gl-ethel-cain', '에델 케인', 'Ethel Cain', '1998-04-15', null, null, '🌍', '가수', '싱어송라이터', '미국'],

  // --- Latin Artists ---
  ['gl-j-balvin', '제이 발빈', 'J Balvin', '1985-05-07', null, null, '🌍', '가수', '레게톤', '콜롬비아'],
  ['gl-ozuna', '오주나', 'Ozuna', '1992-03-13', null, null, '🌍', '가수', '레게톤', '푸에르토리코'],
  ['gl-daddy-yankee', '대디 양키', 'Daddy Yankee', '1976-02-03', null, null, '🌍', '가수', '레게톤', '푸에르토리코'],
  ['gl-maluma', '말루마', 'Maluma', '1994-01-28', null, null, '🌍', '가수', '레게톤', '콜롬비아'],
  ['gl-karol-g', '카롤 지', 'Karol G', '1991-02-14', null, null, '🌍', '가수', '레게톤', '콜롬비아'],
  ['gl-rauw-alejandro', '라우 알레한드로', 'Rauw Alejandro', '1993-01-10', null, null, '🌍', '가수', '레게톤', '푸에르토리코'],
  ['gl-peso-pluma', '페소 플루마', 'Peso Pluma', '1999-06-15', null, null, '🌍', '가수', '멕시코음악', '멕시코'],
  ['gl-feid', '페이드', 'Feid', '1992-08-19', null, null, '🌍', '가수', '레게톤', '콜롬비아'],

  // --- K-pop (additional global) ---
  ['gl-psy', '싸이', 'PSY', '1977-12-31', null, null, '🌍', '가수', 'K-pop', '한국'],
  ['gl-cl', 'CL', 'CL', '1991-02-26', null, null, '🌍', '가수', '래퍼', '한국'],
  ['gl-hyuna', '현아', 'HyunA', '1992-06-06', null, null, '🌍', '가수', '아이돌', '한국'],
  ['gl-iu-global', '아이유', 'IU', '1993-05-16', null, null, '🌍', '가수', '싱어송라이터', '한국'],
  ['gl-rain', '비', 'Rain', '1982-06-25', null, null, '🌍', '가수', '배우', '한국'],

  // --- EDM / Electronic ---
  ['gl-marshmello', '마시멜로', 'Marshmello', '1992-05-19', null, null, '🌍', 'DJ', '프로듀서', '미국'],
  ['gl-calvin-harris', '캘빈 해리스', 'Calvin Harris', '1984-01-17', null, null, '🌍', 'DJ', '프로듀서', '영국'],
  ['gl-david-guetta', '데이빗 게타', 'David Guetta', '1967-11-07', null, null, '🌍', 'DJ', '프로듀서', '프랑스'],
  ['gl-skrillex', '스크릴렉스', 'Skrillex', '1988-01-15', null, null, '🌍', 'DJ', '프로듀서', '미국'],
  ['gl-deadmau5', '데드마우스', 'deadmau5', '1981-01-05', null, null, '🌍', 'DJ', '프로듀서', '캐나다'],
  ['gl-avicii', '아비치', 'Avicii', '1989-09-08', null, null, '🌍', 'DJ', '프로듀서', '스웨덴'],
  ['gl-martin-garrix', '마틴 가릭스', 'Martin Garrix', '1996-05-14', null, null, '🌍', 'DJ', '프로듀서', '네덜란드'],
  ['gl-zedd', '제드', 'Zedd', '1989-09-02', null, null, '🌍', 'DJ', '프로듀서', '독일'],
  ['gl-diplo', '디플로', 'Diplo', '1978-11-10', null, null, '🌍', 'DJ', '프로듀서', '미국'],
  ['gl-kygo', '카이고', 'Kygo', '1991-09-11', null, null, '🌍', 'DJ', '프로듀서', '노르웨이'],
  ['gl-illenium', '일레니엄', 'Illenium', '1990-12-26', null, null, '🌍', 'DJ', '프로듀서', '미국'],
  ['gl-fred-again', '프레드 어게인', 'Fred Again..', '1993-11-12', null, null, '🌍', 'DJ', '프로듀서', '영국'],

  // --- More Bands ---
  ['gl-mick-jagger', '믹 재거', 'Mick Jagger', '1943-07-26', null, 'The Rolling Stones', '🌍', '가수', '록', '영국'],
  ['gl-keith-richards', '키스 리차드', 'Keith Richards', '1943-12-18', null, 'The Rolling Stones', '🌍', '기타리스트', '록', '영국'],
  ['gl-robert-plant', '로버트 플랜트', 'Robert Plant', '1948-08-20', null, 'Led Zeppelin', '🌍', '가수', '록', '영국'],
  ['gl-jimmy-page', '지미 페이지', 'Jimmy Page', '1944-01-09', null, 'Led Zeppelin', '🌍', '기타리스트', '록', '영국'],
  ['gl-roger-waters', '로저 워터스', 'Roger Waters', '1943-09-06', null, 'Pink Floyd', '🌍', '베이시스트', '록', '영국'],
  ['gl-bono', '보노', 'Bono', '1960-05-10', null, 'U2', '🌍', '가수', '록', '아일랜드'],
  ['gl-the-edge', '디 에지', 'The Edge', '1961-08-08', null, 'U2', '🌍', '기타리스트', '록', '영국'],
  ['gl-eddie-vedder', '에디 베더', 'Eddie Vedder', '1964-12-23', null, 'Pearl Jam', '🌍', '가수', '그런지', '미국'],
  ['gl-chester-bennington', '체스터 베닝턴', 'Chester Bennington', '1976-03-20', null, 'Linkin Park', '🌍', '가수', '록밴드', '미국'],
  ['gl-mike-shinoda', '마이크 시노다', 'Mike Shinoda', '1977-02-11', null, 'Linkin Park', '🌍', '래퍼', '프로듀서', '미국'],
  ['gl-gerard-way', '제라드 웨이', 'Gerard Way', '1977-04-09', null, 'My Chemical Romance', '🌍', '가수', '록밴드', '미국'],
  ['gl-hayley-williams', '헤일리 윌리엄스', 'Hayley Williams', '1988-12-27', null, 'Paramore', '🌍', '가수', '록밴드', '미국'],

  // ===== TECH / BUSINESS LEADERS =====
  ['gl-elon-musk', '일론 머스크', 'Elon Musk', '1971-06-28', null, null, '🌍', '사업가', 'CEO', '남아프리카'],
  ['gl-jeff-bezos', '제프 베이조스', 'Jeff Bezos', '1964-01-12', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-mark-zuckerberg', '마크 저커버그', 'Mark Zuckerberg', '1984-05-14', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-bill-gates', '빌 게이츠', 'Bill Gates', '1955-10-28', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-steve-jobs', '스티브 잡스', 'Steve Jobs', '1955-02-24', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-tim-cook', '팀 쿡', 'Tim Cook', '1960-11-01', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-satya-nadella', '사티아 나델라', 'Satya Nadella', '1967-08-19', null, null, '🌍', '사업가', 'CEO', '인도'],
  ['gl-sundar-pichai', '순다르 피차이', 'Sundar Pichai', '1972-06-10', null, null, '🌍', '사업가', 'CEO', '인도'],
  ['gl-sam-altman', '샘 알트만', 'Sam Altman', '1985-04-22', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-jensen-huang', '젠슨 황', 'Jensen Huang', '1963-02-17', null, null, '🌍', '사업가', 'CEO', '대만계미국'],
  ['gl-jack-ma', '마윈', 'Jack Ma', '1964-09-10', null, null, '🌍', '사업가', 'CEO', '중국'],
  ['gl-warren-buffett', '워런 버핏', 'Warren Buffett', '1930-08-30', null, null, '🌍', '투자자', '사업가', '미국'],
  ['gl-oprah-winfrey', '오프라 윈프리', 'Oprah Winfrey', '1954-01-29', null, null, '🌍', '방송인', '사업가', '미국'],
  ['gl-kim-kardashian', '킴 카다시안', 'Kim Kardashian', '1980-10-21', null, null, '🌍', '사업가', '인플루언서', '미국'],
  ['gl-kylie-jenner', '카일리 제너', 'Kylie Jenner', '1997-08-10', null, null, '🌍', '사업가', '인플루언서', '미국'],
  ['gl-larry-page', '래리 페이지', 'Larry Page', '1973-03-26', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-sergey-brin', '세르게이 브린', 'Sergey Brin', '1973-08-21', null, null, '🌍', '사업가', 'CEO', '러시아계미국'],
  ['gl-jack-dorsey', '잭 도시', 'Jack Dorsey', '1976-11-19', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-reid-hoffman', '리드 호프만', 'Reid Hoffman', '1967-08-05', null, null, '🌍', '사업가', '투자자', '미국'],
  ['gl-peter-thiel', '피터 틸', 'Peter Thiel', '1967-10-11', null, null, '🌍', '사업가', '투자자', '독일계미국'],
  ['gl-travis-kalanick', '트래비스 캘러닉', 'Travis Kalanick', '1976-08-06', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-brian-chesky', '브라이언 체스키', 'Brian Chesky', '1981-08-29', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-daniel-ek', '다니엘 에크', 'Daniel Ek', '1983-02-21', null, null, '🌍', '사업가', 'CEO', '스웨덴'],
  ['gl-whitney-wolfe-herd', '휘트니 울프 허드', 'Whitney Wolfe Herd', '1989-07-01', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-evan-spiegel', '에반 슈피겔', 'Evan Spiegel', '1990-06-04', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-lisa-su', '리사 수', 'Lisa Su', '1969-11-07', null, null, '🌍', '사업가', 'CEO', '대만계미국'],
  ['gl-pat-gelsinger', '팻 겔싱어', 'Pat Gelsinger', '1961-06-05', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-andy-jassy', '앤디 재시', 'Andy Jassy', '1968-01-13', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-dario-amodei', '다리오 아모데이', 'Dario Amodei', '1983-01-01', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-demis-hassabis', '데미스 하사비스', 'Demis Hassabis', '1976-07-27', null, null, '🌍', '과학자', 'CEO', '영국'],
  ['gl-susan-wojcicki', '수전 보이치츠키', 'Susan Wojcicki', '1968-07-05', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-sheryl-sandberg', '셰릴 샌드버그', 'Sheryl Sandberg', '1969-08-28', null, null, '🌍', '사업가', 'COO', '미국'],
  ['gl-richard-branson', '리처드 브랜슨', 'Richard Branson', '1950-07-18', null, null, '🌍', '사업가', '미국'],
  ['gl-bob-iger', '밥 아이거', 'Bob Iger', '1951-02-10', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-reed-hastings', '리드 헤이스팅스', 'Reed Hastings', '1960-10-08', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-jamie-dimon', '제이미 다이먼', 'Jamie Dimon', '1956-03-13', null, null, '🌍', '사업가', 'CEO', '미국'],
  ['gl-satoshi-nakamoto', '사토시 나카모토', 'Satoshi Nakamoto', '1975-04-05', null, null, '🌍', '개발자', '비트코인', '일본'],
  ['gl-vitalik-buterin', '비탈릭 부테린', 'Vitalik Buterin', '1994-01-31', null, null, '🌍', '개발자', '이더리움', '러시아계캐나다'],
  ['gl-linus-torvalds', '리누스 토르발스', 'Linus Torvalds', '1969-12-28', null, null, '🌍', '개발자', '리눅스', '핀란드'],
  ['gl-mark-cuban', '마크 큐반', 'Mark Cuban', '1958-07-31', null, null, '🌍', '사업가', '투자자', '미국'],

  // ===== WORLD ATHLETES - FOOTBALL (SOCCER) =====
  ['gl-lionel-messi', '리오넬 메시', 'Lionel Messi', '1987-06-24', null, null, '🌍', '축구선수', '아르헨티나'],
  ['gl-cristiano-ronaldo', '크리스티아누 호날두', 'Cristiano Ronaldo', '1985-02-05', null, null, '🌍', '축구선수', '포르투갈'],
  ['gl-neymar', '네이마르', 'Neymar', '1992-02-05', null, null, '🌍', '축구선수', '브라질'],
  ['gl-kylian-mbappe', '킬리안 음바페', 'Kylian Mbappé', '1998-12-20', null, null, '🌍', '축구선수', '프랑스'],
  ['gl-erling-haaland', '엘링 홀란드', 'Erling Haaland', '2000-07-21', null, null, '🌍', '축구선수', '노르웨이'],
  ['gl-jude-bellingham', '주드 벨링엄', 'Jude Bellingham', '2003-06-29', null, null, '🌍', '축구선수', '영국'],
  ['gl-vinicius-jr', '비니시우스 주니어', 'Vinícius Jr', '2000-07-12', null, null, '🌍', '축구선수', '브라질'],
  ['gl-lamine-yamal', '라민 야말', 'Lamine Yamal', '2007-07-13', null, null, '🌍', '축구선수', '스페인'],
  ['gl-pedri', '페드리', 'Pedri', '2002-11-25', null, null, '🌍', '축구선수', '스페인'],
  ['gl-bukayo-saka', '부카요 사카', 'Bukayo Saka', '2001-09-05', null, null, '🌍', '축구선수', '영국'],
  ['gl-phil-foden', '필 포든', 'Phil Foden', '2000-05-28', null, null, '🌍', '축구선수', '영국'],
  ['gl-mohamed-salah', '모하메드 살라', 'Mohamed Salah', '1992-06-15', null, null, '🌍', '축구선수', '이집트'],
  ['gl-kevin-de-bruyne', '케빈 데 브라위너', 'Kevin De Bruyne', '1991-06-28', null, null, '🌍', '축구선수', '벨기에'],
  ['gl-robert-lewandowski', '로베르트 레반도프스키', 'Robert Lewandowski', '1988-08-21', null, null, '🌍', '축구선수', '폴란드'],
  ['gl-karim-benzema', '카림 벤제마', 'Karim Benzema', '1987-12-19', null, null, '🌍', '축구선수', '프랑스'],
  ['gl-virgil-van-dijk', '버질 반 다이크', 'Virgil van Dijk', '1991-07-08', null, null, '🌍', '축구선수', '네덜란드'],
  ['gl-toni-kroos', '토니 크로스', 'Toni Kroos', '1990-01-04', null, null, '🌍', '축구선수', '독일'],
  ['gl-luka-modric', '루카 모드리치', 'Luka Modrić', '1985-09-09', null, null, '🌍', '축구선수', '크로아티아'],
  ['gl-zlatan-ibrahimovic', '즐라탄 이브라히모비치', 'Zlatan Ibrahimović', '1981-10-03', null, null, '🌍', '축구선수', '스웨덴'],
  ['gl-david-beckham', '데이비드 베컴', 'David Beckham', '1975-05-02', null, null, '🌍', '축구선수', '사업가', '영국'],
  ['gl-zinedine-zidane', '지네딘 지단', 'Zinédine Zidane', '1972-06-23', null, null, '🌍', '축구선수', '감독', '프랑스'],
  ['gl-ronaldinho', '호나우지뉴', 'Ronaldinho', '1980-03-21', null, null, '🌍', '축구선수', '브라질'],
  ['gl-pele', '펠레', 'Pelé', '1940-10-23', null, null, '🌍', '축구선수', '전설', '브라질'],
  ['gl-diego-maradona', '디에고 마라도나', 'Diego Maradona', '1960-10-30', null, null, '🌍', '축구선수', '전설', '아르헨티나'],
  ['gl-thierry-henry', '티에리 앙리', 'Thierry Henry', '1977-08-17', null, null, '🌍', '축구선수', '프랑스'],
  ['gl-wayne-rooney', '웨인 루니', 'Wayne Rooney', '1985-10-24', null, null, '🌍', '축구선수', '영국'],
  ['gl-alex-morgan', '알렉스 모건', 'Alex Morgan', '1989-07-02', null, null, '🌍', '축구선수', '미국'],
  ['gl-megan-rapinoe', '메건 래피노', 'Megan Rapinoe', '1985-07-05', null, null, '🌍', '축구선수', '미국'],

  // ===== BASKETBALL =====
  ['gl-lebron-james', '르브론 제임스', 'LeBron James', '1984-12-30', null, null, '🌍', '농구선수', '미국'],
  ['gl-stephen-curry', '스테판 커리', 'Stephen Curry', '1988-03-14', null, null, '🌍', '농구선수', '미국'],
  ['gl-kevin-durant', '케빈 듀란트', 'Kevin Durant', '1988-09-29', null, null, '🌍', '농구선수', '미국'],
  ['gl-luka-doncic', '루카 돈치치', 'Luka Dončić', '1999-02-28', null, null, '🌍', '농구선수', '슬로베니아'],
  ['gl-giannis', '야니스 아데토쿤보', 'Giannis Antetokounmpo', '1994-12-06', null, null, '🌍', '농구선수', '그리스'],
  ['gl-michael-jordan', '마이클 조던', 'Michael Jordan', '1963-02-17', null, null, '🌍', '농구선수', '전설', '미국'],
  ['gl-kobe-bryant', '코비 브라이언트', 'Kobe Bryant', '1978-08-23', null, null, '🌍', '농구선수', '전설', '미국'],
  ['gl-shaquille-oneal', '샤킬 오닐', 'Shaquille O\'Neal', '1972-03-06', null, null, '🌍', '농구선수', '미국'],
  ['gl-nikola-jokic', '니콜라 요키치', 'Nikola Jokić', '1995-02-19', null, null, '🌍', '농구선수', '세르비아'],
  ['gl-joel-embiid', '조엘 엠비드', 'Joel Embiid', '1994-03-16', null, null, '🌍', '농구선수', '카메룬'],
  ['gl-jayson-tatum', '제이슨 테이텀', 'Jayson Tatum', '1998-03-03', null, null, '🌍', '농구선수', '미국'],
  ['gl-anthony-edwards', '앤서니 에드워즈', 'Anthony Edwards', '2001-08-05', null, null, '🌍', '농구선수', '미국'],
  ['gl-victor-wembanyama', '빅터 웸바냐마', 'Victor Wembanyama', '2004-01-04', null, null, '🌍', '농구선수', '프랑스'],
  ['gl-wilt-chamberlain', '윌트 체임벌린', 'Wilt Chamberlain', '1936-08-21', null, null, '🌍', '농구선수', '전설', '미국'],
  ['gl-magic-johnson', '매직 존슨', 'Magic Johnson', '1959-08-14', null, null, '🌍', '농구선수', '사업가', '미국'],
  ['gl-larry-bird', '래리 버드', 'Larry Bird', '1956-12-07', null, null, '🌍', '농구선수', '전설', '미국'],
  ['gl-tim-duncan', '팀 던컨', 'Tim Duncan', '1976-04-25', null, null, '🌍', '농구선수', '미국'],
  ['gl-dirk-nowitzki', '더크 노비츠키', 'Dirk Nowitzki', '1978-06-19', null, null, '🌍', '농구선수', '독일'],

  // ===== TENNIS =====
  ['gl-serena-williams', '세레나 윌리엄스', 'Serena Williams', '1981-09-26', null, null, '🌍', '테니스선수', '미국'],
  ['gl-naomi-osaka', '오사카 나오미', 'Naomi Osaka', '1997-10-16', null, null, '🌍', '테니스선수', '일본'],
  ['gl-roger-federer', '로저 페더러', 'Roger Federer', '1981-08-08', null, null, '🌍', '테니스선수', '스위스'],
  ['gl-rafael-nadal', '라파엘 나달', 'Rafael Nadal', '1986-06-03', null, null, '🌍', '테니스선수', '스페인'],
  ['gl-novak-djokovic', '노박 조코비치', 'Novak Djokovic', '1987-05-22', null, null, '🌍', '테니스선수', '세르비아'],
  ['gl-carlos-alcaraz', '카를로스 알카라즈', 'Carlos Alcaraz', '2003-05-05', null, null, '🌍', '테니스선수', '스페인'],
  ['gl-jannik-sinner', '야닉 시너', 'Jannik Sinner', '2001-08-16', null, null, '🌍', '테니스선수', '이탈리아'],
  ['gl-coco-gauff', '코코 고프', 'Coco Gauff', '2004-03-13', null, null, '🌍', '테니스선수', '미국'],
  ['gl-iga-swiatek', '이가 시비옹텍', 'Iga Świątek', '2001-05-31', null, null, '🌍', '테니스선수', '폴란드'],
  ['gl-venus-williams', '비너스 윌리엄스', 'Venus Williams', '1980-06-17', null, null, '🌍', '테니스선수', '미국'],

  // ===== GYMNASTICS / TRACK & FIELD =====
  ['gl-simone-biles', '시몬 바일스', 'Simone Biles', '1997-03-14', null, null, '🌍', '체조선수', '미국'],
  ['gl-usain-bolt', '우사인 볼트', 'Usain Bolt', '1986-08-21', null, null, '🌍', '육상선수', '자메이카'],
  ['gl-nadia-comaneci', '나디아 코마네치', 'Nadia Comăneci', '1961-11-12', null, null, '🌍', '체조선수', '루마니아'],

  // ===== F1 / MOTORSPORT =====
  ['gl-lewis-hamilton', '루이스 해밀턴', 'Lewis Hamilton', '1985-01-07', null, null, '🌍', 'F1드라이버', '영국'],
  ['gl-max-verstappen', '막스 페르스타펀', 'Max Verstappen', '1997-09-30', null, null, '🌍', 'F1드라이버', '네덜란드'],
  ['gl-charles-leclerc', '샤를 르클레르', 'Charles Leclerc', '1997-10-16', null, null, '🌍', 'F1드라이버', '모나코'],
  ['gl-lando-norris', '란도 노리스', 'Lando Norris', '1999-11-13', null, null, '🌍', 'F1드라이버', '영국'],
  ['gl-michael-schumacher', '미하엘 슈마허', 'Michael Schumacher', '1969-01-03', null, null, '🌍', 'F1드라이버', '전설', '독일'],
  ['gl-ayrton-senna', '아일톤 세나', 'Ayrton Senna', '1960-03-21', null, null, '🌍', 'F1드라이버', '전설', '브라질'],

  // ===== GOLF =====
  ['gl-tiger-woods', '타이거 우즈', 'Tiger Woods', '1975-12-30', null, null, '🌍', '골프선수', '미국'],
  ['gl-rory-mcilroy', '로리 매킬로이', 'Rory McIlroy', '1989-05-04', null, null, '🌍', '골프선수', '북아일랜드'],
  ['gl-scottie-scheffler', '스코티 쉐플러', 'Scottie Scheffler', '1996-06-21', null, null, '🌍', '골프선수', '미국'],

  // ===== NFL =====
  ['gl-tom-brady', '톰 브래디', 'Tom Brady', '1977-08-03', null, null, '🌍', '미식축구선수', '미국'],
  ['gl-patrick-mahomes', '패트릭 마홈스', 'Patrick Mahomes', '1995-09-17', null, null, '🌍', '미식축구선수', '미국'],
  ['gl-travis-kelce', '트래비스 켈스', 'Travis Kelce', '1989-10-05', null, null, '🌍', '미식축구선수', '미국'],
  ['gl-lamar-jackson', '라마 잭슨', 'Lamar Jackson', '1997-01-07', null, null, '🌍', '미식축구선수', '미국'],
  ['gl-josh-allen', '조시 앨런', 'Josh Allen', '1996-05-21', null, null, '🌍', '미식축구선수', '미국'],

  // ===== BASEBALL =====
  ['gl-shohei-ohtani', '오타니 쇼헤이', 'Shohei Ohtani', '1994-07-05', null, null, '🌍', '야구선수', '일본'],
  ['gl-mike-trout', '마이크 트라웃', 'Mike Trout', '1991-08-07', null, null, '🌍', '야구선수', '미국'],
  ['gl-aaron-judge', '에런 저지', 'Aaron Judge', '1992-04-26', null, null, '🌍', '야구선수', '미국'],
  ['gl-mookie-betts', '무키 베츠', 'Mookie Betts', '1992-10-07', null, null, '🌍', '야구선수', '미국'],
  ['gl-ronald-acuna', '로날드 아쿠냐', 'Ronald Acuña Jr.', '1997-12-18', null, null, '🌍', '야구선수', '베네수엘라'],

  // ===== CRICKET =====
  ['gl-virat-kohli', '비라트 콜리', 'Virat Kohli', '1988-11-05', null, null, '🌍', '크리켓선수', '인도'],
  ['gl-sachin-tendulkar', '사친 텐둘카르', 'Sachin Tendulkar', '1973-04-24', null, null, '🌍', '크리켓선수', '인도'],
  ['gl-ms-dhoni', 'MS 도니', 'MS Dhoni', '1981-07-07', null, null, '🌍', '크리켓선수', '인도'],

  // ===== COMBAT SPORTS =====
  ['gl-muhammad-ali', '무하마드 알리', 'Muhammad Ali', '1942-01-17', null, null, '🌍', '복싱선수', '전설', '미국'],
  ['gl-mike-tyson', '마이크 타이슨', 'Mike Tyson', '1966-06-30', null, null, '🌍', '복싱선수', '미국'],
  ['gl-conor-mcgregor', '코너 맥그리거', 'Conor McGregor', '1988-07-14', null, null, '🌍', 'UFC선수', '아일랜드'],
  ['gl-floyd-mayweather', '플로이드 메이웨더', 'Floyd Mayweather', '1977-02-24', null, null, '🌍', '복싱선수', '미국'],
  ['gl-manny-pacquiao', '매니 파퀴아오', 'Manny Pacquiao', '1978-12-17', null, null, '🌍', '복싱선수', '필리핀'],

  // ===== SWIMMING =====
  ['gl-michael-phelps', '마이클 펠프스', 'Michael Phelps', '1985-06-30', null, null, '🌍', '수영선수', '미국'],
  ['gl-katie-ledecky', '케이티 레데키', 'Katie Ledecky', '1997-03-17', null, null, '🌍', '수영선수', '미국'],

  // ===== FIGURE SKATING =====
  ['gl-yuzuru-hanyu', '하뉴 유즈루', 'Yuzuru Hanyu', '1994-12-07', null, null, '🌍', '피겨스케이터', '일본'],
  ['gl-nathan-chen', '네이선 첸', 'Nathan Chen', '1999-05-05', null, null, '🌍', '피겨스케이터', '미국'],

  // ===== JAPANESE CELEBRITIES =====
  ['gl-naomi-watanabe', '와타나베 나오미', 'Naomi Watanabe', '1987-10-23', null, null, '🌍', '코미디언', '모델', '일본'],
  ['gl-hikaru-utada', '우타다 히카루', 'Hikaru Utada', '1983-01-19', null, null, '🌍', '가수', '싱어송라이터', '일본'],
  ['gl-kenshi-yonezu', '요네즈 켄시', 'Kenshi Yonezu', '1991-03-10', null, null, '🌍', '가수', '싱어송라이터', '일본'],
  ['gl-yoasobi-ikura', '이쿠라', 'ikura', '2000-01-14', null, 'YOASOBI', '🌍', '가수', '일본'],
  ['gl-yoasobi-ayase', '아야세', 'Ayase', '1994-04-04', null, 'YOASOBI', '🌍', '프로듀서', '일본'],
  ['gl-ado', '아도', 'Ado', '2002-10-24', null, null, '🌍', '가수', '일본'],
  ['gl-lisa-jpn', '리사', 'LiSA', '1987-06-24', null, null, '🌍', '가수', '애니송', '일본'],
  ['gl-aimer', '에메', 'Aimer', '1990-07-05', null, null, '🌍', '가수', '일본'],
  ['gl-milet', '밀레', 'milet', '1994-02-16', null, null, '🌍', '가수', '일본'],
  ['gl-fujii-kaze', '후지이 카제', 'Fujii Kaze', '1997-06-14', null, null, '🌍', '가수', '싱어송라이터', '일본'],
  ['gl-imase', '이마세', 'imase', '2000-09-07', null, null, '🌍', '가수', '싱어송라이터', '일본'],
  ['gl-hoshino-gen', '호시노 겐', 'Hoshino Gen', '1981-01-28', null, null, '🌍', '가수', '배우', '일본'],
  ['gl-masahiro-nakai', '나카이 마사히로', 'Masahiro Nakai', '1972-08-18', null, 'SMAP', '🌍', '가수', '방송인', '일본'],
  ['gl-takuya-kimura', '키무라 타쿠야', 'Takuya Kimura', '1972-11-13', null, 'SMAP', '🌍', '배우', '가수', '일본'],
  ['gl-ryuichi-sakamoto', '사카모토 류이치', 'Ryuichi Sakamoto', '1952-01-17', null, null, '🌍', '작곡가', '피아니스트', '일본'],
  ['gl-araki-singer', '아라키', 'Araki', '1995-09-14', null, null, '🌍', '가수', '일본'],
  ['gl-aimyon', '아이묭', 'Aimyon', '1995-03-06', null, null, '🌍', '가수', '싱어송라이터', '일본'],
  ['gl-king-gnu-iguchi', '이구치 사토시', 'Satoshi Iguchi', '1993-10-05', null, 'King Gnu', '🌍', '가수', '일본'],
  ['gl-radwimps-yojiro', '노다 요지로', 'Yojiro Noda', '1985-07-05', null, 'RADWIMPS', '🌍', '가수', '일본'],
  ['gl-joe-hisaishi', '히사이시 조', 'Joe Hisaishi', '1950-12-06', null, null, '🌍', '작곡가', '일본'],
  ['gl-miyazaki-hayao', '미야자키 하야오', 'Hayao Miyazaki', '1941-01-05', null, null, '🌍', '감독', '애니메이터', '일본'],
  ['gl-akira-kurosawa', '구로사와 아키라', 'Akira Kurosawa', '1910-03-23', null, null, '🌍', '감독', '일본'],
  ['gl-yoko-ono', '오노 요코', 'Yoko Ono', '1933-02-18', null, null, '🌍', '예술가', '일본'],
  ['gl-takeshi-kitano', '키타노 다케시', 'Takeshi Kitano', '1947-01-18', null, null, '🌍', '감독', '코미디언', '일본'],
  ['gl-matsumoto-hitoshi', '마츠모토 히토시', 'Hitoshi Matsumoto', '1963-09-08', null, null, '🌍', '코미디언', '일본'],
  ['gl-shingo-katori', '카토리 싱고', 'Shingo Katori', '1977-01-31', null, 'SMAP', '🌍', '가수', '배우', '일본'],
  ['gl-jun-matsumoto', '마츠모토 준', 'Jun Matsumoto', '1983-08-30', null, 'ARASHI', '🌍', '가수', '배우', '일본'],
  ['gl-kazunari-ninomiya', '니노미야 카즈나리', 'Kazunari Ninomiya', '1983-06-17', null, 'ARASHI', '🌍', '가수', '배우', '일본'],
  ['gl-ichiro', '이치로', 'Ichiro Suzuki', '1973-10-22', null, null, '🌍', '야구선수', '전설', '일본'],
  ['gl-naomi-osaka-sports', '오사카 나오미', null, '1997-10-16', null, null, '🌍', '테니스선수', '일본'],
  ['gl-sono-sion', '소노 시온', 'Sion Sono', '1961-12-18', null, null, '🌍', '감독', '일본'],
  ['gl-hideaki-anno', '안노 히데아키', 'Hideaki Anno', '1960-05-22', null, null, '🌍', '감독', '애니메이터', '일본'],

  // ===== ACTORS / ENTERTAINERS (GLOBAL) =====
  ['gl-timothee-chalamet', '티모시 샬라메', 'Timothée Chalamet', '1995-12-27', null, null, '🌍', '배우', '미국'],
  ['gl-zendaya', '젠데이아', 'Zendaya', '1996-09-01', null, null, '🌍', '배우', '가수', '미국'],
  ['gl-tom-holland', '톰 홀랜드', 'Tom Holland', '1996-06-01', null, null, '🌍', '배우', '영국'],
  ['gl-florence-pugh', '플로렌스 퓨', 'Florence Pugh', '1996-01-03', null, null, '🌍', '배우', '영국'],
  ['gl-anya-taylor-joy', '안야 테일러 조이', 'Anya Taylor-Joy', '1996-04-16', null, null, '🌍', '배우', '아르헨티나계미국'],
  ['gl-sydney-sweeney', '시드니 스위니', 'Sydney Sweeney', '1997-09-12', null, null, '🌍', '배우', '미국'],
  ['gl-margot-robbie', '마고 로비', 'Margot Robbie', '1990-07-02', null, null, '🌍', '배우', '호주'],
  ['gl-keanu-reeves', '키아누 리브스', 'Keanu Reeves', '1964-09-02', null, null, '🌍', '배우', '캐나다'],
  ['gl-leonardo-dicaprio', '레오나르도 디카프리오', 'Leonardo DiCaprio', '1974-11-11', null, null, '🌍', '배우', '미국'],
  ['gl-brad-pitt', '브래드 피트', 'Brad Pitt', '1963-12-18', null, null, '🌍', '배우', '미국'],
  ['gl-angelina-jolie', '안젤리나 졸리', 'Angelina Jolie', '1975-06-04', null, null, '🌍', '배우', '미국'],
  ['gl-johnny-depp', '조니 뎁', 'Johnny Depp', '1963-06-09', null, null, '🌍', '배우', '미국'],
  ['gl-robert-downey-jr', '로버트 다우니 주니어', 'Robert Downey Jr.', '1965-04-04', null, null, '🌍', '배우', '미국'],
  ['gl-chris-hemsworth', '크리스 헴스워스', 'Chris Hemsworth', '1983-08-11', null, null, '🌍', '배우', '호주'],
  ['gl-chris-evans', '크리스 에반스', 'Chris Evans', '1981-06-13', null, null, '🌍', '배우', '미국'],
  ['gl-scarlett-johansson', '스칼렛 요한슨', 'Scarlett Johansson', '1984-11-22', null, null, '🌍', '배우', '미국'],
  ['gl-emma-stone', '엠마 스톤', 'Emma Stone', '1988-11-06', null, null, '🌍', '배우', '미국'],
  ['gl-jennifer-lawrence', '제니퍼 로렌스', 'Jennifer Lawrence', '1990-08-15', null, null, '🌍', '배우', '미국'],
  ['gl-natalie-portman', '나탈리 포트만', 'Natalie Portman', '1981-06-09', null, null, '🌍', '배우', '이스라엘계미국'],
  ['gl-emma-watson', '엠마 왓슨', 'Emma Watson', '1990-04-15', null, null, '🌍', '배우', '영국'],
  ['gl-daniel-radcliffe', '대니얼 래드클리프', 'Daniel Radcliffe', '1989-07-23', null, null, '🌍', '배우', '영국'],
  ['gl-ryan-gosling', '라이언 고슬링', 'Ryan Gosling', '1980-11-12', null, null, '🌍', '배우', '캐나다'],
  ['gl-pedro-pascal', '페드로 파스칼', 'Pedro Pascal', '1975-04-02', null, null, '🌍', '배우', '칠레계미국'],
  ['gl-austin-butler', '오스틴 버틀러', 'Austin Butler', '1991-08-17', null, null, '🌍', '배우', '미국'],
  ['gl-barry-keoghan', '배리 키오건', 'Barry Keoghan', '1992-10-18', null, null, '🌍', '배우', '아일랜드'],
  ['gl-jacob-elordi', '제이콥 엘로디', 'Jacob Elordi', '1997-06-26', null, null, '🌍', '배우', '호주'],
  ['gl-jenna-ortega', '젠나 오르테가', 'Jenna Ortega', '2002-09-27', null, null, '🌍', '배우', '미국'],
  ['gl-cillian-murphy', '킬리언 머피', 'Cillian Murphy', '1976-05-25', null, null, '🌍', '배우', '아일랜드'],
  ['gl-denzel-washington', '덴젤 워싱턴', 'Denzel Washington', '1954-12-28', null, null, '🌍', '배우', '미국'],
  ['gl-morgan-freeman', '모건 프리먼', 'Morgan Freeman', '1937-06-01', null, null, '🌍', '배우', '미국'],
  ['gl-meryl-streep', '메릴 스트립', 'Meryl Streep', '1949-06-22', null, null, '🌍', '배우', '미국'],
  ['gl-tom-hanks', '톰 행크스', 'Tom Hanks', '1956-07-09', null, null, '🌍', '배우', '미국'],
  ['gl-will-smith', '윌 스미스', 'Will Smith', '1968-09-25', null, null, '🌍', '배우', '가수', '미국'],
  ['gl-dwayne-johnson', '드웨인 존슨', 'Dwayne Johnson', '1972-05-02', null, null, '🌍', '배우', '프로레슬러', '미국'],

  // ===== DIRECTORS =====
  ['gl-christopher-nolan', '크리스토퍼 놀란', 'Christopher Nolan', '1970-07-30', null, null, '🌍', '감독', '영국'],
  ['gl-steven-spielberg', '스티븐 스필버그', 'Steven Spielberg', '1946-12-18', null, null, '🌍', '감독', '미국'],
  ['gl-quentin-tarantino', '쿠엔틴 타란티노', 'Quentin Tarantino', '1963-03-27', null, null, '🌍', '감독', '미국'],
  ['gl-martin-scorsese', '마틴 스코세이지', 'Martin Scorsese', '1942-11-17', null, null, '🌍', '감독', '미국'],
  ['gl-denis-villeneuve', '드니 빌뇌브', 'Denis Villeneuve', '1967-10-03', null, null, '🌍', '감독', '캐나다'],
  ['gl-greta-gerwig', '그레타 거윅', 'Greta Gerwig', '1983-08-04', null, null, '🌍', '감독', '배우', '미국'],

  // ===== INFLUENCERS / YOUTUBERS =====
  ['gl-mrbeast', '미스터비스트', 'MrBeast', '1998-05-07', null, null, '🌍', '유튜버', '사업가', '미국'],
  ['gl-pewdiepie', '퓨디파이', 'PewDiePie', '1989-10-24', null, null, '🌍', '유튜버', '스웨덴'],
  ['gl-emma-chamberlain', '엠마 챔벌레인', 'Emma Chamberlain', '2001-05-22', null, null, '🌍', '유튜버', '인플루언서', '미국'],
  ['gl-markiplier', '마크플라이어', 'Markiplier', '1989-06-28', null, null, '🌍', '유튜버', '미국'],
  ['gl-pokimane', '포키마네', 'Pokimane', '1996-05-14', null, null, '🌍', '스트리머', '모로코계캐나다'],
  ['gl-khaby-lame', '카비 라메', 'Khaby Lame', '2000-03-09', null, null, '🌍', '틱톡커', '세네갈계이탈리아'],
  ['gl-addison-rae', '애디슨 래', 'Addison Rae', '2000-10-06', null, null, '🌍', '틱톡커', '미국'],

  // ===== POLITICAL / WORLD LEADERS =====
  ['gl-barack-obama', '버락 오바마', 'Barack Obama', '1961-08-04', null, null, '🌍', '정치인', '전 대통령', '미국'],
  ['gl-donald-trump', '도널드 트럼프', 'Donald Trump', '1946-06-14', null, null, '🌍', '정치인', '대통령', '미국'],
  ['gl-joe-biden', '조 바이든', 'Joe Biden', '1942-11-20', null, null, '🌍', '정치인', '전 대통령', '미국'],
  ['gl-kamala-harris', '카말라 해리스', 'Kamala Harris', '1964-10-20', null, null, '🌍', '정치인', '부통령', '미국'],
  ['gl-queen-elizabeth-ii', '엘리자베스 2세', 'Queen Elizabeth II', '1926-04-21', null, null, '🌍', '왕족', '영국'],
  ['gl-king-charles-iii', '찰스 3세', 'King Charles III', '1948-11-14', null, null, '🌍', '왕족', '영국'],
  ['gl-princess-diana', '다이애나 왕세자비', 'Princess Diana', '1961-07-01', null, null, '🌍', '왕족', '영국'],
  ['gl-prince-william', '윌리엄 왕세자', 'Prince William', '1982-06-21', null, null, '🌍', '왕족', '영국'],
  ['gl-prince-harry', '해리 왕자', 'Prince Harry', '1984-09-15', null, null, '🌍', '왕족', '영국'],
  ['gl-volodymyr-zelenskyy', '볼로디미르 젤렌스키', 'Volodymyr Zelenskyy', '1978-01-25', null, null, '🌍', '정치인', '대통령', '우크라이나'],
  ['gl-xi-jinping', '시진핑', 'Xi Jinping', '1953-06-15', null, null, '🌍', '정치인', '주석', '중국'],
  ['gl-narendra-modi', '나렌드라 모디', 'Narendra Modi', '1950-09-17', null, null, '🌍', '정치인', '총리', '인도'],
  ['gl-pope-francis', '프란치스코 교황', 'Pope Francis', '1936-12-17', null, null, '🌍', '종교지도자', '아르헨티나'],

  // ===== SCIENTISTS / THINKERS =====
  ['gl-stephen-hawking', '스티븐 호킹', 'Stephen Hawking', '1942-01-08', null, null, '🌍', '물리학자', '영국'],
  ['gl-neil-degrasse-tyson', '닐 디그래스 타이슨', 'Neil deGrasse Tyson', '1958-10-05', null, null, '🌍', '천체물리학자', '미국'],
  ['gl-jane-goodall', '제인 구달', 'Jane Goodall', '1934-04-03', null, null, '🌍', '동물학자', '영국'],
  ['gl-malala-yousafzai', '말랄라 유사프자이', 'Malala Yousafzai', '1997-07-12', null, null, '🌍', '활동가', '노벨상수상자', '파키스탄'],
  ['gl-greta-thunberg', '그레타 툰베리', 'Greta Thunberg', '2003-01-03', null, null, '🌍', '환경활동가', '스웨덴'],
  ['gl-yuval-noah-harari', '유발 하라리', 'Yuval Noah Harari', '1976-02-24', null, null, '🌍', '역사학자', '작가', '이스라엘'],
  ['gl-jordan-peterson', '조던 피터슨', 'Jordan Peterson', '1962-06-12', null, null, '🌍', '심리학자', '작가', '캐나다'],
  ['gl-elon-musk-sci', null, null, '1971-06-28', null, null, '🌍', '사업가', 'CEO', '남아프리카'],

  // ===== FASHION / MODELS =====
  ['gl-gigi-hadid', '지지 하디드', 'Gigi Hadid', '1995-04-23', null, null, '🌍', '모델', '미국'],
  ['gl-bella-hadid', '벨라 하디드', 'Bella Hadid', '1996-10-09', null, null, '🌍', '모델', '미국'],
  ['gl-kendall-jenner', '켄달 제너', 'Kendall Jenner', '1995-11-03', null, null, '🌍', '모델', '미국'],
  ['gl-hailey-bieber', '헤일리 비버', 'Hailey Bieber', '1996-11-22', null, null, '🌍', '모델', '미국'],
  ['gl-naomi-campbell', '나오미 캠벨', 'Naomi Campbell', '1970-05-22', null, null, '🌍', '모델', '영국'],
  ['gl-cara-delevingne', '카라 델레바인', 'Cara Delevingne', '1992-08-12', null, null, '🌍', '모델', '배우', '영국'],

  // ===== PRODUCERS & COMPOSERS =====
  ['gl-glass-animals', '데이브 베일리', 'Dave Bayley', '1988-09-04', null, 'Glass Animals', '🌍', '가수', '영국'],
  ['gl-jack-antonoff', '잭 안토노프', 'Jack Antonoff', '1984-03-31', null, 'Bleachers', '🌍', '프로듀서', '싱어송라이터', '미국'],
  ['gl-finneas', '피네아스', 'Finneas', '1997-07-30', null, null, '🌍', '프로듀서', '싱어송라이터', '미국'],
  ['gl-mark-ronson', '마크 론슨', 'Mark Ronson', '1975-09-04', null, null, '🌍', '프로듀서', 'DJ', '영국'],
  ['gl-max-martin', '맥스 마틴', 'Max Martin', '1971-02-26', null, null, '🌍', '프로듀서', '작곡가', '스웨덴'],
  ['gl-rick-rubin', '릭 루빈', 'Rick Rubin', '1963-03-10', null, null, '🌍', '프로듀서', '미국'],
  ['gl-quincy-jones', '퀸시 존스', 'Quincy Jones', '1933-03-14', null, null, '🌍', '프로듀서', '작곡가', '미국'],
  ['gl-hans-zimmer', '한스 짐머', 'Hans Zimmer', '1957-09-12', null, null, '🌍', '작곡가', '영화음악', '독일'],
  ['gl-john-williams', '존 윌리엄스', 'John Williams', '1932-02-08', null, null, '🌍', '작곡가', '영화음악', '미국'],
  ['gl-ennio-morricone', '엔니오 모리코네', 'Ennio Morricone', '1928-11-10', null, null, '🌍', '작곡가', '영화음악', '이탈리아'],
  ['gl-yo-yo-ma', '요요 마', 'Yo-Yo Ma', '1955-10-07', null, null, '🌍', '첼리스트', '프랑스계미국'],
  ['gl-lang-lang', '랑랑', 'Lang Lang', '1982-06-14', null, null, '🌍', '피아니스트', '중국'],
  ['gl-andre-rieu', '앙드레 류', 'André Rieu', '1949-10-01', null, null, '🌍', '바이올리니스트', '네덜란드'],
  ['gl-yuja-wang', '왕위자', 'Yuja Wang', '1987-02-10', null, null, '🌍', '피아니스트', '중국'],

  // ===== KOREAN GLOBAL ATHLETES =====
  ['gl-son-heungmin', '손흥민', 'Son Heung-min', '1992-07-08', null, null, '🌍', '축구선수', '한국'],
  ['gl-kim-yuna', '김연아', 'Kim Yuna', '1990-09-05', null, null, '🌍', '피겨스케이터', '한국'],
  ['gl-ryu-hyunjin', '류현진', 'Ryu Hyun-jin', '1987-03-25', null, null, '🌍', '야구선수', '한국'],
  ['gl-park-jisung', '박지성', 'Park Ji-sung', '1981-02-25', null, null, '🌍', '축구선수', '한국'],
  ['gl-cha-bumkun', '차범근', 'Cha Bum-kun', '1953-05-22', null, null, '🌍', '축구선수', '전설', '한국'],
  ['gl-an-sehyoung', '안세영', 'An Se-young', '2001-02-17', null, null, '🌍', '배드민턴선수', '한국'],
  ['gl-chloe-kim', '클로이 김', 'Chloe Kim', '2000-04-23', null, null, '🌍', '스노보더', '한국계미국'],
  ['gl-hwang-hee-chan', '황희찬', 'Hwang Hee-chan', '1996-01-26', null, null, '🌍', '축구선수', '한국'],
  ['gl-lee-kang-in', '이강인', 'Lee Kang-in', '2001-02-19', null, null, '🌍', '축구선수', '한국'],
  ['gl-kim-minjae', '김민재', 'Kim Min-jae', '1996-11-15', null, null, '🌍', '축구선수', '한국'],
  ['gl-cho-gue-sung', '조규성', 'Cho Gue-sung', '1998-01-25', null, null, '🌍', '축구선수', '한국'],
  ['gl-park-seri', '박세리', 'Pak Se-ri', '1977-09-28', null, null, '🌍', '골프선수', '한국'],
  ['gl-ko-jin-young', '고진영', 'Ko Jin-young', '1995-07-07', null, null, '🌍', '골프선수', '한국'],
  ['gl-choi-hyungjoo', '최경주', 'K.J. Choi', '1970-05-19', null, null, '🌍', '골프선수', '한국'],
  ['gl-kim-seyoung', '김세영', 'Kim Sei-young', '1993-01-21', null, null, '🌍', '골프선수', '한국'],
  ['gl-lee-daehoon', '이대훈', 'Lee Dae-hoon', '1992-02-13', null, null, '🌍', '태권도선수', '한국'],
  ['gl-park-taehwan', '박태환', 'Park Tae-hwan', '1989-09-27', null, null, '🌍', '수영선수', '한국'],

  // ===== AFRICAN ARTISTS =====
  ['gl-burna-boy', '버나 보이', 'Burna Boy', '1991-07-02', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-wizkid', '위즈키드', 'Wizkid', '1990-07-16', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-davido', '다비도', 'Davido', '1992-11-21', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-rema', '레마', 'Rema', '2000-05-01', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-tems', '템스', 'Tems', '1995-06-11', null, null, '🌍', '가수', 'R&B', '나이지리아'],
  ['gl-asake', '아사케', 'Asake', '1999-01-13', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-ayra-starr', '아이라 스타', 'Ayra Starr', '2002-06-14', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-ckay', 'CKay', 'CKay', '1995-07-16', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],
  ['gl-tiwa-savage', '티와 새비지', 'Tiwa Savage', '1980-02-05', null, null, '🌍', '가수', '아프로비츠', '나이지리아'],

  // ===== UK RAP & GRIME =====
  ['gl-central-cee', '센트럴 씨', 'Central Cee', '1998-06-04', null, null, '🌍', '래퍼', '영국'],
  ['gl-stormzy', '스톰지', 'Stormzy', '1993-07-26', null, null, '🌍', '래퍼', '영국'],
  ['gl-dave-uk', '데이브', 'Dave', '1998-06-05', null, null, '🌍', '래퍼', '영국'],
  ['gl-skepta', '스켑타', 'Skepta', '1982-09-19', null, null, '🌍', '래퍼', '영국'],
  ['gl-aitch', '에이치', 'Aitch', '2000-12-09', null, null, '🌍', '래퍼', '영국'],
  ['gl-little-simz', '리틀 심즈', 'Little Simz', '1994-02-16', null, null, '🌍', '래퍼', '영국'],
  ['gl-slowthai', '슬로타이', 'slowthai', '1994-12-18', null, null, '🌍', '래퍼', '영국'],

  // ===== EUROPEAN ARTISTS =====
  ['gl-stromae', '스트로마에', 'Stromae', '1985-03-12', null, null, '🌍', '가수', '벨기에'],
  ['gl-angele', '앙젤', 'Angèle', '1995-12-03', null, null, '🌍', '가수', '벨기에'],
  ['gl-aya-nakamura', '아야 나카무라', 'Aya Nakamura', '1995-05-10', null, null, '🌍', '가수', '프랑스'],
  ['gl-zara-larsson', '자라 라슨', 'Zara Larsson', '1997-12-16', null, null, '🌍', '가수', '스웨덴'],
  ['gl-robyn', '로빈', 'Robyn', '1979-06-12', null, null, '🌍', '가수', '스웨덴'],
  ['gl-sigrid', '시그리드', 'Sigrid', '1996-09-05', null, null, '🌍', '가수', '노르웨이'],
  ['gl-tove-lo', '토브 로', 'Tove Lo', '1987-10-29', null, null, '🌍', '가수', '스웨덴'],
  ['gl-loreen', '로렌', 'Loreen', '1983-10-16', null, null, '🌍', '가수', '스웨덴'],
  ['gl-mahmood', '마무드', 'Mahmood', '1992-09-12', null, null, '🌍', '가수', '이탈리아'],
  ['gl-maneskin-damiano', '다미아노 다비드', 'Damiano David', '1999-01-08', null, 'Maneskin', '🌍', '가수', '이탈리아'],
  ['gl-elodie', '엘로디', 'Elodie', '1990-05-03', null, null, '🌍', '가수', '이탈리아'],

  // ===== INDIAN ARTISTS =====
  ['gl-diljit-dosanjh', '딜짓 도산', 'Diljit Dosanjh', '1984-01-06', null, null, '🌍', '가수', '배우', '인도'],
  ['gl-ap-dhillon', 'AP 딜론', 'AP Dhillon', '1999-12-02', null, null, '🌍', '가수', '인도계캐나다'],
  ['gl-arijit-singh', '아리짓 싱', 'Arijit Singh', '1987-04-25', null, null, '🌍', '가수', '인도'],
  ['gl-shreya-ghoshal', '슈레야 고샬', 'Shreya Ghoshal', '1984-03-12', null, null, '🌍', '가수', '인도'],
  ['gl-neha-kakkar', '네하 카카르', 'Neha Kakkar', '1988-06-06', null, null, '🌍', '가수', '인도'],
  ['gl-badshah', '배드샤', 'Badshah', '1985-11-19', null, null, '🌍', '래퍼', '인도'],
  ['gl-ar-rahman', 'A.R. 라만', 'A.R. Rahman', '1967-01-06', null, null, '🌍', '작곡가', '인도'],
  ['gl-priyanka-chopra', '프리양카 초프라', 'Priyanka Chopra', '1982-07-18', null, null, '🌍', '배우', '가수', '인도'],
  ['gl-deepika-padukone', '디피카 파두코네', 'Deepika Padukone', '1986-01-05', null, null, '🌍', '배우', '인도'],
  ['gl-shah-rukh-khan', '샤루크 칸', 'Shah Rukh Khan', '1965-11-02', null, null, '🌍', '배우', '인도'],

  // ===== COMEDIANS / TV PERSONALITIES =====
  ['gl-trevor-noah', '트레버 노아', 'Trevor Noah', '1984-02-20', null, null, '🌍', '코미디언', '방송인', '남아프리카'],
  ['gl-john-oliver', '존 올리버', 'John Oliver', '1977-04-23', null, null, '🌍', '코미디언', '방송인', '영국'],
  ['gl-jimmy-fallon', '지미 팰런', 'Jimmy Fallon', '1974-09-19', null, null, '🌍', '코미디언', '방송인', '미국'],
  ['gl-conan-obrien', '코난 오브라이언', 'Conan O\'Brien', '1963-04-18', null, null, '🌍', '코미디언', '방송인', '미국'],
  ['gl-kevin-hart', '케빈 하트', 'Kevin Hart', '1979-07-06', null, null, '🌍', '코미디언', '배우', '미국'],
  ['gl-dave-chappelle', '데이브 샤펠', 'Dave Chappelle', '1973-08-24', null, null, '🌍', '코미디언', '미국'],
  ['gl-chris-rock', '크리스 록', 'Chris Rock', '1965-02-07', null, null, '🌍', '코미디언', '배우', '미국'],
  ['gl-ali-wong', '알리 웡', 'Ali Wong', '1982-04-19', null, null, '🌍', '코미디언', '배우', '미국'],
  ['gl-hasan-minhaj', '하산 민하지', 'Hasan Minhaj', '1985-09-23', null, null, '🌍', '코미디언', '방송인', '미국'],
  ['gl-bo-burnham', '보 번햄', 'Bo Burnham', '1990-08-21', null, null, '🌍', '코미디언', '감독', '미국'],

  // ===== WRITERS / AUTHORS =====
  ['gl-jk-rowling', 'J.K. 롤링', 'J.K. Rowling', '1965-07-31', null, null, '🌍', '작가', '영국'],
  ['gl-stephen-king', '스티븐 킹', 'Stephen King', '1947-09-21', null, null, '🌍', '작가', '미국'],
  ['gl-haruki-murakami', '무라카미 하루키', 'Haruki Murakami', '1949-01-12', null, null, '🌍', '작가', '일본'],
  ['gl-george-rr-martin', '조지 R.R. 마틴', 'George R.R. Martin', '1948-09-20', null, null, '🌍', '작가', '미국'],
  ['gl-colleen-hoover', '콜린 후버', 'Colleen Hoover', '1979-12-11', null, null, '🌍', '작가', '미국'],
  ['gl-sally-rooney', '샐리 루니', 'Sally Rooney', '1991-02-20', null, null, '🌍', '작가', '아일랜드'],

  // ===== MORE K-POP GLOBAL =====
  ['gl-stray-kids-bang-chan', '방찬', 'Bang Chan', '1997-10-03', null, 'Stray Kids', '🌍', '가수', '아이돌', '호주'],
  ['gl-stray-kids-hyunjin', '현진', 'Hyunjin', '2000-03-20', null, 'Stray Kids', '🌍', '가수', '댄서', '한국'],
  ['gl-stray-kids-felix', '필릭스', 'Felix', '2000-09-15', null, 'Stray Kids', '🌍', '가수', '댄서', '호주'],
  ['gl-ateez-hongjoong', '홍중', 'Hongjoong', '1998-11-07', null, 'ATEEZ', '🌍', '가수', '아이돌', '한국'],
  ['gl-ateez-san', '산', 'San', '1999-07-10', null, 'ATEEZ', '🌍', '가수', '댄서', '한국'],
  ['gl-enhypen-heeseung', '희승', 'Heeseung', '2001-10-15', null, 'ENHYPEN', '🌍', '가수', '아이돌', '한국'],
  ['gl-enhypen-ni-ki', '니키', 'Ni-ki', '2005-12-09', null, 'ENHYPEN', '🌍', '가수', '댄서', '일본'],
  ['gl-txt-soobin', '수빈', 'Soobin', '2000-12-05', null, 'TXT', '🌍', '가수', '아이돌', '한국'],
  ['gl-txt-yeonjun', '연준', 'Yeonjun', '1999-09-13', null, 'TXT', '🌍', '가수', '댄서', '한국'],
  ['gl-twice-nayeon', '나연', 'Nayeon', '1995-09-22', null, 'TWICE', '🌍', '가수', '아이돌', '한국'],
  ['gl-twice-momo', '모모', 'Momo', '1996-11-09', null, 'TWICE', '🌍', '가수', '댄서', '일본'],
  ['gl-twice-sana', '사나', 'Sana', '1996-12-29', null, 'TWICE', '🌍', '가수', '아이돌', '일본'],
  ['gl-twice-tzuyu', '쯔위', 'Tzuyu', '1999-06-14', null, 'TWICE', '🌍', '가수', '아이돌', '대만'],
  ['gl-aespa-karina', '카리나', 'Karina', '2000-04-11', null, 'aespa', '🌍', '가수', '아이돌', '한국'],
  ['gl-aespa-winter', '윈터', 'Winter', '2001-01-01', null, 'aespa', '🌍', '가수', '아이돌', '한국'],
  ['gl-le-sserafim-sakura', '사쿠라', 'Sakura', '1998-03-19', null, 'LE SSERAFIM', '🌍', '가수', '아이돌', '일본'],
  ['gl-le-sserafim-chaewon', '채원', 'Chaewon', '2000-08-01', null, 'LE SSERAFIM', '🌍', '가수', '아이돌', '한국'],
  ['gl-newjeans-minji', '민지', 'Minji', '2004-05-07', null, 'NewJeans', '🌍', '가수', '아이돌', '한국'],
  ['gl-newjeans-hanni', '하니', 'Hanni', '2004-10-06', null, 'NewJeans', '🌍', '가수', '아이돌', '호주'],
  ['gl-newjeans-danielle', '다니엘', 'Danielle', '2005-04-11', null, 'NewJeans', '🌍', '가수', '아이돌', '호주'],
  ['gl-newjeans-haerin', '해린', 'Haerin', '2006-05-15', null, 'NewJeans', '🌍', '가수', '아이돌', '한국'],
  ['gl-newjeans-hyein', '혜인', 'Hyein', '2008-04-21', null, 'NewJeans', '🌍', '가수', '아이돌', '한국'],
  ['gl-ive-wonyoung', '원영', 'Wonyoung', '2004-08-31', null, 'IVE', '🌍', '가수', '아이돌', '한국'],
  ['gl-ive-yujin', '유진', 'Yujin', '2003-09-01', null, 'IVE', '🌍', '가수', '아이돌', '한국'],
  ['gl-seventeen-scoups', '에스쿱스', 'S.Coups', '1995-08-08', null, 'SEVENTEEN', '🌍', '가수', '래퍼', '한국'],
  ['gl-seventeen-vernon', '버논', 'Vernon', '1998-02-18', null, 'SEVENTEEN', '🌍', '가수', '래퍼', '한국'],
  ['gl-nct-taeyong', '태용', 'Taeyong', '1995-07-01', null, 'NCT', '🌍', '가수', '댄서', '한국'],
  ['gl-nct-mark', '마크', 'Mark', '1999-08-02', null, 'NCT', '🌍', '가수', '래퍼', '캐나다'],
  ['gl-exo-baekhyun', '백현', 'Baekhyun', '1992-05-06', null, 'EXO', '🌍', '가수', '아이돌', '한국'],
  ['gl-exo-kai', '카이', 'Kai', '1994-01-14', null, 'EXO', '🌍', '가수', '댄서', '한국'],
  ['gl-itzy-ryujin', '류진', 'Ryujin', '2001-04-17', null, 'ITZY', '🌍', '가수', '댄서', '한국'],
  ['gl-gidle-miyeon', '미연', 'Miyeon', '1997-01-31', null, '(G)I-DLE', '🌍', '가수', '아이돌', '한국'],
  ['gl-gidle-soyeon', '소연', 'Soyeon', '1998-08-26', null, '(G)I-DLE', '🌍', '가수', '래퍼', '한국'],
  ['gl-mamamoo-hwasa', '화사', 'Hwasa', '1995-07-23', null, 'MAMAMOO', '🌍', '가수', '아이돌', '한국'],
  ['gl-red-velvet-irene', '아이린', 'Irene', '1991-03-29', null, 'Red Velvet', '🌍', '가수', '아이돌', '한국'],
  ['gl-sunmi', '선미', 'Sunmi', '1992-05-02', null, null, '🌍', '가수', '아이돌', '한국'],
  ['gl-chungha', '청하', 'Chungha', '1996-02-09', null, null, '🌍', '가수', '댄서', '한국'],
  ['gl-jay-park', '박재범', 'Jay Park', '1987-04-25', null, null, '🌍', '가수', '래퍼', '한국계미국'],
  ['gl-zico', '지코', 'Zico', '1992-09-14', null, null, '🌍', '래퍼', '프로듀서', '한국'],
  ['gl-dean', '딘', 'Dean', '1992-11-10', null, null, '🌍', '가수', 'R&B', '한국'],
  ['gl-crush', '크러쉬', 'Crush', '1992-05-03', null, null, '🌍', '가수', 'R&B', '한국'],
  ['gl-heize', '헤이즈', 'Heize', '1991-08-09', null, null, '🌍', '가수', '래퍼', '한국'],
  ['gl-babymonster-ruka', '루카', 'Ruka', '2002-03-20', null, 'BABYMONSTER', '🌍', '가수', '댄서', '일본'],
  ['gl-illit-wonhee', '원희', 'Wonhee', '2007-09-28', null, 'ILLIT', '🌍', '가수', '아이돌', '한국'],
  ['gl-g-dragon', '지드래곤', 'G-Dragon', '1988-08-18', null, 'BIGBANG', '🌍', '가수', '래퍼', '한국'],
  ['gl-taeyang', '태양', 'Taeyang', '1988-05-18', null, 'BIGBANG', '🌍', '가수', '댄서', '한국'],

  // ===== MORE ACTORS/ENTERTAINERS =====
  ['gl-ana-de-armas', '아나 데 아르마스', 'Ana de Armas', '1988-04-30', null, null, '🌍', '배우', '쿠바계미국'],
  ['gl-elizabeth-olsen', '엘리자베스 올슨', 'Elizabeth Olsen', '1989-02-16', null, null, '🌍', '배우', '미국'],
  ['gl-tom-cruise', '톰 크루즈', 'Tom Cruise', '1962-07-03', null, null, '🌍', '배우', '미국'],
  ['gl-matt-damon', '맷 데이먼', 'Matt Damon', '1970-10-08', null, null, '🌍', '배우', '미국'],
  ['gl-ben-affleck', '벤 애플렉', 'Ben Affleck', '1972-08-15', null, null, '🌍', '배우', '감독', '미국'],
  ['gl-christian-bale', '크리스찬 베일', 'Christian Bale', '1974-01-30', null, null, '🌍', '배우', '영국'],
  ['gl-benedict-cumberbatch', '베네딕트 컴버배치', 'Benedict Cumberbatch', '1976-07-19', null, null, '🌍', '배우', '영국'],
  ['gl-henry-cavill', '헨리 카빌', 'Henry Cavill', '1983-05-05', null, null, '🌍', '배우', '영국'],
  ['gl-jason-momoa', '제이슨 모모아', 'Jason Momoa', '1979-08-01', null, null, '🌍', '배우', '미국'],
  ['gl-idris-elba', '이드리스 엘바', 'Idris Elba', '1972-09-06', null, null, '🌍', '배우', '영국'],
  ['gl-viola-davis', '비올라 데이비스', 'Viola Davis', '1965-08-11', null, null, '🌍', '배우', '미국'],
  ['gl-lupita-nyongo', '루피타 뇽오', 'Lupita Nyong\'o', '1983-03-01', null, null, '🌍', '배우', '케냐계멕시코'],
  ['gl-cate-blanchett', '케이트 블란쳇', 'Cate Blanchett', '1969-05-14', null, null, '🌍', '배우', '호주'],
  ['gl-nicole-kidman', '니콜 키드먼', 'Nicole Kidman', '1967-06-20', null, null, '🌍', '배우', '호주'],
  ['gl-sandra-bullock', '산드라 블록', 'Sandra Bullock', '1964-07-26', null, null, '🌍', '배우', '미국'],
  ['gl-anne-hathaway', '앤 해서웨이', 'Anne Hathaway', '1982-11-12', null, null, '🌍', '배우', '미국'],
  ['gl-gal-gadot', '갈 가돗', 'Gal Gadot', '1985-04-30', null, null, '🌍', '배우', '이스라엘'],
  ['gl-oscar-isaac', '오스카 아이작', 'Oscar Isaac', '1979-03-09', null, null, '🌍', '배우', '과테말라계미국'],
  ['gl-paul-mescal', '폴 메스칼', 'Paul Mescal', '1996-02-02', null, null, '🌍', '배우', '아일랜드'],
  ['gl-glen-powell', '글렌 파월', 'Glen Powell', '1988-10-21', null, null, '🌍', '배우', '미국'],
  ['gl-rachel-zegler', '레이첼 제글러', 'Rachel Zegler', '2001-05-03', null, null, '🌍', '배우', '가수', '미국'],
  ['gl-hailee-steinfeld', '헤일리 스타인펠드', 'Hailee Steinfeld', '1996-12-11', null, null, '🌍', '배우', '가수', '미국'],

  // ===== MORE DIRECTORS =====
  ['gl-bong-joonho', '봉준호', 'Bong Joon-ho', '1969-09-14', null, null, '🌍', '감독', '한국'],
  ['gl-park-chanwook', '박찬욱', 'Park Chan-wook', '1963-08-23', null, null, '🌍', '감독', '한국'],
  ['gl-wes-anderson', '웨스 앤더슨', 'Wes Anderson', '1969-05-01', null, null, '🌍', '감독', '미국'],
  ['gl-jordan-peele', '조던 필', 'Jordan Peele', '1979-02-21', null, null, '🌍', '감독', '미국'],
  ['gl-taika-waititi', '타이카 와이티티', 'Taika Waititi', '1975-08-16', null, null, '🌍', '감독', '배우', '뉴질랜드'],
  ['gl-guillermo-del-toro', '기예르모 델 토로', 'Guillermo del Toro', '1964-10-09', null, null, '🌍', '감독', '멕시코'],
  ['gl-ridley-scott', '리들리 스콧', 'Ridley Scott', '1937-11-30', null, null, '🌍', '감독', '영국'],
  ['gl-james-cameron', '제임스 카메론', 'James Cameron', '1954-08-16', null, null, '🌍', '감독', '캐나다'],

  // ===== MORE YOUTUBERS / STREAMERS =====
  ['gl-mrbeast', '미스터비스트', 'MrBeast', '1998-05-07', null, null, '🌍', '유튜버', '사업가', '미국'],
  ['gl-pewdiepie', '퓨디파이', 'PewDiePie', '1989-10-24', null, null, '🌍', '유튜버', '스웨덴'],
  ['gl-emma-chamberlain', '엠마 챔벌레인', 'Emma Chamberlain', '2001-05-22', null, null, '🌍', '유튜버', '인플루언서', '미국'],
  ['gl-markiplier', '마크플라이어', 'Markiplier', '1989-06-28', null, null, '🌍', '유튜버', '미국'],
  ['gl-pokimane', '포키마네', 'Pokimane', '1996-05-14', null, null, '🌍', '스트리머', '모로코계캐나다'],
  ['gl-khaby-lame', '카비 라메', 'Khaby Lame', '2000-03-09', null, null, '🌍', '틱톡커', '세네갈계이탈리아'],
  ['gl-addison-rae', '애디슨 래', 'Addison Rae', '2000-10-06', null, null, '🌍', '틱톡커', '미국'],
  ['gl-jacksepticeye', '잭셉틱아이', 'Jacksepticeye', '1990-02-07', null, null, '🌍', '유튜버', '아일랜드'],
  ['gl-dream', '드림', 'Dream', '1999-08-12', null, null, '🌍', '유튜버', '미국'],
  ['gl-ninja', '닌자', 'Ninja', '1991-06-05', null, null, '🌍', '스트리머', '미국'],
  ['gl-kai-cenat', '카이 세나', 'Kai Cenat', '2001-12-16', null, null, '🌍', '스트리머', '미국'],
  ['gl-ixine', '이지네', 'IShowSpeed', '2005-01-21', null, null, '🌍', '유튜버', '스트리머', '미국'],

  // ===== MORE RAPPERS =====
  ['gl-nba-youngboy', 'NBA 영보이', 'NBA YoungBoy', '1999-10-20', null, null, '🌍', '래퍼', '미국'],
  ['gl-lil-uzi-vert', '릴 우지 버트', 'Lil Uzi Vert', '1995-07-31', null, null, '🌍', '래퍼', '미국'],
  ['gl-lil-durk', '릴 더크', 'Lil Durk', '1992-10-19', null, null, '🌍', '래퍼', '미국'],
  ['gl-young-thug', '영 떡', 'Young Thug', '1991-08-16', null, null, '🌍', '래퍼', '미국'],
  ['gl-dababy', '다베이비', 'DaBaby', '1991-12-22', null, null, '🌍', '래퍼', '미국'],
  ['gl-polo-g', '폴로 지', 'Polo G', '1999-01-06', null, null, '🌍', '래퍼', '미국'],
  ['gl-pop-smoke', '팝 스모크', 'Pop Smoke', '1999-07-20', null, null, '🌍', '래퍼', '미국'],
  ['gl-yeat', '이트', 'Yeat', '2000-02-26', null, null, '🌍', '래퍼', '미국'],
  ['gl-ken-carson', '켄 카슨', 'Ken Carson', '2000-04-11', null, null, '🌍', '래퍼', '미국'],
  ['gl-glorilla', '글로릴라', 'GloRilla', '1999-07-28', null, null, '🌍', '래퍼', '미국'],
  ['gl-sexyy-red', '섹시 레드', 'Sexyy Red', '1998-04-15', null, null, '🌍', '래퍼', '미국'],

  // ===== MORE ADDITIONAL ATHLETES =====
  ['gl-alexander-zverev', '알렉산더 즈베레프', 'Alexander Zverev', '1997-04-20', null, null, '🌍', '테니스선수', '독일'],
  ['gl-daniil-medvedev', '다닐 메드베데프', 'Daniil Medvedev', '1996-02-11', null, null, '🌍', '테니스선수', '러시아'],
  ['gl-aryna-sabalenka', '아리나 사발렌카', 'Aryna Sabalenka', '1998-05-05', null, null, '🌍', '테니스선수', '벨라루스'],
  ['gl-florian-wirtz', '플로리안 비르츠', 'Florian Wirtz', '2003-05-03', null, null, '🌍', '축구선수', '독일'],
  ['gl-jamal-musiala', '자말 무시알라', 'Jamal Musiala', '2003-02-26', null, null, '🌍', '축구선수', '독일'],
  ['gl-declan-rice', '데클란 라이스', 'Declan Rice', '1999-01-14', null, null, '🌍', '축구선수', '영국'],
  ['gl-bruno-fernandes', '브루누 페르난데스', 'Bruno Fernandes', '1994-09-08', null, null, '🌍', '축구선수', '포르투갈'],
  ['gl-harry-kane', '해리 케인', 'Harry Kane', '1993-07-28', null, null, '🌍', '축구선수', '영국'],
  ['gl-sadio-mane', '사디오 마네', 'Sadio Mané', '1992-04-10', null, null, '🌍', '축구선수', '세네갈'],
  ['gl-thibaut-courtois', '티보 쿠르투아', 'Thibaut Courtois', '1992-05-11', null, null, '🌍', '축구선수', '벨기에'],
  ['gl-alisson-becker', '알리송 베케르', 'Alisson Becker', '1992-10-02', null, null, '🌍', '축구선수', '브라질'],
  ['gl-giorgi-mamardashvili', '마마르다슈빌리', 'Giorgi Mamardashvili', '2000-09-29', null, null, '🌍', '축구선수', '조지아'],
  ['gl-devin-booker', '데빈 부커', 'Devin Booker', '1996-10-30', null, null, '🌍', '농구선수', '미국'],
  ['gl-ja-morant', '자 모란트', 'Ja Morant', '1999-08-10', null, null, '🌍', '농구선수', '미국'],
  ['gl-shai-gilgeous', '샤이 길저스 알렉산더', 'Shai Gilgeous-Alexander', '1998-07-12', null, null, '🌍', '농구선수', '캐나다'],
  ['gl-lauri-markkanen', '라우리 마르카넨', 'Lauri Markkanen', '1997-05-22', null, null, '🌍', '농구선수', '핀란드'],
  ['gl-wemby', '웸바냐마', null, '2004-01-04', null, null, '🌍', '농구선수', '프랑스'],
  ['gl-connor-mcdavid', '코너 맥데이비드', 'Connor McDavid', '1997-01-13', null, null, '🌍', '아이스하키선수', '캐나다'],
  ['gl-babe-ruth', '베이브 루스', 'Babe Ruth', '1895-02-06', null, null, '🌍', '야구선수', '전설', '미국'],

  // ===== ADDITIONAL JAPANESE =====
  ['gl-one-ok-rock-taka', '타카', 'Taka', '1988-04-17', null, 'ONE OK ROCK', '🌍', '가수', '록밴드', '일본'],
  ['gl-babymetal-sumetal', '스메탈', 'Su-metal', '1997-12-20', null, 'BABYMETAL', '🌍', '가수', '메탈', '일본'],
  ['gl-official-hige-dandism', '후지하라 사토시', 'Satoshi Fujihara', '1991-08-19', null, 'Official HIGE DANdism', '🌍', '가수', '일본'],
  ['gl-mrs-green-apple', '오모리 모토키', 'Motoki Omori', '1996-09-14', null, 'Mrs. GREEN APPLE', '🌍', '가수', '일본'],
  ['gl-vaundy', '바운디', 'Vaundy', '2000-06-06', null, null, '🌍', '가수', '싱어송라이터', '일본'],
  ['gl-yama', '야마', 'Yama', '1996-08-18', null, null, '🌍', '가수', '일본'],
  ['gl-atarashii-gakko', '새 학교의 리더즈', 'Atarashii Gakko!', '1998-08-29', null, 'Atarashii Gakko!', '🌍', '가수', '댄서', '일본'],
  ['gl-xg-jurin', '쥬린', 'Jurin', '2002-06-19', null, 'XG', '🌍', '가수', '아이돌', '일본'],

  // ===== CHINESE / CHINESE-SPEAKING CELEBRITIES =====
  ['gl-jay-chou', '주걸륜', 'Jay Chou', '1979-01-18', null, null, '🌍', '가수', '배우', '대만'],
  ['gl-jackson-wang', '잭슨', 'Jackson Wang', '1994-03-28', null, null, '🌍', '가수', '아이돌', '홍콩'],
  ['gl-lay-zhang', '레이', 'Lay Zhang', '1991-10-07', null, null, '🌍', '가수', '배우', '중국'],
  ['gl-lu-han', '루한', 'Lu Han', '1990-04-20', null, null, '🌍', '가수', '배우', '중국'],
  ['gl-kris-wu', '크리스 우', 'Kris Wu', '1990-11-06', null, null, '🌍', '가수', '배우', '캐나다계중국'],
  ['gl-jj-lin', '린준걸', 'JJ Lin', '1981-03-27', null, null, '🌍', '가수', '싱어송라이터', '싱가포르'],
  ['gl-eason-chan', '진이쉰', 'Eason Chan', '1974-07-27', null, null, '🌍', '가수', '홍콩'],
  ['gl-g-e-m', '등자기', 'G.E.M.', '1991-08-16', null, null, '🌍', '가수', '싱어송라이터', '홍콩'],
  ['gl-dimash', '디마쉬', 'Dimash Kudaibergen', '1994-05-24', null, null, '🌍', '가수', '카자흐스탄'],
  ['gl-jackie-chan', '성룡', 'Jackie Chan', '1954-04-07', null, null, '🌍', '배우', '무술가', '홍콩'],
  ['gl-bruce-lee', '이소룡', 'Bruce Lee', '1940-11-27', null, null, '🌍', '무술가', '배우', '미국계홍콩'],
  ['gl-tony-leung', '양조위', 'Tony Leung', '1962-06-27', null, null, '🌍', '배우', '홍콩'],
  ['gl-fan-bingbing', '판빙빙', 'Fan Bingbing', '1981-09-16', null, null, '🌍', '배우', '중국'],
  ['gl-gong-li', '공리', 'Gong Li', '1965-12-31', null, null, '🌍', '배우', '중국'],
  ['gl-zhang-yimou', '장이모우', 'Zhang Yimou', '1950-04-02', null, null, '🌍', '감독', '중국'],
  ['gl-wong-kar-wai', '왕가위', 'Wong Kar-wai', '1958-07-17', null, null, '🌍', '감독', '홍콩'],
  ['gl-ang-lee', '이안', 'Ang Lee', '1954-10-23', null, null, '🌍', '감독', '대만'],

  // ===== THAI / SOUTHEAST ASIAN =====
  ['gl-lalisa-extra', '리사', null, '1997-03-27', null, 'BLACKPINK', '🌍', '가수', '아이돌', '태국'],
  ['gl-bambam', '뱀뱀', 'BamBam', '1997-05-02', null, 'GOT7', '🌍', '가수', '아이돌', '태국'],
  ['gl-minnie', '민니', 'Minnie', '1997-10-23', null, '(G)I-DLE', '🌍', '가수', '아이돌', '태국'],
  ['gl-ten', '텐', 'Ten', '1996-02-27', null, 'WayV', '🌍', '가수', '댄서', '태국'],
  ['gl-bright-vachirawit', '브라이트', 'Bright Vachirawit', '1997-12-27', null, null, '🌍', '배우', '태국'],

  // ===== MORE SOCCER LEGENDS & CURRENT =====
  ['gl-gavi', '가비', 'Gavi', '2004-08-05', null, null, '🌍', '축구선수', '스페인'],
  ['gl-joao-felix', '주앙 펠릭스', 'João Félix', '1999-11-10', null, null, '🌍', '축구선수', '포르투갈'],
  ['gl-frenkie-de-jong', '프렌키 데 용', 'Frenkie de Jong', '1997-05-12', null, null, '🌍', '축구선수', '네덜란드'],
  ['gl-martin-odegaard', '마르틴 외데고르', 'Martin Ødegaard', '1998-12-17', null, null, '🌍', '축구선수', '노르웨이'],
  ['gl-raphinha', '하피냐', 'Raphinha', '1996-12-14', null, null, '🌍', '축구선수', '브라질'],
  ['gl-rodri', '로드리', 'Rodri', '1996-06-22', null, null, '🌍', '축구선수', '스페인'],
  ['gl-dani-olmo', '다니 올모', 'Dani Olmo', '1998-05-07', null, null, '🌍', '축구선수', '스페인'],
  ['gl-cole-palmer', '콜 파머', 'Cole Palmer', '2002-05-06', null, null, '🌍', '축구선수', '영국'],
  ['gl-marc-cucurella', '마르크 쿠쿠레야', 'Marc Cucurella', '1998-07-22', null, null, '🌍', '축구선수', '스페인'],
  ['gl-william-saliba', '윌리엄 살리바', 'William Saliba', '2001-03-24', null, null, '🌍', '축구선수', '프랑스'],
  ['gl-nico-williams', '니코 윌리엄스', 'Nico Williams', '2002-07-12', null, null, '🌍', '축구선수', '스페인'],
  ['gl-ronaldo-nazario', '호나우두', 'Ronaldo Nazário', '1976-09-18', null, null, '🌍', '축구선수', '전설', '브라질'],
  ['gl-andrea-pirlo', '안드레아 피를로', 'Andrea Pirlo', '1979-05-19', null, null, '🌍', '축구선수', '이탈리아'],
  ['gl-xavi', '사비', 'Xavi', '1980-01-25', null, null, '🌍', '축구선수', '감독', '스페인'],
  ['gl-andres-iniesta', '안드레스 이니에스타', 'Andrés Iniesta', '1984-05-11', null, null, '🌍', '축구선수', '스페인'],
  ['gl-steven-gerrard', '스티븐 제라드', 'Steven Gerrard', '1980-05-30', null, null, '🌍', '축구선수', '영국'],
  ['gl-frank-lampard', '프랭크 램파드', 'Frank Lampard', '1978-06-20', null, null, '🌍', '축구선수', '영국'],
  ['gl-kaka', '카카', 'Kaká', '1982-04-22', null, null, '🌍', '축구선수', '브라질'],
  ['gl-samuel-etoo', '사무엘 에투', 'Samuel Eto\'o', '1981-03-10', null, null, '🌍', '축구선수', '카메룬'],
  ['gl-didier-drogba', '디디에 드록바', 'Didier Drogba', '1978-03-11', null, null, '🌍', '축구선수', '코트디부아르'],
  ['gl-carles-puyol', '카를레스 푸욜', 'Carles Puyol', '1978-04-13', null, null, '🌍', '축구선수', '스페인'],
  ['gl-paolo-maldini', '파올로 말디니', 'Paolo Maldini', '1968-06-26', null, null, '🌍', '축구선수', '이탈리아'],

  // ===== MORE BASKETBALL =====
  ['gl-allen-iverson', '앨런 아이버슨', 'Allen Iverson', '1975-06-07', null, null, '🌍', '농구선수', '미국'],
  ['gl-kareem-abdul-jabbar', '카림 압둘자바', 'Kareem Abdul-Jabbar', '1947-04-16', null, null, '🌍', '농구선수', '전설', '미국'],
  ['gl-bill-russell', '빌 러셀', 'Bill Russell', '1934-02-12', null, null, '🌍', '농구선수', '전설', '미국'],
  ['gl-hakeem-olajuwon', '하킴 올라주원', 'Hakeem Olajuwon', '1963-01-21', null, null, '🌍', '농구선수', '나이지리아'],
  ['gl-charles-barkley', '찰스 바클리', 'Charles Barkley', '1963-02-20', null, null, '🌍', '농구선수', '미국'],
  ['gl-scottie-pippen', '스코티 피펜', 'Scottie Pippen', '1965-09-25', null, null, '🌍', '농구선수', '미국'],
  ['gl-dennis-rodman', '데니스 로드먼', 'Dennis Rodman', '1961-05-13', null, null, '🌍', '농구선수', '미국'],
  ['gl-isiah-thomas', '아이재아 토마스', 'Isiah Thomas', '1961-04-30', null, null, '🌍', '농구선수', '미국'],
  ['gl-dwyane-wade', '드웨인 웨이드', 'Dwyane Wade', '1982-01-17', null, null, '🌍', '농구선수', '미국'],
  ['gl-carmelo-anthony', '카멜로 앤서니', 'Carmelo Anthony', '1984-05-29', null, null, '🌍', '농구선수', '미국'],
  ['gl-james-harden', '제임스 하든', 'James Harden', '1989-08-26', null, null, '🌍', '농구선수', '미국'],
  ['gl-russell-westbrook', '러셀 웨스트브룩', 'Russell Westbrook', '1988-11-12', null, null, '🌍', '농구선수', '미국'],
  ['gl-damian-lillard', '데이미언 릴라드', 'Damian Lillard', '1990-07-15', null, null, '🌍', '농구선수', '미국'],
  ['gl-kyrie-irving', '카이리 어빙', 'Kyrie Irving', '1992-03-23', null, null, '🌍', '농구선수', '미국'],
  ['gl-kawhi-leonard', '카와이 레너드', 'Kawhi Leonard', '1991-06-29', null, null, '🌍', '농구선수', '미국'],
  ['gl-paul-george', '폴 조지', 'Paul George', '1990-05-02', null, null, '🌍', '농구선수', '미국'],
  ['gl-jimmy-butler', '지미 버틀러', 'Jimmy Butler', '1989-09-14', null, null, '🌍', '농구선수', '미국'],

  // ===== ANIME / MANGA CREATORS =====
  ['gl-eiichiro-oda', '오다 에이이치로', 'Eiichiro Oda', '1975-01-01', null, null, '🌍', '만화가', '일본'],
  ['gl-masashi-kishimoto', '기시모토 마사시', 'Masashi Kishimoto', '1974-11-08', null, null, '🌍', '만화가', '일본'],
  ['gl-akira-toriyama', '토리야마 아키라', 'Akira Toriyama', '1955-04-05', null, null, '🌍', '만화가', '일본'],
  ['gl-hajime-isayama', '이사야마 하지메', 'Hajime Isayama', '1986-08-29', null, null, '🌍', '만화가', '일본'],
  ['gl-gege-akutami', '아쿠타미 게게', 'Gege Akutami', '1992-02-26', null, null, '🌍', '만화가', '일본'],
  ['gl-tatsuki-fujimoto', '후지모토 타츠키', 'Tatsuki Fujimoto', '1993-10-10', null, null, '🌍', '만화가', '일본'],
  ['gl-rumiko-takahashi', '다카하시 루미코', 'Rumiko Takahashi', '1957-10-10', null, null, '🌍', '만화가', '일본'],
  ['gl-naoko-takeuchi', '다케우치 나오코', 'Naoko Takeuchi', '1967-03-15', null, null, '🌍', '만화가', '일본'],
  ['gl-osamu-tezuka', '데즈카 오사무', 'Osamu Tezuka', '1928-11-03', null, null, '🌍', '만화가', '일본'],

  // ===== GAME DEVELOPERS =====
  ['gl-shigeru-miyamoto', '미야모토 시게루', 'Shigeru Miyamoto', '1952-11-16', null, null, '🌍', '게임디자이너', '일본'],
  ['gl-hideo-kojima', '코지마 히데오', 'Hideo Kojima', '1963-08-24', null, null, '🌍', '게임디자이너', '일본'],
  ['gl-satoru-iwata', '이와타 사토루', 'Satoru Iwata', '1959-12-06', null, null, '🌍', '게임디자이너', 'CEO', '일본'],
  ['gl-masahiro-sakurai', '사쿠라이 마사히로', 'Masahiro Sakurai', '1970-08-03', null, null, '🌍', '게임디자이너', '일본'],
  ['gl-todd-howard', '토드 하워드', 'Todd Howard', '1971-04-25', null, null, '🌍', '게임디자이너', '미국'],
  ['gl-hidetaka-miyazaki', '미야자키 히데타카', 'Hidetaka Miyazaki', '1974-01-01', null, null, '🌍', '게임디자이너', '일본'],

  // ===== ESPORTS =====
  ['gl-faker', '페이커', 'Faker', '1996-05-07', null, null, '🌍', '프로게이머', '한국'],
  ['gl-s1mple', '심플', 's1mple', '1997-10-02', null, null, '🌍', '프로게이머', '우크라이나'],
  ['gl-bugha', '버가', 'Bugha', '2002-12-30', null, null, '🌍', '프로게이머', '미국'],

  // ===== MORE ATHLETES - MISC =====
  ['gl-lindsey-vonn', '린지 본', 'Lindsey Vonn', '1984-10-18', null, null, '🌍', '스키선수', '미국'],
  ['gl-shaun-white', '숀 화이트', 'Shaun White', '1986-09-03', null, null, '🌍', '스노보더', '미국'],
  ['gl-nadia-comaneci-gl', '나디아 코마네치', 'Nadia Comăneci', '1961-11-12', null, null, '🌍', '체조선수', '루마니아'],
  ['gl-carl-lewis', '칼 루이스', 'Carl Lewis', '1961-07-01', null, null, '🌍', '육상선수', '미국'],
  ['gl-jesse-owens', '제시 오웬스', 'Jesse Owens', '1913-09-12', null, null, '🌍', '육상선수', '미국'],
  ['gl-eliud-kipchoge', '엘리우드 킵초게', 'Eliud Kipchoge', '1984-11-05', null, null, '🌍', '마라토너', '케냐'],
  ['gl-allyson-felix', '앨리슨 펠릭스', 'Allyson Felix', '1985-11-18', null, null, '🌍', '육상선수', '미국'],
  ['gl-elaine-thompson', '일레인 톰슨 헤라', 'Elaine Thompson-Herah', '1992-06-28', null, null, '🌍', '육상선수', '자메이카'],
  ['gl-noah-lyles', '노아 라일스', 'Noah Lyles', '1997-07-18', null, null, '🌍', '육상선수', '미국'],
  ['gl-armand-duplantis', '아르망 뒤플란티스', 'Armand Duplantis', '1999-11-10', null, null, '🌍', '장대높이뛰기', '스웨덴'],
  ['gl-sydney-mclaughlin', '시드니 맥러플린', 'Sydney McLaughlin', '1999-08-07', null, null, '🌍', '허들선수', '미국'],

  // ===== ADDITIONAL MISC =====
  ['gl-rupaul', '루폴', 'RuPaul', '1960-11-17', null, null, '🌍', '드래그퀸', '방송인', '미국'],
  ['gl-gordon-ramsay', '고든 램지', 'Gordon Ramsay', '1966-11-08', null, null, '🌍', '셰프', '방송인', '영국'],
  ['gl-martha-stewart', '마사 스튜어트', 'Martha Stewart', '1941-08-03', null, null, '🌍', '사업가', '방송인', '미국'],
  ['gl-jamie-oliver', '제이미 올리버', 'Jamie Oliver', '1975-05-27', null, null, '🌍', '셰프', '방송인', '영국'],
  ['gl-banksy', '뱅크시', 'Banksy', '1974-01-01', null, null, '🌍', '예술가', '영국'],
  ['gl-takashi-murakami', '무라카미 다카시', 'Takashi Murakami', '1962-02-01', null, null, '🌍', '예술가', '일본'],
  ['gl-yayoi-kusama', '쿠사마 야요이', 'Yayoi Kusama', '1929-03-22', null, null, '🌍', '예술가', '일본'],
  ['gl-virgil-abloh', '버질 아블로', 'Virgil Abloh', '1980-09-30', null, null, '🌍', '디자이너', '미국'],
  ['gl-pharrell-fashion', '퍼렐 윌리엄스', null, '1973-04-05', null, null, '🌍', '디자이너', '미국'],
  ['gl-rei-kawakubo', '가와쿠보 레이', 'Rei Kawakubo', '1942-10-11', null, null, '🌍', '패션디자이너', '일본'],
  ['gl-karl-lagerfeld', '카를 라거펠트', 'Karl Lagerfeld', '1933-09-10', null, null, '🌍', '패션디자이너', '독일'],
  ['gl-coco-chanel', '코코 샤넬', 'Coco Chanel', '1883-08-19', null, null, '🌍', '패션디자이너', '프랑스'],
  ['gl-gianni-versace', '지아니 베르사체', 'Gianni Versace', '1946-12-02', null, null, '🌍', '패션디자이너', '이탈리아'],
  ['gl-donatella-versace', '도나텔라 베르사체', 'Donatella Versace', '1955-05-02', null, null, '🌍', '패션디자이너', '이탈리아'],
  ['gl-tom-ford', '톰 포드', 'Tom Ford', '1961-08-27', null, null, '🌍', '패션디자이너', '감독', '미국'],
  ['gl-alexander-mcqueen', '알렉산더 맥퀸', 'Alexander McQueen', '1969-03-17', null, null, '🌍', '패션디자이너', '영국'],

  // ===== ADDITIONAL GLOBAL ENTRIES =====
  ['gl-jason-derulo', '제이슨 데룰로', 'Jason Derulo', '1989-09-21', null, null, '🌍', '가수', '팝스타', '미국'],
  ['gl-pitbull', '핏불', 'Pitbull', '1981-01-15', null, null, '🌍', '래퍼', '가수', '미국'],
  ['gl-ne-yo', '니요', 'Ne-Yo', '1979-10-18', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-usher', '어셔', 'Usher', '1978-10-14', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-chris-brown', '크리스 브라운', 'Chris Brown', '1989-05-05', null, null, '🌍', '가수', 'R&B', '미국'],
  ['gl-jason-statham', '제이슨 스태덤', 'Jason Statham', '1967-07-26', null, null, '🌍', '배우', '영국'],
  ['gl-vin-diesel', '빈 디젤', 'Vin Diesel', '1967-07-18', null, null, '🌍', '배우', '미국'],
  ['gl-samuel-l-jackson', '사무엘 L. 잭슨', 'Samuel L. Jackson', '1948-12-21', null, null, '🌍', '배우', '미국'],
  ['gl-ryan-reynolds', '라이언 레이놀즈', 'Ryan Reynolds', '1976-10-23', null, null, '🌍', '배우', '캐나다'],
  ['gl-hugh-jackman', '휴 잭맨', 'Hugh Jackman', '1968-10-12', null, null, '🌍', '배우', '호주'],
  ['gl-joaquin-phoenix', '호아킨 피닉스', 'Joaquin Phoenix', '1974-10-28', null, null, '🌍', '배우', '미국'],
  ['gl-al-pacino', '알 파치노', 'Al Pacino', '1940-04-25', null, null, '🌍', '배우', '미국'],
  ['gl-robert-de-niro', '로버트 드 니로', 'Robert De Niro', '1943-08-17', null, null, '🌍', '배우', '미국'],
  ['gl-harrison-ford', '해리슨 포드', 'Harrison Ford', '1942-07-13', null, null, '🌍', '배우', '미국'],
  ['gl-sean-connery', '숀 코너리', 'Sean Connery', '1930-08-25', null, null, '🌍', '배우', '영국'],
  ['gl-clint-eastwood', '클린트 이스트우드', 'Clint Eastwood', '1930-05-31', null, null, '🌍', '배우', '감독', '미국'],
  ['gl-jackie-chan-extra', '성룡', null, '1954-04-07', null, null, '🌍', '배우', '무술가', '홍콩'],
  ['gl-jet-li', '이연걸', 'Jet Li', '1963-04-26', null, null, '🌍', '배우', '무술가', '중국'],
  ['gl-donnie-yen', '견자단', 'Donnie Yen', '1963-07-27', null, null, '🌍', '배우', '무술가', '홍콩'],
  ['gl-sophie-turner', '소피 터너', 'Sophie Turner', '1996-02-21', null, null, '🌍', '배우', '영국'],
  ['gl-maisie-williams', '메이지 윌리엄스', 'Maisie Williams', '1997-04-15', null, null, '🌍', '배우', '영국'],
  ['gl-millie-bobby-brown', '밀리 바비 브라운', 'Millie Bobby Brown', '2004-02-19', null, null, '🌍', '배우', '영국'],
  ['gl-sadie-sink', '세이디 싱크', 'Sadie Sink', '2002-04-16', null, null, '🌍', '배우', '미국'],
  ['gl-hunter-schafer', '헌터 셰이퍼', 'Hunter Schafer', '1998-12-31', null, null, '🌍', '모델', '배우', '미국'],
  ['gl-loewe-jonathan', '조나단 앤더슨', 'Jonathan Anderson', '1984-09-25', null, null, '🌍', '패션디자이너', '영국'],
]
