// [id, name, nameEn|null, birthDate(YYYY-MM-DD), birthHour|null, group|null, emoji, ...tags]
export default [
  // ===== KOREAN HISTORICAL FIGURES - ANCIENT & THREE KINGDOMS =====
  ['hist-gwanggaeto', '광개토대왕', 'Gwanggaeto the Great', '0374-01-01', null, null, '📜', '고구려', '왕', '한국'],
  ['hist-eulji-mundeok', '을지문덕', 'Eulji Mundeok', '0550-01-01', null, null, '📜', '고구려', '장군', '한국'],
  ['hist-yeon-gaesomun', '연개소문', 'Yeon Gaesomun', '0603-01-01', null, null, '📜', '고구려', '정치가', '한국'],
  ['hist-dae-joyoung', '대조영', 'Dae Joyoung', '0668-01-01', null, null, '📜', '발해', '왕', '한국'],
  ['hist-kim-yushin', '김유신', 'Kim Yu-shin', '0595-01-01', null, null, '📜', '신라', '장군', '한국'],
  ['hist-jang-bogo', '장보고', 'Jang Bogo', '0790-01-01', null, null, '📜', '신라', '무역왕', '한국'],
  ['hist-choe-chiwon', '최치원', 'Choe Chi-won', '0857-01-01', null, null, '📜', '신라', '학자', '한국'],
  ['hist-gyeonhwon', '견훤', 'Gyeon Hwon', '0867-01-01', null, null, '📜', '후백제', '왕', '한국'],
  ['hist-gungye', '궁예', 'Gung Ye', '0869-01-01', null, null, '📜', '후고구려', '왕', '한국'],

  // ===== GORYEO =====
  ['hist-wang-geon', '왕건', 'Wang Geon', '0877-01-31', null, null, '📜', '고려', '태조', '한국'],
  ['hist-gwangjong', '광종', 'Gwangjong', '0925-01-01', null, null, '📜', '고려', '왕', '한국'],
  ['hist-gang-gamchan', '강감찬', 'Gang Gam-chan', '0948-01-01', null, null, '📜', '고려', '장군', '한국'],
  ['hist-seo-hui', '서희', 'Seo Hui', '0942-01-01', null, null, '📜', '고려', '외교관', '한국'],
  ['hist-choi-chungheon', '최충헌', 'Choe Chung-heon', '1149-01-01', null, null, '📜', '고려', '무신', '한국'],
  ['hist-kim-busik', '김부식', 'Kim Bu-sik', '1075-01-01', null, null, '📜', '고려', '학자', '한국'],
  ['hist-ilyeon', '일연', 'Iryeon', '1206-01-01', null, null, '📜', '고려', '승려', '한국'],
  ['hist-jeong-mongju', '정몽주', 'Jeong Mong-ju', '1337-01-01', null, null, '📜', '고려', '충신', '한국'],
  ['hist-choe-yeong', '최영', 'Choe Yeong', '1316-01-01', null, null, '📜', '고려', '장군', '한국'],
  ['hist-choe-museon', '최무선', 'Choe Mu-seon', '1325-01-01', null, null, '📜', '고려', '발명가', '한국'],
  ['hist-mungeuk-monk', '보우', 'Bowoo', '1301-01-01', null, null, '📜', '고려', '승려', '한국'],

  // ===== JOSEON DYNASTY - EARLY =====
  ['hist-lee-seonggye', '이성계', 'Yi Seong-gye', '1335-10-27', null, null, '📜', '조선', '태조', '한국'],
  ['hist-lee-bangwon', '이방원', 'Yi Bang-won', '1367-06-13', null, null, '📜', '조선', '태종', '한국'],
  ['hist-sejong', '세종대왕', 'Sejong the Great', '1397-05-15', null, null, '📜', '조선', '왕', '한국'],
  ['hist-jang-yeongshil', '장영실', 'Jang Yeong-sil', '1390-01-01', null, null, '📜', '조선', '발명가', '한국'],
  ['hist-munjong', '문종', 'Munjong', '1414-11-15', null, null, '📜', '조선', '왕', '한국'],
  ['hist-danjong', '단종', 'Danjong', '1441-08-09', null, null, '📜', '조선', '왕', '한국'],
  ['hist-sejo', '세조', 'Sejo', '1417-11-02', null, null, '📜', '조선', '왕', '한국'],
  ['hist-seongjong', '성종', 'Seongjong', '1457-08-19', null, null, '📜', '조선', '왕', '한국'],
  ['hist-yeonsan', '연산군', 'Yeonsangun', '1476-11-23', null, null, '📜', '조선', '왕', '한국'],
  ['hist-jungjong', '중종', 'Jungjong', '1488-04-16', null, null, '📜', '조선', '왕', '한국'],

  // ===== JOSEON DYNASTY - MIDDLE =====
  ['hist-shin-saimdang', '신사임당', 'Shin Saimdang', '1504-01-01', null, null, '📜', '조선', '예술가', '한국'],
  ['hist-hwangjini', '황진이', 'Hwang Jin-i', '1506-01-01', null, null, '📜', '조선', '시인', '한국'],
  ['hist-yi-hwang', '이황', 'Yi Hwang', '1501-11-25', null, null, '📜', '조선', '학자', '한국'],
  ['hist-yi-i', '이이', 'Yi I', '1536-12-26', null, null, '📜', '조선', '학자', '한국'],
  ['hist-yi-sunsin', '이순신', 'Yi Sun-sin', '1545-04-28', null, null, '📜', '조선', '장군', '한국'],
  ['hist-seonjo', '선조', 'Seonjo', '1552-11-26', null, null, '📜', '조선', '왕', '한국'],
  ['hist-gwanghaegun', '광해군', 'Gwanghaegun', '1575-06-04', null, null, '📜', '조선', '왕', '한국'],
  ['hist-heo-jun', '허준', 'Heo Jun', '1539-01-01', null, null, '📜', '조선', '의사', '한국'],
  ['hist-heo-gyun', '허균', 'Heo Gyun', '1569-01-01', null, null, '📜', '조선', '소설가', '한국'],
  ['hist-heo-nanseolheon', '허난설헌', 'Heo Nanseolheon', '1563-01-01', null, null, '📜', '조선', '시인', '한국'],
  ['hist-ryu-seongryong', '유성룡', 'Ryu Seong-ryong', '1542-01-01', null, null, '📜', '조선', '재상', '한국'],
  ['hist-gwon-yul', '권율', 'Gwon Yul', '1537-01-01', null, null, '📜', '조선', '장군', '한국'],
  ['hist-kwak-jae-u', '곽재우', 'Gwak Jae-u', '1552-01-01', null, null, '📜', '조선', '의병장', '한국'],
  ['hist-nongae', '논개', 'Non-gae', '1574-01-01', null, null, '📜', '조선', '의녀', '한국'],
  ['hist-song-siyeol', '송시열', 'Song Si-yeol', '1607-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-injo', '인조', 'Injo', '1595-12-07', null, null, '📜', '조선', '왕', '한국'],

  // ===== JOSEON DYNASTY - LATE =====
  ['hist-yeongjo', '영조', 'Yeongjo', '1694-10-31', null, null, '📜', '조선', '왕', '한국'],
  ['hist-sado-seja', '사도세자', 'Crown Prince Sado', '1735-02-13', null, null, '📜', '조선', '세자', '한국'],
  ['hist-jeongjo', '정조', 'Jeongjo', '1752-10-28', null, null, '📜', '조선', '왕', '한국'],
  ['hist-jeong-yakyong', '정약용', 'Jeong Yak-yong', '1762-08-05', null, null, '📜', '조선', '학자', '한국'],
  ['hist-park-jiwon', '박지원', 'Park Ji-won', '1737-01-01', null, null, '📜', '조선', '소설가', '한국'],
  ['hist-kim-hongdo', '김홍도', 'Kim Hong-do', '1745-01-01', null, null, '📜', '조선', '화가', '한국'],
  ['hist-shin-yunbok', '신윤복', 'Shin Yun-bok', '1758-01-01', null, null, '📜', '조선', '화가', '한국'],
  ['hist-kim-jeongho', '김정호', 'Kim Jeong-ho', '1804-01-01', null, null, '📜', '조선', '지리학자', '한국'],
  ['hist-heungseon', '흥선대원군', 'Heungseon Daewongun', '1820-12-21', null, null, '📜', '조선', '섭정', '한국'],
  ['hist-gojong', '고종', 'Gojong', '1852-09-08', null, null, '📜', '대한제국', '황제', '한국'],
  ['hist-sunjong', '순종', 'Sunjong', '1874-03-25', null, null, '📜', '대한제국', '황제', '한국'],
  ['hist-myeongseong', '명성황후', 'Empress Myeongseong', '1851-11-17', null, null, '📜', '조선', '왕비', '한국'],
  ['hist-sunjo', '순조', 'Sunjo', '1790-07-29', null, null, '📜', '조선', '왕', '한국'],
  ['hist-heonjong', '헌종', 'Heonjong', '1827-09-08', null, null, '📜', '조선', '왕', '한국'],
  ['hist-cheoljong', '철종', 'Cheoljong', '1831-07-25', null, null, '📜', '조선', '왕', '한국'],

  // ===== KOREAN MODERN - INDEPENDENCE MOVEMENT =====
  ['hist-kim-gu', '김구', 'Kim Gu', '1876-08-29', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-ahn-junggeun', '안중근', 'Ahn Jung-geun', '1879-09-02', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-ahn-changho', '안창호', 'Ahn Chang-ho', '1878-11-09', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yun-bonggil', '윤봉길', 'Yun Bong-gil', '1908-06-21', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yu-gwansun', '유관순', 'Yu Gwan-sun', '1902-12-16', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-kim-okgyun', '김옥균', 'Kim Ok-gyun', '1851-02-23', null, null, '📜', '근대', '개혁가', '한국'],
  ['hist-jeon-bongjun', '전봉준', 'Jeon Bong-jun', '1855-01-01', null, null, '📜', '근대', '혁명가', '한국'],
  ['hist-choe-jewu', '최제우', 'Choe Je-u', '1824-12-18', null, null, '📜', '근대', '종교지도자', '한국'],
  ['hist-ji-seokyeong', '지석영', 'Ji Seok-yeong', '1855-05-15', null, null, '📜', '근대', '의사', '한국'],
  ['hist-seo-jaepil', '서재필', 'Seo Jae-pil', '1864-01-07', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-kim-daegon', '김대건', 'Kim Dae-geon', '1821-08-21', null, null, '📜', '조선', '신부', '한국'],
  ['hist-ju-sigyeong', '주시경', 'Ju Si-gyeong', '1876-12-22', null, null, '📜', '근대', '국어학자', '한국'],
  ['hist-bang-jeonghwan', '방정환', 'Bang Jeong-hwan', '1899-11-09', null, null, '📜', '근대', '아동운동가', '한국'],
  ['hist-lee-bongchang', '이봉창', 'Lee Bong-chang', '1900-08-10', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-shin-chaeho', '신채호', 'Shin Chae-ho', '1880-12-08', null, null, '📜', '근대', '역사학자', '한국'],
  ['hist-han-yongun', '한용운', 'Han Yong-un', '1879-08-29', null, null, '📜', '근대', '시인', '독립운동가', '한국'],
  ['hist-lee-hoeyoung', '이회영', 'Lee Hoe-young', '1867-04-21', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-kim-maria', '김마리아', 'Kim Maria', '1892-06-18', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-nam-ja-hyeon', '남자현', 'Nam Ja-hyeon', '1872-12-07', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yun-chiho', '윤치호', 'Yun Chi-ho', '1865-01-23', null, null, '📜', '근대', '정치가', '한국'],
  ['hist-lee-gwangsu', '이광수', 'Yi Gwang-su', '1892-03-05', null, null, '📜', '근대', '소설가', '한국'],
  ['hist-kim-sowol', '김소월', 'Kim So-wol', '1902-09-07', null, null, '📜', '근대', '시인', '한국'],
  ['hist-yun-dongju', '윤동주', 'Yun Dong-ju', '1917-12-30', null, null, '📜', '근대', '시인', '한국'],
  ['hist-lee-sang', '이상', 'Yi Sang', '1910-09-23', null, null, '📜', '근대', '시인', '소설가', '한국'],
  ['hist-na-hyeseok', '나혜석', 'Na Hye-seok', '1896-04-28', null, null, '📜', '근대', '화가', '여성운동가', '한국'],
  ['hist-park-eunsik', '박은식', 'Park Eun-sik', '1859-10-02', null, null, '📜', '근대', '역사학자', '한국'],
  ['hist-yi-donghwi', '이동휘', 'Yi Dong-hwi', '1873-06-20', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yeo-unhyeong', '여운형', 'Yeo Un-hyeong', '1886-05-25', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-cho-mansik', '조만식', 'Cho Man-sik', '1883-02-01', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-son-byunghee', '손병희', 'Son Byeong-hui', '1861-04-08', null, null, '📜', '근대', '종교지도자', '한국'],
  ['hist-lee-junghyun', '이준', 'Yi Jun', '1859-01-21', null, null, '📜', '근대', '외교관', '한국'],

  // ===== KOREAN - ADDITIONAL HISTORICAL =====
  ['hist-yi-gwangsa', '이광사', 'Yi Gwang-sa', '1705-01-01', null, null, '📜', '조선', '서예가', '한국'],
  ['hist-kim-satgat', '김삿갓', 'Kim Sat-gat', '1807-01-01', null, null, '📜', '조선', '방랑시인', '한국'],
  ['hist-chusa-kim', '김정희', 'Kim Jeong-hui', '1786-06-03', null, null, '📜', '조선', '서예가', '한국'],
  ['hist-jeonggam-nok', '남이', 'Nam I', '1441-01-01', null, null, '📜', '조선', '장군', '한국'],
  ['hist-im-kkeokjeong', '임꺽정', 'Im Kkeok-jeong', '1500-01-01', null, null, '📜', '조선', '의적', '한국'],
  ['hist-hong-gildong', '홍길동', 'Hong Gil-dong', '1443-01-01', null, null, '📜', '조선', '의적', '한국'],
  ['hist-park-hyeokgeose', '박혁거세', 'Park Hyeokgeose', '-0057-01-01', null, null, '📜', '신라', '시조', '한국'],
  ['hist-onjo', '온조', 'Onjo', '-0018-01-01', null, null, '📜', '백제', '시조', '한국'],
  ['hist-jumong', '주몽', 'Jumong', '-0058-01-01', null, null, '📜', '고구려', '시조', '한국'],
  ['hist-dangun', '단군', 'Dangun', '-2333-01-01', null, null, '📜', '고조선', '시조', '한국'],
  ['hist-gwanggaeto-stele', '장수왕', 'Jangsu of Goguryeo', '0394-01-01', null, null, '📜', '고구려', '왕', '한국'],
  ['hist-euija', '의자왕', 'Uija of Baekje', '0599-01-01', null, null, '📜', '백제', '왕', '한국'],
  ['hist-gyebaek', '계백', 'Gyebaek', '0600-01-01', null, null, '📜', '백제', '장군', '한국'],
  ['hist-wonhyo', '원효', 'Wonhyo', '0617-01-01', null, null, '📜', '신라', '승려', '한국'],
  ['hist-uisang', '의상', 'Uisang', '0625-01-01', null, null, '📜', '신라', '승려', '한국'],
  ['hist-seol-chong', '설총', 'Seol Chong', '0655-01-01', null, null, '📜', '신라', '학자', '한국'],
  ['hist-chungdam', '충담사', 'Chungdam', '0700-01-01', null, null, '📜', '신라', '승려', '한국'],

  // ===== KOREAN - JOSEON SCHOLARS & CULTURE =====
  ['hist-jeong-dojeon', '정도전', 'Jeong Do-jeon', '1342-01-01', null, null, '📜', '조선', '재상', '한국'],
  ['hist-hwang-hui', '황희', 'Hwang Hui', '1363-03-08', null, null, '📜', '조선', '재상', '한국'],
  ['hist-maeng-saseong', '맹사성', 'Maeng Sa-seong', '1360-01-01', null, null, '📜', '조선', '재상', '한국'],
  ['hist-seong-sammun', '성삼문', 'Seong Sam-mun', '1418-01-01', null, null, '📜', '조선', '충신', '한국'],
  ['hist-park-paengnyeon', '박팽년', 'Pak Paeng-nyeon', '1417-01-01', null, null, '📜', '조선', '충신', '한국'],
  ['hist-kim-jongseo', '김종서', 'Kim Jong-seo', '1383-01-01', null, null, '📜', '조선', '장군', '한국'],
  ['hist-jo-gwangjo', '조광조', 'Jo Gwang-jo', '1482-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-seo-gyeongdeok', '서경덕', 'Seo Gyeong-deok', '1489-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-seong-hon', '성혼', 'Seong Hon', '1535-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-jo-sik', '조식', 'Jo Sik', '1501-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-song-ikpil', '성익필', 'Song Ik-pil', '1534-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-yulgok-mother', '이이 어머니', null, '1504-01-01', null, null, '📜', '조선', '예술가', '한국'],
  ['hist-jeong-cheol', '정철', 'Jeong Cheol', '1536-01-01', null, null, '📜', '조선', '시인', '한국'],
  ['hist-yun-sundo', '윤선도', 'Yun Seon-do', '1587-01-01', null, null, '📜', '조선', '시인', '한국'],
  ['hist-park-yeonhyo', '박연', 'Park Yeon', '1378-01-01', null, null, '📜', '조선', '음악가', '한국'],
  ['hist-kim-simnip', '김시습', 'Kim Si-seup', '1435-01-01', null, null, '📜', '조선', '소설가', '한국'],
  ['hist-hong-daeyong', '홍대용', 'Hong Dae-yong', '1731-01-01', null, null, '📜', '조선', '과학자', '한국'],
  ['hist-choe-hangi', '최한기', 'Choe Han-gi', '1803-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-yi-ikk', '이익', 'Yi Ik', '1681-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-park-jega', '박제가', 'Park Je-ga', '1750-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-yi-deokmu', '이덕무', 'Yi Deok-mu', '1741-01-01', null, null, '📜', '조선', '학자', '한국'],

  // ===== WORLD HISTORICAL - ANCIENT =====
  ['hist-socrates', '소크라테스', 'Socrates', '-0470-01-01', null, null, '📜', '고대', '철학자', '그리스'],
  ['hist-plato', '플라톤', 'Plato', '-0428-01-01', null, null, '📜', '고대', '철학자', '그리스'],
  ['hist-aristotle', '아리스토텔레스', 'Aristotle', '-0384-01-01', null, null, '📜', '고대', '철학자', '그리스'],
  ['hist-alexander', '알렉산더 대왕', 'Alexander the Great', '-0356-07-20', null, null, '📜', '고대', '정복자', '마케도니아'],
  ['hist-julius-caesar', '율리우스 카이사르', 'Julius Caesar', '-0100-07-12', null, null, '📜', '고대', '정치가', '로마'],
  ['hist-cleopatra', '클레오파트라', 'Cleopatra', '-0069-01-01', null, null, '📜', '고대', '파라오', '이집트'],
  ['hist-augustus', '아우구스투스', 'Augustus', '-0063-09-23', null, null, '📜', '고대', '황제', '로마'],
  ['hist-nero', '네로', 'Nero', '0037-12-15', null, null, '📜', '고대', '황제', '로마'],
  ['hist-marcus-aurelius', '마르쿠스 아우렐리우스', 'Marcus Aurelius', '0121-04-26', null, null, '📜', '고대', '황제', '철학자', '로마'],
  ['hist-archimedes', '아르키메데스', 'Archimedes', '-0287-01-01', null, null, '📜', '고대', '수학자', '그리스'],
  ['hist-hippocrates', '히포크라테스', 'Hippocrates', '-0460-01-01', null, null, '📜', '고대', '의학자', '그리스'],
  ['hist-herodotus', '헤로도토스', 'Herodotus', '-0484-01-01', null, null, '📜', '고대', '역사가', '그리스'],
  ['hist-homer', '호메로스', 'Homer', '-0800-01-01', null, null, '📜', '고대', '시인', '그리스'],
  ['hist-pythagoras', '피타고라스', 'Pythagoras', '-0570-01-01', null, null, '📜', '고대', '수학자', '그리스'],
  ['hist-hannibal', '한니발', 'Hannibal', '-0247-01-01', null, null, '📜', '고대', '장군', '카르타고'],
  ['hist-spartacus', '스파르타쿠스', 'Spartacus', '-0111-01-01', null, null, '📜', '고대', '검투사', '트라키아'],
  ['hist-attila', '아틸라', 'Attila the Hun', '0406-01-01', null, null, '📜', '고대', '정복자', '훈족'],

  // ===== RELIGIOUS FIGURES =====
  ['hist-confucius', '공자', 'Confucius', '-0551-09-28', null, null, '📜', '고대', '철학자', '중국'],
  ['hist-laozi', '노자', 'Laozi', '-0571-01-01', null, null, '📜', '고대', '철학자', '중국'],
  ['hist-buddha', '석가모니', 'Buddha', '-0563-04-08', null, null, '📜', '고대', '종교지도자', '인도'],
  ['hist-jesus', '예수', 'Jesus Christ', '0001-12-25', null, null, '📜', '고대', '종교지도자', '이스라엘'],
  ['hist-muhammad', '무함마드', 'Muhammad', '0570-04-22', null, null, '📜', '중세', '종교지도자', '아라비아'],
  ['hist-moses', '모세', 'Moses', '-1393-01-01', null, null, '📜', '고대', '종교지도자', '이집트'],
  ['hist-martin-luther', '마르틴 루터', 'Martin Luther', '1483-11-10', null, null, '📜', '중세', '종교개혁가', '독일'],
  ['hist-john-calvin', '장 칼뱅', 'John Calvin', '1509-07-10', null, null, '📜', '중세', '종교개혁가', '프랑스'],
  ['hist-thomas-aquinas', '토마스 아퀴나스', 'Thomas Aquinas', '1225-01-28', null, null, '📜', '중세', '신학자', '이탈리아'],
  ['hist-saint-francis', '성 프란치스코', 'Saint Francis of Assisi', '1181-01-01', null, null, '📜', '중세', '성인', '이탈리아'],

  // ===== CHINESE HISTORICAL =====
  ['hist-sunzi', '손자', 'Sun Tzu', '-0544-01-01', null, null, '📜', '고대', '병법가', '중국'],
  ['hist-qin-shi-huang', '진시황', 'Qin Shi Huang', '-0259-01-01', null, null, '📜', '고대', '황제', '중국'],
  ['hist-cao-cao', '조조', 'Cao Cao', '0155-01-01', null, null, '📜', '삼국시대', '정치가', '중국'],
  ['hist-liu-bei', '유비', 'Liu Bei', '0161-01-01', null, null, '📜', '삼국시대', '정치가', '중국'],
  ['hist-zhuge-liang', '제갈량', 'Zhuge Liang', '0181-01-01', null, null, '📜', '삼국시대', '전략가', '중국'],
  ['hist-guan-yu', '관우', 'Guan Yu', '0160-01-01', null, null, '📜', '삼국시대', '장군', '중국'],
  ['hist-zhang-fei', '장비', 'Zhang Fei', '0167-01-01', null, null, '📜', '삼국시대', '장군', '중국'],
  ['hist-wu-zetian', '무측천', 'Wu Zetian', '0624-02-17', null, null, '📜', '당나라', '여제', '중국'],
  ['hist-li-shimin', '이세민', 'Li Shimin', '0598-01-28', null, null, '📜', '당나라', '황제', '중국'],
  ['hist-jiang-taigong', '강태공', 'Jiang Ziya', '-1128-01-01', null, null, '📜', '고대', '전략가', '중국'],
  ['hist-mencius', '맹자', 'Mencius', '-0372-01-01', null, null, '📜', '고대', '철학자', '중국'],
  ['hist-zhuangzi', '장자', 'Zhuangzi', '-0369-01-01', null, null, '📜', '고대', '철학자', '중국'],
  ['hist-han-wudi', '한무제', 'Emperor Wu of Han', '-0156-01-01', null, null, '📜', '한나라', '황제', '중국'],
  ['hist-sima-qian', '사마천', 'Sima Qian', '-0145-01-01', null, null, '📜', '한나라', '역사가', '중국'],
  ['hist-li-bai', '이백', 'Li Bai', '0701-01-01', null, null, '📜', '당나라', '시인', '중국'],
  ['hist-du-fu', '두보', 'Du Fu', '0712-01-01', null, null, '📜', '당나라', '시인', '중국'],
  ['hist-genghis-khan', '칭기즈 칸', 'Genghis Khan', '1162-05-31', null, null, '📜', '중세', '정복자', '몽골'],
  ['hist-kublai-khan', '쿠빌라이 칸', 'Kublai Khan', '1215-09-23', null, null, '📜', '중세', '황제', '몽골'],
  ['hist-zhu-yuanzhang', '주원장', 'Zhu Yuanzhang', '1328-10-21', null, null, '📜', '명나라', '황제', '중국'],
  ['hist-zheng-he', '정화', 'Zheng He', '1371-01-01', null, null, '📜', '명나라', '항해가', '중국'],
  ['hist-kangxi', '강희제', 'Kangxi Emperor', '1654-05-04', null, null, '📜', '청나라', '황제', '중국'],
  ['hist-cixi', '서태후', 'Empress Dowager Cixi', '1835-11-29', null, null, '📜', '청나라', '섭정', '중국'],
  ['hist-sun-yatsen', '쑨원', 'Sun Yat-sen', '1866-11-12', null, null, '📜', '근대', '혁명가', '중국'],
  ['hist-mao-zedong', '마오쩌둥', 'Mao Zedong', '1893-12-26', null, null, '📜', '근대', '정치가', '중국'],

  // ===== JAPANESE HISTORICAL =====
  ['hist-oda-nobunaga', '오다 노부나가', 'Oda Nobunaga', '1534-06-23', null, null, '📜', '전국시대', '다이묘', '일본'],
  ['hist-toyotomi-hideyoshi', '도요토미 히데요시', 'Toyotomi Hideyoshi', '1537-03-17', null, null, '📜', '전국시대', '통일자', '일본'],
  ['hist-tokugawa-ieyasu', '도쿠가와 이에야스', 'Tokugawa Ieyasu', '1543-01-31', null, null, '📜', '에도시대', '쇼군', '일본'],
  ['hist-miyamoto-musashi', '미야모토 무사시', 'Miyamoto Musashi', '1584-01-01', null, null, '📜', '에도시대', '검객', '일본'],
  ['hist-sakamoto-ryoma', '사카모토 료마', 'Sakamoto Ryoma', '1836-01-03', null, null, '📜', '막부말기', '지사', '일본'],
  ['hist-takeda-shingen', '다케다 신겐', 'Takeda Shingen', '1521-12-01', null, null, '📜', '전국시대', '다이묘', '일본'],
  ['hist-uesugi-kenshin', '우에스기 겐신', 'Uesugi Kenshin', '1530-02-18', null, null, '📜', '전국시대', '다이묘', '일본'],
  ['hist-saigo-takamori', '사이고 다카모리', 'Saigo Takamori', '1828-01-23', null, null, '📜', '막부말기', '무사', '일본'],
  ['hist-meiji-emperor', '메이지 천황', 'Emperor Meiji', '1852-11-03', null, null, '📜', '근대', '천황', '일본'],
  ['hist-ito-hirobumi', '이토 히로부미', 'Ito Hirobumi', '1841-10-16', null, null, '📜', '근대', '정치가', '일본'],

  // ===== EUROPEAN MEDIEVAL & RENAISSANCE =====
  ['hist-charlemagne', '샤를마뉴', 'Charlemagne', '0742-04-02', null, null, '📜', '중세', '황제', '프랑크'],
  ['hist-william-conqueror', '윌리엄 1세', 'William the Conqueror', '1028-01-01', null, null, '📜', '중세', '왕', '영국'],
  ['hist-richard-lionheart', '리처드 1세', 'Richard the Lionheart', '1157-09-08', null, null, '📜', '중세', '왕', '영국'],
  ['hist-joan-of-arc', '잔 다르크', 'Joan of Arc', '1412-01-06', null, null, '📜', '중세', '성녀', '프랑스'],
  ['hist-marco-polo', '마르코 폴로', 'Marco Polo', '1254-09-15', null, null, '📜', '중세', '탐험가', '이탈리아'],
  ['hist-columbus', '크리스토퍼 콜럼버스', 'Christopher Columbus', '1451-10-31', null, null, '📜', '대항해시대', '탐험가', '이탈리아'],
  ['hist-magellan', '페르디난드 마젤란', 'Ferdinand Magellan', '1480-02-03', null, null, '📜', '대항해시대', '탐험가', '포르투갈'],
  ['hist-da-vinci', '레오나르도 다 빈치', 'Leonardo da Vinci', '1452-04-15', null, null, '📜', '르네상스', '예술가', '이탈리아'],
  ['hist-michelangelo', '미켈란젤로', 'Michelangelo', '1475-03-06', null, null, '📜', '르네상스', '예술가', '이탈리아'],
  ['hist-raphael', '라파엘로', 'Raphael', '1483-04-06', null, null, '📜', '르네상스', '화가', '이탈리아'],
  ['hist-galileo', '갈릴레오 갈릴레이', 'Galileo Galilei', '1564-02-15', null, null, '📜', '르네상스', '과학자', '이탈리아'],
  ['hist-copernicus', '코페르니쿠스', 'Nicolaus Copernicus', '1473-02-19', null, null, '📜', '르네상스', '천문학자', '폴란드'],
  ['hist-gutenberg', '구텐베르크', 'Johannes Gutenberg', '1400-01-01', null, null, '📜', '르네상스', '발명가', '독일'],
  ['hist-machiavelli', '마키아벨리', 'Niccolò Machiavelli', '1469-05-03', null, null, '📜', '르네상스', '정치사상가', '이탈리아'],

  // ===== EUROPEAN MODERN - SCIENTISTS =====
  ['hist-newton', '아이작 뉴턴', 'Isaac Newton', '1643-01-04', null, null, '📜', '근대', '과학자', '영국'],
  ['hist-einstein', '알베르트 아인슈타인', 'Albert Einstein', '1879-03-14', null, null, '📜', '근대', '물리학자', '독일'],
  ['hist-tesla', '니콜라 테슬라', 'Nikola Tesla', '1856-07-10', null, null, '📜', '근대', '발명가', '세르비아계미국'],
  ['hist-marie-curie', '마리 퀴리', 'Marie Curie', '1867-11-07', null, null, '📜', '근대', '과학자', '폴란드계프랑스'],
  ['hist-darwin', '찰스 다윈', 'Charles Darwin', '1809-02-12', null, null, '📜', '근대', '생물학자', '영국'],
  ['hist-pasteur', '루이 파스퇴르', 'Louis Pasteur', '1822-12-27', null, null, '📜', '근대', '미생물학자', '프랑스'],
  ['hist-edison', '토마스 에디슨', 'Thomas Edison', '1847-02-11', null, null, '📜', '근대', '발명가', '미국'],
  ['hist-bell', '알렉산더 그레이엄 벨', 'Alexander Graham Bell', '1847-03-03', null, null, '📜', '근대', '발명가', '영국계미국'],
  ['hist-wright-orville', '오빌 라이트', 'Orville Wright', '1871-08-19', null, null, '📜', '근대', '발명가', '미국'],
  ['hist-wright-wilbur', '윌버 라이트', 'Wilbur Wright', '1867-04-16', null, null, '📜', '근대', '발명가', '미국'],
  ['hist-ada-lovelace', '에이다 러브레이스', 'Ada Lovelace', '1815-12-10', null, null, '📜', '근대', '수학자', '영국'],
  ['hist-alan-turing', '앨런 튜링', 'Alan Turing', '1912-06-23', null, null, '📜', '근대', '수학자', '영국'],
  ['hist-nightingale', '플로렌스 나이팅게일', 'Florence Nightingale', '1820-05-12', null, null, '📜', '근대', '간호사', '영국'],
  ['hist-kepler', '요하네스 케플러', 'Johannes Kepler', '1571-12-27', null, null, '📜', '르네상스', '천문학자', '독일'],
  ['hist-leibniz', '고트프리트 라이프니츠', 'Gottfried Wilhelm Leibniz', '1646-07-01', null, null, '📜', '근대', '수학자', '독일'],
  ['hist-descartes', '르네 데카르트', 'René Descartes', '1596-03-31', null, null, '📜', '근대', '철학자', '프랑스'],
  ['hist-pascal', '블레즈 파스칼', 'Blaise Pascal', '1623-06-19', null, null, '📜', '근대', '수학자', '프랑스'],
  ['hist-faraday', '마이클 패러데이', 'Michael Faraday', '1791-09-22', null, null, '📜', '근대', '물리학자', '영국'],
  ['hist-maxwell', '제임스 맥스웰', 'James Clerk Maxwell', '1831-06-13', null, null, '📜', '근대', '물리학자', '영국'],
  ['hist-mendel', '그레고르 멘델', 'Gregor Mendel', '1822-07-20', null, null, '📜', '근대', '유전학자', '오스트리아'],
  ['hist-bohr', '닐스 보어', 'Niels Bohr', '1885-10-07', null, null, '📜', '근대', '물리학자', '덴마크'],
  ['hist-heisenberg', '베르너 하이젠베르크', 'Werner Heisenberg', '1901-12-05', null, null, '📜', '근대', '물리학자', '독일'],
  ['hist-schrodinger', '에르빈 슈뢰딩거', 'Erwin Schrödinger', '1887-08-12', null, null, '📜', '근대', '물리학자', '오스트리아'],
  ['hist-max-planck', '막스 플랑크', 'Max Planck', '1858-04-23', null, null, '📜', '근대', '물리학자', '독일'],
  ['hist-fermi', '엔리코 페르미', 'Enrico Fermi', '1901-09-29', null, null, '📜', '근대', '물리학자', '이탈리아'],
  ['hist-oppenheimer', '로버트 오펜하이머', 'J. Robert Oppenheimer', '1904-04-22', null, null, '📜', '근대', '물리학자', '미국'],
  ['hist-feynman', '리처드 파인만', 'Richard Feynman', '1918-05-11', null, null, '📜', '근대', '물리학자', '미국'],
  ['hist-gauss', '카를 프리드리히 가우스', 'Carl Friedrich Gauss', '1777-04-30', null, null, '📜', '근대', '수학자', '독일'],
  ['hist-euler', '레온하르트 오일러', 'Leonhard Euler', '1707-04-15', null, null, '📜', '근대', '수학자', '스위스'],
  ['hist-ramanujan', '라마누잔', 'Srinivasa Ramanujan', '1887-12-22', null, null, '📜', '근대', '수학자', '인도'],

  // ===== THINKERS & PHILOSOPHERS =====
  ['hist-kant', '임마누엘 칸트', 'Immanuel Kant', '1724-04-22', null, null, '📜', '근대', '철학자', '독일'],
  ['hist-hegel', '게오르크 헤겔', 'Georg Wilhelm Friedrich Hegel', '1770-08-27', null, null, '📜', '근대', '철학자', '독일'],
  ['hist-marx', '카를 마르크스', 'Karl Marx', '1818-05-05', null, null, '📜', '근대', '철학자', '독일'],
  ['hist-nietzsche', '프리드리히 니체', 'Friedrich Nietzsche', '1844-10-15', null, null, '📜', '근대', '철학자', '독일'],
  ['hist-freud', '지그문트 프로이트', 'Sigmund Freud', '1856-05-06', null, null, '📜', '근대', '심리학자', '오스트리아'],
  ['hist-jung', '카를 융', 'Carl Jung', '1875-07-26', null, null, '📜', '근대', '심리학자', '스위스'],
  ['hist-voltaire', '볼테르', 'Voltaire', '1694-11-21', null, null, '📜', '근대', '철학자', '프랑스'],
  ['hist-rousseau', '장자크 루소', 'Jean-Jacques Rousseau', '1712-06-28', null, null, '📜', '근대', '철학자', '스위스'],
  ['hist-locke', '존 로크', 'John Locke', '1632-08-29', null, null, '📜', '근대', '철학자', '영국'],
  ['hist-hobbes', '토마스 홉스', 'Thomas Hobbes', '1588-04-05', null, null, '📜', '근대', '철학자', '영국'],
  ['hist-adam-smith', '애덤 스미스', 'Adam Smith', '1723-06-16', null, null, '📜', '근대', '경제학자', '영국'],
  ['hist-montesquieu', '몽테스키외', 'Montesquieu', '1689-01-18', null, null, '📜', '근대', '사상가', '프랑스'],
  ['hist-schopenhauer', '아르투어 쇼펜하우어', 'Arthur Schopenhauer', '1788-02-22', null, null, '📜', '근대', '철학자', '독일'],
  ['hist-kierkegaard', '쇠렌 키르케고르', 'Søren Kierkegaard', '1813-05-05', null, null, '📜', '근대', '철학자', '덴마크'],
  ['hist-wittgenstein', '루트비히 비트겐슈타인', 'Ludwig Wittgenstein', '1889-04-26', null, null, '📜', '근대', '철학자', '오스트리아'],
  ['hist-sartre', '장폴 사르트르', 'Jean-Paul Sartre', '1905-06-21', null, null, '📜', '근대', '철학자', '프랑스'],
  ['hist-simone-de-beauvoir', '시몬 드 보부아르', 'Simone de Beauvoir', '1908-01-09', null, null, '📜', '근대', '철학자', '프랑스'],
  ['hist-hannah-arendt', '한나 아렌트', 'Hannah Arendt', '1906-10-14', null, null, '📜', '근대', '철학자', '독일계미국'],

  // ===== POLITICAL LEADERS =====
  ['hist-napoleon', '나폴레옹', 'Napoleon Bonaparte', '1769-08-15', null, null, '📜', '근대', '황제', '프랑스'],
  ['hist-washington', '조지 워싱턴', 'George Washington', '1732-02-22', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-jefferson', '토마스 제퍼슨', 'Thomas Jefferson', '1743-04-13', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-franklin', '벤저민 프랭클린', 'Benjamin Franklin', '1706-01-17', null, null, '📜', '근대', '정치가', '미국'],
  ['hist-lincoln', '에이브러햄 링컨', 'Abraham Lincoln', '1809-02-12', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-queen-elizabeth-i', '엘리자베스 1세', 'Queen Elizabeth I', '1533-09-07', null, null, '📜', '르네상스', '여왕', '영국'],
  ['hist-queen-victoria', '빅토리아 여왕', 'Queen Victoria', '1819-05-24', null, null, '📜', '근대', '여왕', '영국'],
  ['hist-churchill', '윈스턴 처칠', 'Winston Churchill', '1874-11-30', null, null, '📜', '근대', '총리', '영국'],
  ['hist-fdr', '프랭클린 루즈벨트', 'Franklin D. Roosevelt', '1882-01-30', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-jfk', '존 F. 케네디', 'John F. Kennedy', '1917-05-29', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-mlk', '마틴 루서 킹', 'Martin Luther King Jr.', '1929-01-15', null, null, '📜', '근대', '인권운동가', '미국'],
  ['hist-gandhi', '마하트마 간디', 'Mahatma Gandhi', '1869-10-02', null, null, '📜', '근대', '독립운동가', '인도'],
  ['hist-mandela', '넬슨 만델라', 'Nelson Mandela', '1918-07-18', null, null, '📜', '근대', '대통령', '남아프리카'],
  ['hist-obama', '버락 오바마', 'Barack Obama', '1961-08-04', null, null, '📜', '현대', '대통령', '미국'],
  ['hist-trump', '도널드 트럼프', 'Donald Trump', '1946-06-14', null, null, '📜', '현대', '대통령', '미국'],
  ['hist-henry-viii', '헨리 8세', 'Henry VIII', '1491-06-28', null, null, '📜', '르네상스', '왕', '영국'],
  ['hist-louis-xiv', '루이 14세', 'Louis XIV', '1638-09-05', null, null, '📜', '근대', '왕', '프랑스'],
  ['hist-catherine-great', '예카테리나 대제', 'Catherine the Great', '1729-05-02', null, null, '📜', '근대', '여제', '러시아'],
  ['hist-peter-great', '표트르 대제', 'Peter the Great', '1672-06-09', null, null, '📜', '근대', '황제', '러시아'],
  ['hist-bismarck', '오토 폰 비스마르크', 'Otto von Bismarck', '1815-04-01', null, null, '📜', '근대', '재상', '독일'],
  ['hist-garibaldi', '주세페 가리발디', 'Giuseppe Garibaldi', '1807-07-04', null, null, '📜', '근대', '혁명가', '이탈리아'],
  ['hist-simon-bolivar', '시몬 볼리바르', 'Simón Bolívar', '1783-07-24', null, null, '📜', '근대', '해방자', '베네수엘라'],
  ['hist-che-guevara', '체 게바라', 'Che Guevara', '1928-06-14', null, null, '📜', '근대', '혁명가', '아르헨티나'],
  ['hist-fidel-castro', '피델 카스트로', 'Fidel Castro', '1926-08-13', null, null, '📜', '근대', '정치가', '쿠바'],
  ['hist-lenin', '블라디미르 레닌', 'Vladimir Lenin', '1870-04-22', null, null, '📜', '근대', '혁명가', '러시아'],
  ['hist-stalin', '이오시프 스탈린', 'Joseph Stalin', '1878-12-18', null, null, '📜', '근대', '독재자', '소련'],
  ['hist-hitler', '아돌프 히틀러', 'Adolf Hitler', '1889-04-20', null, null, '📜', '근대', '독재자', '독일'],
  ['hist-mussolini', '베니토 무솔리니', 'Benito Mussolini', '1883-07-29', null, null, '📜', '근대', '독재자', '이탈리아'],
  ['hist-rosa-parks', '로자 파크스', 'Rosa Parks', '1913-02-04', null, null, '📜', '근대', '인권운동가', '미국'],
  ['hist-mother-teresa', '마더 테레사', 'Mother Teresa', '1910-08-26', null, null, '📜', '근대', '성녀', '북마케도니아계인도'],
  ['hist-dalai-lama', '달라이 라마', 'Dalai Lama', '1935-07-06', null, null, '📜', '현대', '종교지도자', '티베트'],

  // ===== ARTISTS & MUSICIANS =====
  ['hist-shakespeare', '윌리엄 셰익스피어', 'William Shakespeare', '1564-04-23', null, null, '📜', '르네상스', '극작가', '영국'],
  ['hist-rembrandt', '렘브란트', 'Rembrandt', '1606-07-15', null, null, '📜', '바로크', '화가', '네덜란드'],
  ['hist-bach', '요한 세바스찬 바흐', 'Johann Sebastian Bach', '1685-03-31', null, null, '📜', '바로크', '작곡가', '독일'],
  ['hist-mozart', '볼프강 아마데우스 모차르트', 'Wolfgang Amadeus Mozart', '1756-01-27', null, null, '📜', '고전주의', '작곡가', '오스트리아'],
  ['hist-beethoven', '루트비히 판 베토벤', 'Ludwig van Beethoven', '1770-12-17', null, null, '📜', '고전주의', '작곡가', '독일'],
  ['hist-van-gogh', '빈센트 반 고흐', 'Vincent van Gogh', '1853-03-30', null, null, '📜', '근대', '화가', '네덜란드'],
  ['hist-picasso', '파블로 피카소', 'Pablo Picasso', '1881-10-25', null, null, '📜', '근대', '화가', '스페인'],
  ['hist-frida-kahlo', '프리다 칼로', 'Frida Kahlo', '1907-07-06', null, null, '📜', '근대', '화가', '멕시코'],
  ['hist-monet', '클로드 모네', 'Claude Monet', '1840-11-14', null, null, '📜', '근대', '화가', '프랑스'],
  ['hist-renoir', '피에르 오귀스트 르누아르', 'Pierre-Auguste Renoir', '1841-02-25', null, null, '📜', '근대', '화가', '프랑스'],
  ['hist-dali', '살바도르 달리', 'Salvador Dalí', '1904-05-11', null, null, '📜', '근대', '화가', '스페인'],
  ['hist-warhol', '앤디 워홀', 'Andy Warhol', '1928-08-06', null, null, '📜', '현대', '예술가', '미국'],
  ['hist-vermeer', '요하네스 페르메이르', 'Johannes Vermeer', '1632-10-31', null, null, '📜', '바로크', '화가', '네덜란드'],
  ['hist-caravaggio', '카라바조', 'Caravaggio', '1571-09-29', null, null, '📜', '바로크', '화가', '이탈리아'],
  ['hist-goya', '프란시스코 고야', 'Francisco Goya', '1746-03-30', null, null, '📜', '근대', '화가', '스페인'],
  ['hist-rodin', '오귀스트 로댕', 'Auguste Rodin', '1840-11-12', null, null, '📜', '근대', '조각가', '프랑스'],
  ['hist-chopin', '프레데리크 쇼팽', 'Frédéric Chopin', '1810-03-01', null, null, '📜', '낭만주의', '작곡가', '폴란드'],
  ['hist-liszt', '프란츠 리스트', 'Franz Liszt', '1811-10-22', null, null, '📜', '낭만주의', '피아니스트', '헝가리'],
  ['hist-tchaikovsky', '표트르 차이코프스키', 'Pyotr Tchaikovsky', '1840-05-07', null, null, '📜', '낭만주의', '작곡가', '러시아'],
  ['hist-wagner', '리하르트 바그너', 'Richard Wagner', '1813-05-22', null, null, '📜', '낭만주의', '작곡가', '독일'],
  ['hist-verdi', '주세페 베르디', 'Giuseppe Verdi', '1813-10-10', null, null, '📜', '낭만주의', '작곡가', '이탈리아'],
  ['hist-vivaldi', '안토니오 비발디', 'Antonio Vivaldi', '1678-03-04', null, null, '📜', '바로크', '작곡가', '이탈리아'],
  ['hist-handel', '게오르크 헨델', 'George Frideric Handel', '1685-02-23', null, null, '📜', '바로크', '작곡가', '독일계영국'],
  ['hist-schubert', '프란츠 슈베르트', 'Franz Schubert', '1797-01-31', null, null, '📜', '낭만주의', '작곡가', '오스트리아'],
  ['hist-brahms', '요하네스 브람스', 'Johannes Brahms', '1833-05-07', null, null, '📜', '낭만주의', '작곡가', '독일'],
  ['hist-debussy', '클로드 드뷔시', 'Claude Debussy', '1862-08-22', null, null, '📜', '근대', '작곡가', '프랑스'],
  ['hist-stravinsky', '이고르 스트라빈스키', 'Igor Stravinsky', '1882-06-17', null, null, '📜', '근대', '작곡가', '러시아'],
  ['hist-mahler', '구스타프 말러', 'Gustav Mahler', '1860-07-07', null, null, '📜', '근대', '작곡가', '오스트리아'],
  ['hist-rachmaninoff', '세르게이 라흐마니노프', 'Sergei Rachmaninoff', '1873-04-01', null, null, '📜', '근대', '작곡가', '러시아'],
  ['hist-dvorak', '안토닌 드보르자크', 'Antonín Dvořák', '1841-09-08', null, null, '📜', '낭만주의', '작곡가', '체코'],
  ['hist-paganini', '니콜로 파가니니', 'Niccolò Paganini', '1782-10-27', null, null, '📜', '낭만주의', '바이올리니스트', '이탈리아'],

  // ===== WRITERS =====
  ['hist-dante', '단테', 'Dante Alighieri', '1265-06-01', null, null, '📜', '중세', '시인', '이탈리아'],
  ['hist-cervantes', '세르반테스', 'Miguel de Cervantes', '1547-09-29', null, null, '📜', '르네상스', '소설가', '스페인'],
  ['hist-goethe', '요한 볼프강 폰 괴테', 'Johann Wolfgang von Goethe', '1749-08-28', null, null, '📜', '근대', '시인', '독일'],
  ['hist-tolstoy', '레프 톨스토이', 'Leo Tolstoy', '1828-09-09', null, null, '📜', '근대', '소설가', '러시아'],
  ['hist-dostoevsky', '표도르 도스토예프스키', 'Fyodor Dostoevsky', '1821-11-11', null, null, '📜', '근대', '소설가', '러시아'],
  ['hist-dickens', '찰스 디킨스', 'Charles Dickens', '1812-02-07', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-twain', '마크 트웨인', 'Mark Twain', '1835-11-30', null, null, '📜', '근대', '소설가', '미국'],
  ['hist-wilde', '오스카 와일드', 'Oscar Wilde', '1854-10-16', null, null, '📜', '근대', '극작가', '아일랜드'],
  ['hist-kafka', '프란츠 카프카', 'Franz Kafka', '1883-07-03', null, null, '📜', '근대', '소설가', '체코'],
  ['hist-hemingway', '어니스트 헤밍웨이', 'Ernest Hemingway', '1899-07-21', null, null, '📜', '근대', '소설가', '미국'],
  ['hist-orwell', '조지 오웰', 'George Orwell', '1903-06-25', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-austen', '제인 오스틴', 'Jane Austen', '1775-12-16', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-bronte-charlotte', '샬럿 브론테', 'Charlotte Brontë', '1816-04-21', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-bronte-emily', '에밀리 브론테', 'Emily Brontë', '1818-07-30', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-virginia-woolf', '버지니아 울프', 'Virginia Woolf', '1882-01-25', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-hugo', '빅토르 위고', 'Victor Hugo', '1802-02-26', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-dumas', '알렉상드르 뒤마', 'Alexandre Dumas', '1802-07-24', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-chekhov', '안톤 체호프', 'Anton Chekhov', '1860-01-29', null, null, '📜', '근대', '극작가', '러시아'],
  ['hist-pushkin', '알렉산드르 푸시킨', 'Alexander Pushkin', '1799-06-06', null, null, '📜', '근대', '시인', '러시아'],
  ['hist-borges', '호르헤 루이스 보르헤스', 'Jorge Luis Borges', '1899-08-24', null, null, '📜', '근대', '소설가', '아르헨티나'],
  ['hist-marquez', '가브리엘 가르시아 마르케스', 'Gabriel García Márquez', '1927-03-06', null, null, '📜', '현대', '소설가', '콜롬비아'],
  ['hist-camus', '알베르 카뮈', 'Albert Camus', '1913-11-07', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-proust', '마르셀 프루스트', 'Marcel Proust', '1871-07-10', null, null, '📜', '근대', '소설가', '프랑스'],

  // ===== EXPLORERS & ADVENTURERS =====
  ['hist-cook', '제임스 쿡', 'James Cook', '1728-11-07', null, null, '📜', '근대', '탐험가', '영국'],
  ['hist-amundsen', '로알 아문센', 'Roald Amundsen', '1872-07-16', null, null, '📜', '근대', '탐험가', '노르웨이'],
  ['hist-scott', '로버트 스콧', 'Robert Falcon Scott', '1868-06-06', null, null, '📜', '근대', '탐험가', '영국'],
  ['hist-shackleton', '어니스트 섀클턴', 'Ernest Shackleton', '1874-02-15', null, null, '📜', '근대', '탐험가', '아일랜드'],
  ['hist-armstrong', '닐 암스트롱', 'Neil Armstrong', '1930-08-05', null, null, '📜', '현대', '우주비행사', '미국'],
  ['hist-yuri-gagarin', '유리 가가린', 'Yuri Gagarin', '1934-03-09', null, null, '📜', '현대', '우주비행사', '소련'],

  // ===== INDIAN HISTORICAL =====
  ['hist-ashoka', '아소카', 'Ashoka', '-0304-01-01', null, null, '📜', '고대', '황제', '인도'],
  ['hist-akbar', '악바르', 'Akbar', '1542-10-15', null, null, '📜', '중세', '황제', '인도'],
  ['hist-tagore', '라빈드라나트 타고르', 'Rabindranath Tagore', '1861-05-07', null, null, '📜', '근대', '시인', '인도'],
  ['hist-nehru', '자와할랄 네루', 'Jawaharlal Nehru', '1889-11-14', null, null, '📜', '근대', '총리', '인도'],

  // ===== PERSIAN / MIDDLE EASTERN =====
  ['hist-rumi', '루미', 'Rumi', '1207-09-30', null, null, '📜', '중세', '시인', '페르시아'],
  ['hist-avicenna', '이븐 시나', 'Avicenna', '0980-08-23', null, null, '📜', '중세', '의학자', '페르시아'],
  ['hist-saladin', '살라딘', 'Saladin', '1137-01-01', null, null, '📜', '중세', '술탄', '쿠르드'],
  ['hist-al-khwarizmi', '알콰리즈미', 'Al-Khwarizmi', '0780-01-01', null, null, '📜', '중세', '수학자', '페르시아'],
  ['hist-omar-khayyam', '오마르 하이얌', 'Omar Khayyam', '1048-05-18', null, null, '📜', '중세', '시인', '페르시아'],
  ['hist-hafez', '하페즈', 'Hafez', '1315-01-01', null, null, '📜', '중세', '시인', '페르시아'],

  // ===== AFRICAN HISTORICAL =====
  ['hist-mansa-musa', '만사 무사', 'Mansa Musa', '1280-01-01', null, null, '📜', '중세', '황제', '말리'],
  ['hist-shaka-zulu', '샤카 줄루', 'Shaka Zulu', '1787-01-01', null, null, '📜', '근대', '왕', '줄루'],
  ['hist-haile-selassie', '하일레 셀라시에', 'Haile Selassie', '1892-07-23', null, null, '📜', '근대', '황제', '에티오피아'],
  ['hist-kwame-nkrumah', '콰메 은크루마', 'Kwame Nkrumah', '1909-09-21', null, null, '📜', '근대', '대통령', '가나'],
  ['hist-patrice-lumumba', '파트리스 루뭄바', 'Patrice Lumumba', '1925-07-02', null, null, '📜', '근대', '총리', '콩고'],

  // ===== SOUTH AMERICAN =====
  ['hist-inca-atahualpa', '아타우알파', 'Atahualpa', '1502-03-20', null, null, '📜', '대항해시대', '잉카왕', '페루'],
  ['hist-aztec-moctezuma', '목테수마 2세', 'Moctezuma II', '1466-01-01', null, null, '📜', '대항해시대', '아즈텍왕', '멕시코'],

  // ===== ADDITIONAL WORLD FIGURES =====
  ['hist-anne-frank', '안네 프랑크', 'Anne Frank', '1929-06-12', null, null, '📜', '근대', '일기작가', '독일계네덜란드'],
  ['hist-helen-keller', '헬렌 켈러', 'Helen Keller', '1880-06-27', null, null, '📜', '근대', '교육자', '미국'],
  ['hist-harriet-tubman', '해리엇 터브먼', 'Harriet Tubman', '1822-03-01', null, null, '📜', '근대', '인권운동가', '미국'],
  ['hist-frederick-douglass', '프레더릭 더글러스', 'Frederick Douglass', '1818-02-01', null, null, '📜', '근대', '인권운동가', '미국'],
  ['hist-elizabeth-i-extra', null, null, '1533-09-07', null, null, '📜', '르네상스', '여왕', '영국'],
  ['hist-cleopatra-vii', null, null, '-0069-01-01', null, null, '📜', '고대', '파라오', '이집트'],

  // ===== KOREAN MODERN POLITICAL =====
  ['hist-rhee-syngman', '이승만', 'Syngman Rhee', '1875-03-26', null, null, '📜', '근대', '대통령', '한국'],
  ['hist-park-chunghee', '박정희', 'Park Chung-hee', '1917-11-14', null, null, '📜', '현대', '대통령', '한국'],
  ['hist-kim-daejung', '김대중', 'Kim Dae-jung', '1924-01-06', null, null, '📜', '현대', '대통령', '한국'],
  ['hist-roh-moohyun', '노무현', 'Roh Moo-hyun', '1946-09-01', null, null, '📜', '현대', '대통령', '한국'],
  ['hist-chun-doohwan', '전두환', 'Chun Doo-hwan', '1931-01-18', null, null, '📜', '현대', '대통령', '한국'],
  ['hist-kim-youngsam', '김영삼', 'Kim Young-sam', '1927-12-20', null, null, '📜', '현대', '대통령', '한국'],
  ['hist-roh-taewoo', '노태우', 'Roh Tae-woo', '1932-12-04', null, null, '📜', '현대', '대통령', '한국'],

  // ===== KOREAN ADDITIONAL CULTURAL FIGURES =====
  ['hist-baekbeom-extra', '김구', null, '1876-08-29', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-jeong-inhong', '정인홍', 'Jeong In-hong', '1536-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-lee-hangbok', '이항복', 'Lee Hang-bok', '1556-01-01', null, null, '📜', '조선', '재상', '한국'],
  ['hist-yu-seongyong', '유성룡', null, '1542-01-01', null, null, '📜', '조선', '재상', '한국'],
  ['hist-park-munsu', '박문수', 'Park Mun-su', '1691-01-01', null, null, '📜', '조선', '암행어사', '한국'],
  ['hist-jang-huibin', '장희빈', 'Jang Hui-bin', '1659-01-01', null, null, '📜', '조선', '후궁', '한국'],
  ['hist-inhyeon-wanghu', '인현왕후', 'Queen Inhyeon', '1667-04-23', null, null, '📜', '조선', '왕비', '한국'],
  ['hist-deokheong-gongju', '덕혜옹주', 'Princess Deokhye', '1912-05-25', null, null, '📜', '대한제국', '공주', '한국'],
  ['hist-min-yeongik', '민영익', 'Min Yeong-ik', '1860-01-01', null, null, '📜', '근대', '정치가', '한국'],
  ['hist-horace-allen', '호러스 알렌', 'Horace Newton Allen', '1858-04-23', null, null, '📜', '근대', '선교사', '미국'],

  // ===== MORE KOREAN HISTORICAL FIGURES =====
  ['hist-choe-ikhhyeon', '최익현', 'Choe Ik-hyeon', '1833-01-14', null, null, '📜', '근대', '의병장', '한국'],
  ['hist-shin-dolseok', '신돌석', 'Shin Dol-seok', '1878-11-03', null, null, '📜', '근대', '의병장', '한국'],
  ['hist-hong-beomdo', '홍범도', 'Hong Beom-do', '1868-08-27', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-ji-cheongcheon', '지청천', 'Ji Cheong-cheon', '1888-01-15', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-kim-jwajin', '김좌진', 'Kim Jwa-jin', '1889-12-16', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yi-beomseok', '이범석', 'Yi Beom-seok', '1900-10-20', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yun-bonggil-extra', null, null, '1908-06-21', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-gwon-giok', '권기옥', 'Gwon Gi-ok', '1901-01-11', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yun-huisun', '윤희순', 'Yun Hui-sun', '1860-06-25', null, null, '📜', '근대', '의병장', '한국'],
  ['hist-yi-sajung', '이사중', null, '1865-01-01', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-choe-hyeon-bae', '최현배', 'Choe Hyeon-bae', '1894-10-19', null, null, '📜', '근대', '국어학자', '한국'],
  ['hist-lee-yuksa', '이육사', 'Yi Yuk-sa', '1904-05-18', null, null, '📜', '근대', '시인', '독립운동가', '한국'],
  ['hist-yoon-dongjoo-extra', null, null, '1917-12-30', null, null, '📜', '근대', '시인', '한국'],
  ['hist-heo-baekryeon', '허백련', 'Heo Baek-ryeon', '1891-01-01', null, null, '📜', '근대', '화가', '한국'],
  ['hist-lee-jungseop', '이중섭', 'Lee Jung-seob', '1916-04-10', null, null, '📜', '근대', '화가', '한국'],
  ['hist-kim-whanki', '김환기', 'Kim Whan-ki', '1913-02-27', null, null, '📜', '근대', '화가', '한국'],
  ['hist-park-sookeun', '박수근', 'Park Soo-keun', '1914-02-21', null, null, '📜', '근대', '화가', '한국'],
  ['hist-baek-namjun', '백남준', 'Nam June Paik', '1932-07-20', null, null, '📜', '현대', '예술가', '한국'],
  ['hist-yun-isang', '윤이상', 'Yun Isang', '1917-09-17', null, null, '📜', '현대', '작곡가', '한국'],
  ['hist-chung-myunghwun', '정명훈', 'Chung Myung-whun', '1953-01-22', null, null, '📜', '현대', '지휘자', '한국'],
  ['hist-ahn-iksoo', '안익태', 'Ahn Eak-tai', '1906-12-05', null, null, '📜', '근대', '작곡가', '한국'],
  ['hist-ahn-byungmu', '안병무', 'Ahn Byung-mu', '1922-06-23', null, null, '📜', '현대', '신학자', '한국'],
  ['hist-ham-seokheon', '함석헌', 'Ham Seok-heon', '1901-03-13', null, null, '📜', '현대', '사상가', '한국'],
  ['hist-jang-junha', '장준하', 'Jang Jun-ha', '1918-08-27', null, null, '📜', '현대', '독립운동가', '한국'],
  ['hist-lee-hoesung', '이회승', 'Lee Hoe-seung', '1905-02-24', null, null, '📜', '근대', '국어학자', '한국'],
  ['hist-choi-namseon', '최남선', 'Choi Nam-seon', '1890-04-26', null, null, '📜', '근대', '역사학자', '한국'],
  ['hist-yi-munyeol', '이문열', 'Yi Mun-yol', '1948-05-18', null, null, '📜', '현대', '소설가', '한국'],
  ['hist-hwang-sunwon', '황순원', 'Hwang Sun-won', '1915-03-26', null, null, '📜', '현대', '소설가', '한국'],
  ['hist-yi-hyoseok', '이효석', 'Yi Hyo-seok', '1907-02-23', null, null, '📜', '근대', '소설가', '한국'],
  ['hist-kim-dongni', '김동니', 'Kim Dong-ni', '1913-12-19', null, null, '📜', '현대', '소설가', '한국'],
  ['hist-chae-mansik', '채만식', 'Chae Man-sik', '1902-06-17', null, null, '📜', '근대', '소설가', '한국'],
  ['hist-yi-gwangsu-extra', null, null, '1892-03-05', null, null, '📜', '근대', '소설가', '한국'],
  ['hist-park-kyungni', '박경리', 'Park Kyung-ni', '1926-10-28', null, null, '📜', '현대', '소설가', '한국'],
  ['hist-shin-kyungsuk', '신경숙', 'Shin Kyung-sook', '1963-01-12', null, null, '📜', '현대', '소설가', '한국'],
  ['hist-jo-sehui', '조세희', 'Jo Se-hui', '1942-08-20', null, null, '📜', '현대', '소설가', '한국'],
  ['hist-kim-soo-young', '김수영', 'Kim Su-yeong', '1921-11-27', null, null, '📜', '현대', '시인', '한국'],
  ['hist-seo-jeongjoo', '서정주', 'Seo Jeong-ju', '1915-05-18', null, null, '📜', '현대', '시인', '한국'],
  ['hist-yi-sanghwa', '이상화', 'Yi Sang-hwa', '1901-04-05', null, null, '📜', '근대', '시인', '한국'],

  // ===== KOREAN JOSEON ADDITIONAL =====
  ['hist-gwon-geun', '권근', 'Gwon Geun', '1352-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-hwadam-seo', '서화담', 'Seo Hwa-dam', '1489-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-gi-daeseon', '기대승', 'Gi Dae-seung', '1527-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-song-sammun', '성삼문', null, '1418-01-01', null, null, '📜', '조선', '충신', '한국'],
  ['hist-yu-hyeongwon', '유형원', 'Yu Hyeong-won', '1622-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-yi-sugwang', '이수광', 'Yi Su-gwang', '1563-01-01', null, null, '📜', '조선', '학자', '한국'],
  ['hist-jeong-songtag', '정송강', 'Jeong Cheol', '1536-01-01', null, null, '📜', '조선', '시인', '한국'],
  ['hist-bak-inno', '박인로', 'Bak In-ro', '1561-01-01', null, null, '📜', '조선', '시인', '한국'],
  ['hist-kim-mandeok', '김만덕', 'Kim Man-deok', '1739-01-01', null, null, '📜', '조선', '의녀', '상인', '한국'],
  ['hist-chusa-extra', null, null, '1786-06-03', null, null, '📜', '조선', '서예가', '한국'],

  // ===== MORE WORLD HISTORICAL - MODERN SCIENTISTS =====
  ['hist-von-neumann', '존 폰 노이만', 'John von Neumann', '1903-12-28', null, null, '📜', '근대', '수학자', '헝가리계미국'],
  ['hist-dirac', '폴 디랙', 'Paul Dirac', '1902-08-08', null, null, '📜', '근대', '물리학자', '영국'],
  ['hist-rutherford', '어니스트 러더퍼드', 'Ernest Rutherford', '1871-08-30', null, null, '📜', '근대', '물리학자', '뉴질랜드'],
  ['hist-maxwell-extra', '맥스웰', null, '1831-06-13', null, null, '📜', '근대', '물리학자', '영국'],
  ['hist-hubble', '에드윈 허블', 'Edwin Hubble', '1889-11-20', null, null, '📜', '근대', '천문학자', '미국'],
  ['hist-carl-sagan', '칼 세이건', 'Carl Sagan', '1934-11-09', null, null, '📜', '현대', '천문학자', '미국'],
  ['hist-lise-meitner', '리제 마이트너', 'Lise Meitner', '1878-11-07', null, null, '📜', '근대', '물리학자', '오스트리아'],
  ['hist-emmy-noether', '에미 뇌터', 'Emmy Noether', '1882-03-23', null, null, '📜', '근대', '수학자', '독일'],
  ['hist-rosalind-franklin', '로절린드 프랭클린', 'Rosalind Franklin', '1920-07-25', null, null, '📜', '근대', '화학자', '영국'],
  ['hist-watson-crick', '제임스 왓슨', 'James Watson', '1928-04-06', null, null, '📜', '근대', '생물학자', '미국'],
  ['hist-crick', '프랜시스 크릭', 'Francis Crick', '1916-06-08', null, null, '📜', '근대', '생물학자', '영국'],
  ['hist-alexander-fleming', '알렉산더 플레밍', 'Alexander Fleming', '1881-08-06', null, null, '📜', '근대', '미생물학자', '영국'],
  ['hist-koch', '로베르트 코흐', 'Robert Koch', '1843-12-11', null, null, '📜', '근대', '미생물학자', '독일'],
  ['hist-jenner', '에드워드 제너', 'Edward Jenner', '1749-05-17', null, null, '📜', '근대', '의학자', '영국'],
  ['hist-pavlov', '이반 파블로프', 'Ivan Pavlov', '1849-09-26', null, null, '📜', '근대', '생리학자', '러시아'],
  ['hist-alfred-nobel', '알프레드 노벨', 'Alfred Nobel', '1833-10-21', null, null, '📜', '근대', '발명가', '스웨덴'],
  ['hist-nikola-tesla-extra', null, null, '1856-07-10', null, null, '📜', '근대', '발명가', '세르비아계미국'],
  ['hist-gutenberg-press', null, null, '1400-01-01', null, null, '📜', '르네상스', '발명가', '독일'],
  ['hist-james-watt', '제임스 와트', 'James Watt', '1736-01-19', null, null, '📜', '근대', '발명가', '영국'],
  ['hist-alfred-wegener', '알프레트 베게너', 'Alfred Wegener', '1880-11-01', null, null, '📜', '근대', '지질학자', '독일'],
  ['hist-rachel-carson', '레이첼 카슨', 'Rachel Carson', '1907-05-27', null, null, '📜', '근대', '생물학자', '미국'],
  ['hist-jane-goodall-hist', '제인 구달', 'Jane Goodall', '1934-04-03', null, null, '📜', '현대', '동물학자', '영국'],

  // ===== MORE WORLD POLITICAL LEADERS =====
  ['hist-teddy-roosevelt', '시어도어 루즈벨트', 'Theodore Roosevelt', '1858-10-27', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-woodrow-wilson', '우드로 윌슨', 'Woodrow Wilson', '1856-12-28', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-dwight-eisenhower', '드와이트 아이젠하워', 'Dwight D. Eisenhower', '1890-10-14', null, null, '📜', '근대', '대통령', '미국'],
  ['hist-reagan', '로널드 레이건', 'Ronald Reagan', '1911-02-06', null, null, '📜', '현대', '대통령', '미국'],
  ['hist-margaret-thatcher', '마거릿 대처', 'Margaret Thatcher', '1925-10-13', null, null, '📜', '현대', '총리', '영국'],
  ['hist-charles-de-gaulle', '샤를 드 골', 'Charles de Gaulle', '1890-11-22', null, null, '📜', '근대', '대통령', '프랑스'],
  ['hist-willy-brandt', '빌리 브란트', 'Willy Brandt', '1913-12-18', null, null, '📜', '현대', '총리', '독일'],
  ['hist-kemal-ataturk', '무스타파 케말 아타튀르크', 'Mustafa Kemal Atatürk', '1881-05-19', null, null, '📜', '근대', '대통령', '터키'],
  ['hist-ho-chi-minh', '호치민', 'Ho Chi Minh', '1890-05-19', null, null, '📜', '근대', '대통령', '베트남'],
  ['hist-deng-xiaoping', '덩샤오핑', 'Deng Xiaoping', '1904-08-22', null, null, '📜', '현대', '지도자', '중국'],
  ['hist-zhou-enlai', '저우언라이', 'Zhou Enlai', '1898-03-05', null, null, '📜', '근대', '총리', '중국'],
  ['hist-aung-san', '아웅산', 'Aung San', '1915-02-13', null, null, '📜', '근대', '독립운동가', '미얀마'],
  ['hist-sukarno', '수카르노', 'Sukarno', '1901-06-06', null, null, '📜', '근대', '대통령', '인도네시아'],
  ['hist-meir', '골다 메이어', 'Golda Meir', '1898-05-03', null, null, '📜', '근대', '총리', '이스라엘'],
  ['hist-arafat', '야세르 아라파트', 'Yasser Arafat', '1929-08-24', null, null, '📜', '현대', '정치가', '팔레스타인'],
  ['hist-indira-gandhi', '인디라 간디', 'Indira Gandhi', '1917-11-19', null, null, '📜', '현대', '총리', '인도'],

  // ===== MORE WORLD ARTISTS & ARCHITECTS =====
  ['hist-klimt', '구스타프 클림트', 'Gustav Klimt', '1862-07-14', null, null, '📜', '근대', '화가', '오스트리아'],
  ['hist-munch', '에드바르 뭉크', 'Edvard Munch', '1863-12-12', null, null, '📜', '근대', '화가', '노르웨이'],
  ['hist-matisse', '앙리 마티스', 'Henri Matisse', '1869-12-31', null, null, '📜', '근대', '화가', '프랑스'],
  ['hist-cezanne', '폴 세잔', 'Paul Cézanne', '1839-01-19', null, null, '📜', '근대', '화가', '프랑스'],
  ['hist-degas', '에드가 드가', 'Edgar Degas', '1834-07-19', null, null, '📜', '근대', '화가', '프랑스'],
  ['hist-kandinsky', '바실리 칸딘스키', 'Wassily Kandinsky', '1866-12-16', null, null, '📜', '근대', '화가', '러시아'],
  ['hist-mondrian', '피에트 몬드리안', 'Piet Mondrian', '1872-03-07', null, null, '📜', '근대', '화가', '네덜란드'],
  ['hist-magritte', '르네 마그리트', 'René Magritte', '1898-11-21', null, null, '📜', '근대', '화가', '벨기에'],
  ['hist-banksy-hist', '뱅크시', 'Banksy', '1974-01-01', null, null, '📜', '현대', '예술가', '영국'],
  ['hist-basquiat', '장미셸 바스키아', 'Jean-Michel Basquiat', '1960-12-22', null, null, '📜', '현대', '화가', '미국'],
  ['hist-ai-weiwei', '아이웨이웨이', 'Ai Weiwei', '1957-08-28', null, null, '📜', '현대', '예술가', '중국'],
  ['hist-georgia-okeeffe', '조지아 오키프', 'Georgia O\'Keeffe', '1887-11-15', null, null, '📜', '근대', '화가', '미국'],
  ['hist-jackson-pollock', '잭슨 폴록', 'Jackson Pollock', '1912-01-28', null, null, '📜', '근대', '화가', '미국'],
  ['hist-duchamp', '마르셀 뒤샹', 'Marcel Duchamp', '1887-07-28', null, null, '📜', '근대', '예술가', '프랑스'],
  ['hist-gaudi', '안토니 가우디', 'Antoni Gaudí', '1852-06-25', null, null, '📜', '근대', '건축가', '스페인'],
  ['hist-le-corbusier', '르 코르뷔지에', 'Le Corbusier', '1887-10-06', null, null, '📜', '근대', '건축가', '스위스'],
  ['hist-frank-lloyd-wright', '프랭크 로이드 라이트', 'Frank Lloyd Wright', '1867-06-08', null, null, '📜', '근대', '건축가', '미국'],
  ['hist-zaha-hadid', '자하 하디드', 'Zaha Hadid', '1950-10-31', null, null, '📜', '현대', '건축가', '이라크계영국'],
  ['hist-tadao-ando', '안도 다다오', 'Tadao Ando', '1941-09-13', null, null, '📜', '현대', '건축가', '일본'],

  // ===== MORE WRITERS =====
  ['hist-joyce', '제임스 조이스', 'James Joyce', '1882-02-02', null, null, '📜', '근대', '소설가', '아일랜드'],
  ['hist-faulkner', '윌리엄 포크너', 'William Faulkner', '1897-09-25', null, null, '📜', '근대', '소설가', '미국'],
  ['hist-fitzgerald', 'F. 스콧 피츠제럴드', 'F. Scott Fitzgerald', '1896-09-24', null, null, '📜', '근대', '소설가', '미국'],
  ['hist-steinbeck', '존 스타인벡', 'John Steinbeck', '1902-02-27', null, null, '📜', '근대', '소설가', '미국'],
  ['hist-vonnegut', '커트 보네거트', 'Kurt Vonnegut', '1922-11-11', null, null, '📜', '현대', '소설가', '미국'],
  ['hist-nabokov', '블라디미르 나보코프', 'Vladimir Nabokov', '1899-04-22', null, null, '📜', '근대', '소설가', '러시아계미국'],
  ['hist-beckett', '사뮈엘 베케트', 'Samuel Beckett', '1906-04-13', null, null, '📜', '근대', '극작가', '아일랜드'],
  ['hist-ibsen', '헨리크 입센', 'Henrik Ibsen', '1828-03-20', null, null, '📜', '근대', '극작가', '노르웨이'],
  ['hist-balzac', '오노레 드 발자크', 'Honoré de Balzac', '1799-05-20', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-flaubert', '귀스타브 플로베르', 'Gustave Flaubert', '1821-12-12', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-baudelaire', '샤를 보들레르', 'Charles Baudelaire', '1821-04-09', null, null, '📜', '근대', '시인', '프랑스'],
  ['hist-neruda', '파블로 네루다', 'Pablo Neruda', '1904-07-12', null, null, '📜', '근대', '시인', '칠레'],
  ['hist-rabindranath', '라빈드라나트 타고르', null, '1861-05-07', null, null, '📜', '근대', '시인', '인도'],
  ['hist-rainer-maria-rilke', '라이너 마리아 릴케', 'Rainer Maria Rilke', '1875-12-04', null, null, '📜', '근대', '시인', '오스트리아'],
  ['hist-emily-dickinson', '에밀리 디킨슨', 'Emily Dickinson', '1830-12-10', null, null, '📜', '근대', '시인', '미국'],
  ['hist-walt-whitman', '월트 휘트먼', 'Walt Whitman', '1819-05-31', null, null, '📜', '근대', '시인', '미국'],
  ['hist-edgar-allan-poe', '에드거 앨런 포', 'Edgar Allan Poe', '1809-01-19', null, null, '📜', '근대', '소설가', '미국'],
  ['hist-hans-andersen', '한스 안데르센', 'Hans Christian Andersen', '1805-04-02', null, null, '📜', '근대', '동화작가', '덴마크'],
  ['hist-brothers-grimm-jacob', '야콥 그림', 'Jacob Grimm', '1785-01-04', null, null, '📜', '근대', '동화작가', '독일'],
  ['hist-brothers-grimm-wilhelm', '빌헬름 그림', 'Wilhelm Grimm', '1786-02-24', null, null, '📜', '근대', '동화작가', '독일'],
  ['hist-jules-verne', '쥘 베른', 'Jules Verne', '1828-02-08', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-hg-wells', 'H.G. 웰스', 'H.G. Wells', '1866-09-21', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-agatha-christie', '아가사 크리스티', 'Agatha Christie', '1890-09-15', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-conan-doyle', '아서 코난 도일', 'Arthur Conan Doyle', '1859-05-22', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-tolkien', 'J.R.R. 톨킨', 'J.R.R. Tolkien', '1892-01-03', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-cs-lewis', 'C.S. 루이스', 'C.S. Lewis', '1898-11-29', null, null, '📜', '근대', '소설가', '영국'],
  ['hist-antoine-de-saint-exupery', '생텍쥐페리', 'Antoine de Saint-Exupéry', '1900-06-29', null, null, '📜', '근대', '소설가', '프랑스'],
  ['hist-simone-weil', '시몬 베유', 'Simone Weil', '1909-02-03', null, null, '📜', '근대', '철학자', '프랑스'],

  // ===== MORE CHINESE HISTORICAL =====
  ['hist-yue-fei', '악비', 'Yue Fei', '1103-03-24', null, null, '📜', '송나라', '장군', '중국'],
  ['hist-ban-gu', '반고', 'Ban Gu', '0032-01-01', null, null, '📜', '한나라', '역사가', '중국'],
  ['hist-cai-lun', '채륜', 'Cai Lun', '0063-01-01', null, null, '📜', '한나라', '발명가', '중국'],
  ['hist-su-shi', '소식', 'Su Shi', '1037-01-08', null, null, '📜', '송나라', '시인', '중국'],
  ['hist-wang-xizhi', '왕희지', 'Wang Xizhi', '0303-01-01', null, null, '📜', '진나라', '서예가', '중국'],
  ['hist-lu-xun', '루쉰', 'Lu Xun', '1881-09-25', null, null, '📜', '근대', '소설가', '중국'],
  ['hist-lao-she', '라오서', 'Lao She', '1899-02-03', null, null, '📜', '근대', '소설가', '중국'],
  ['hist-zhang-heng', '장형', 'Zhang Heng', '0078-01-01', null, null, '📜', '한나라', '과학자', '중국'],
  ['hist-hua-tuo', '화타', 'Hua Tuo', '0145-01-01', null, null, '📜', '삼국시대', '의학자', '중국'],
  ['hist-confucius-extra', null, null, '-0551-09-28', null, null, '📜', '고대', '철학자', '중국'],

  // ===== MORE JAPANESE HISTORICAL =====
  ['hist-murasaki-shikibu', '무라사키 시키부', 'Murasaki Shikibu', '0973-01-01', null, null, '📜', '헤이안시대', '소설가', '일본'],
  ['hist-sei-shonagon', '세이 쇼나곤', 'Sei Shōnagon', '0966-01-01', null, null, '📜', '헤이안시대', '수필가', '일본'],
  ['hist-matsuo-basho', '마츠오 바쇼', 'Matsuo Bashō', '1644-06-15', null, null, '📜', '에도시대', '시인', '일본'],
  ['hist-hokusai', '가츠시카 호쿠사이', 'Katsushika Hokusai', '1760-10-31', null, null, '📜', '에도시대', '화가', '일본'],
  ['hist-hiroshige', '우타가와 히로시게', 'Utagawa Hiroshige', '1797-01-01', null, null, '📜', '에도시대', '화가', '일본'],
  ['hist-natsume-soseki', '나쓰메 소세키', 'Natsume Sōseki', '1867-02-09', null, null, '📜', '근대', '소설가', '일본'],
  ['hist-kawabata', '가와바타 야스나리', 'Yasunari Kawabata', '1899-06-11', null, null, '📜', '근대', '소설가', '일본'],
  ['hist-mishima', '미시마 유키오', 'Yukio Mishima', '1925-01-14', null, null, '📜', '현대', '소설가', '일본'],
  ['hist-osamu-dazai', '다자이 오사무', 'Osamu Dazai', '1909-06-19', null, null, '📜', '근대', '소설가', '일본'],
  ['hist-hideyo-noguchi', '노구치 히데요', 'Hideyo Noguchi', '1876-11-09', null, null, '📜', '근대', '의학자', '일본'],
  ['hist-fukuzawa-yukichi', '후쿠자와 유키치', 'Fukuzawa Yukichi', '1835-01-10', null, null, '📜', '근대', '교육자', '일본'],
  ['hist-toshinobu-kubota', '구보타 도시노부', null, '1845-01-01', null, null, '📜', '근대', '정치가', '일본'],

  // ===== ANCIENT EGYPTIAN / MESOPOTAMIAN =====
  ['hist-ramesses-ii', '람세스 2세', 'Ramesses II', '-1303-01-01', null, null, '📜', '고대', '파라오', '이집트'],
  ['hist-tutankhamun', '투탕카멘', 'Tutankhamun', '-1341-01-01', null, null, '📜', '고대', '파라오', '이집트'],
  ['hist-nefertiti', '네페르티티', 'Nefertiti', '-1370-01-01', null, null, '📜', '고대', '왕비', '이집트'],
  ['hist-hatshepsut', '하트셉수트', 'Hatshepsut', '-1507-01-01', null, null, '📜', '고대', '파라오', '이집트'],
  ['hist-hammurabi', '함무라비', 'Hammurabi', '-1810-01-01', null, null, '📜', '고대', '왕', '바빌로니아'],
  ['hist-nebuchadnezzar', '네부카드네자르', 'Nebuchadnezzar II', '-0634-01-01', null, null, '📜', '고대', '왕', '바빌로니아'],
  ['hist-cyrus-great', '키루스 대왕', 'Cyrus the Great', '-0600-01-01', null, null, '📜', '고대', '왕', '페르시아'],
  ['hist-darius-i', '다리우스 1세', 'Darius I', '-0550-01-01', null, null, '📜', '고대', '왕', '페르시아'],

  // ===== ADDITIONAL MODERN FIGURES =====
  ['hist-sigmund-freud-extra', null, null, '1856-05-06', null, null, '📜', '근대', '심리학자', '오스트리아'],
  ['hist-carl-jung-extra', null, null, '1875-07-26', null, null, '📜', '근대', '심리학자', '스위스'],
  ['hist-weber', '막스 베버', 'Max Weber', '1864-04-21', null, null, '📜', '근대', '사회학자', '독일'],
  ['hist-durkheim', '에밀 뒤르켐', 'Émile Durkheim', '1858-04-15', null, null, '📜', '근대', '사회학자', '프랑스'],
  ['hist-foucault', '미셸 푸코', 'Michel Foucault', '1926-10-15', null, null, '📜', '현대', '철학자', '프랑스'],
  ['hist-derrida', '자크 데리다', 'Jacques Derrida', '1930-07-15', null, null, '📜', '현대', '철학자', '프랑스'],
  ['hist-chomsky', '노엄 촘스키', 'Noam Chomsky', '1928-12-07', null, null, '📜', '현대', '언어학자', '미국'],
  ['hist-edward-said', '에드워드 사이드', 'Edward Said', '1935-11-01', null, null, '📜', '현대', '학자', '팔레스타인계미국'],
  ['hist-amartya-sen', '아마르티아 센', 'Amartya Sen', '1933-11-03', null, null, '📜', '현대', '경제학자', '인도'],
  ['hist-john-maynard-keynes', '존 메이너드 케인스', 'John Maynard Keynes', '1883-06-05', null, null, '📜', '근대', '경제학자', '영국'],
  ['hist-hayek', '프리드리히 하이에크', 'Friedrich Hayek', '1899-05-08', null, null, '📜', '근대', '경제학자', '오스트리아'],
  ['hist-milton-friedman', '밀턴 프리드먼', 'Milton Friedman', '1912-07-31', null, null, '📜', '현대', '경제학자', '미국'],

  // ===== SOUTHEAST ASIAN / OCEANIAN HISTORICAL =====
  ['hist-rizal', '호세 리살', 'José Rizal', '1861-06-19', null, null, '📜', '근대', '독립운동가', '필리핀'],
  ['hist-pol-pot', '폴 포트', 'Pol Pot', '1925-05-19', null, null, '📜', '현대', '독재자', '캄보디아'],
  ['hist-king-rama-v', '쫄랄롱꼰', 'Chulalongkorn', '1853-09-20', null, null, '📜', '근대', '왕', '태국'],

  // ===== MORE MEDIEVAL / RENAISSANCE =====
  ['hist-saladin-extra', null, null, '1137-01-01', null, null, '📜', '중세', '술탄', '쿠르드'],
  ['hist-dante-extra', null, null, '1265-06-01', null, null, '📜', '중세', '시인', '이탈리아'],
  ['hist-giordano-bruno', '조르다노 브루노', 'Giordano Bruno', '1548-01-01', null, null, '📜', '르네상스', '철학자', '이탈리아'],
  ['hist-erasmus', '에라스뮈스', 'Erasmus', '1466-10-28', null, null, '📜', '르네상스', '인문주의자', '네덜란드'],
  ['hist-francis-bacon', '프랜시스 베이컨', 'Francis Bacon', '1561-01-22', null, null, '📜', '르네상스', '철학자', '영국'],
  ['hist-montaigne', '미셸 드 몽테뉴', 'Michel de Montaigne', '1533-02-28', null, null, '📜', '르네상스', '수필가', '프랑스'],
  ['hist-spinoza', '바루흐 스피노자', 'Baruch Spinoza', '1632-11-24', null, null, '📜', '근대', '철학자', '네덜란드'],
  ['hist-hume', '데이비드 흄', 'David Hume', '1711-05-07', null, null, '📜', '근대', '철학자', '영국'],
  ['hist-john-stuart-mill', '존 스튜어트 밀', 'John Stuart Mill', '1806-05-20', null, null, '📜', '근대', '철학자', '영국'],

  // ===== ADDITIONAL KOREAN INDEPENDENCE FIGHTERS =====
  ['hist-min-youngwan', '민영환', 'Min Yeong-hwan', '1861-08-07', null, null, '📜', '근대', '충신', '한국'],
  ['hist-cho-byeongseon', '조병세', null, '1827-01-01', null, null, '📜', '근대', '충신', '한국'],
  ['hist-song-jinwoo', '송진우', 'Song Jin-woo', '1890-05-08', null, null, '📜', '근대', '언론인', '한국'],
  ['hist-kim-gyu-sik', '김규식', 'Kim Kyu-sik', '1881-01-29', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yeo-unhyeong-extra', null, null, '1886-05-25', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-shin-ik-hui', '신익희', 'Shin Ik-hui', '1894-07-11', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-kim-wonbong', '김원봉', 'Kim Won-bong', '1898-09-28', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yi-siyeong', '이시영', 'Yi Si-yeong', '1869-12-03', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-cho-soan', '조소앙', 'Jo So-ang', '1887-04-30', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-nam-gungok', '남궁억', 'Nam Gung-eok', '1863-12-27', null, null, '📜', '근대', '교육자', '한국'],
  ['hist-yi-dongnyu', '이동녕', 'Yi Dong-nyeong', '1869-10-06', null, null, '📜', '근대', '독립운동가', '한국'],
  ['hist-yun-chiho-extra', null, null, '1865-01-23', null, null, '📜', '근대', '정치가', '한국'],

  // ===== ROMAN EMPIRE =====
  ['hist-constantine', '콘스탄티누스 대제', 'Constantine the Great', '0272-02-27', null, null, '📜', '고대', '황제', '로마'],
  ['hist-trajan', '트라야누스', 'Trajan', '0053-09-18', null, null, '📜', '고대', '황제', '로마'],
  ['hist-hadrian', '하드리아누스', 'Hadrian', '0076-01-24', null, null, '📜', '고대', '황제', '로마'],
  ['hist-cicero', '키케로', 'Cicero', '-0106-01-03', null, null, '📜', '고대', '정치가', '로마'],
  ['hist-virgil', '베르길리우스', 'Virgil', '-0070-10-15', null, null, '📜', '고대', '시인', '로마'],
  ['hist-ovid', '오비디우스', 'Ovid', '-0043-03-20', null, null, '📜', '고대', '시인', '로마'],

  // ===== MORE WORLD MODERN =====
  ['hist-marie-antoinette', '마리 앙투아네트', 'Marie Antoinette', '1755-11-02', null, null, '📜', '근대', '왕비', '프랑스'],
  ['hist-robespierre', '로베스피에르', 'Maximilien Robespierre', '1758-05-06', null, null, '📜', '근대', '혁명가', '프랑스'],
  ['hist-florence-nightingale-extra', null, null, '1820-05-12', null, null, '📜', '근대', '간호사', '영국'],
  ['hist-clara-barton', '클래라 바턴', 'Clara Barton', '1821-12-25', null, null, '📜', '근대', '간호사', '미국'],
  ['hist-sojourner-truth', '소저너 트루스', 'Sojourner Truth', '1797-01-01', null, null, '📜', '근대', '인권운동가', '미국'],
  ['hist-mary-wollstonecraft', '메리 울스턴크래프트', 'Mary Wollstonecraft', '1759-04-27', null, null, '📜', '근대', '여성운동가', '영국'],
  ['hist-emmeline-pankhurst', '에멀린 팽크허스트', 'Emmeline Pankhurst', '1858-07-15', null, null, '📜', '근대', '여성운동가', '영국'],
  ['hist-simone-de-beauvoir-extra', null, null, '1908-01-09', null, null, '📜', '근대', '철학자', '여성운동가', '프랑스'],
  ['hist-betty-friedan', '베티 프리단', 'Betty Friedan', '1921-02-04', null, null, '📜', '현대', '여성운동가', '미국'],
  ['hist-frida-kahlo-extra', null, null, '1907-07-06', null, null, '📜', '근대', '화가', '멕시코'],
  ['hist-pablo-neruda-extra', null, null, '1904-07-12', null, null, '📜', '근대', '시인', '칠레'],
  ['hist-garcia-lorca', '페데리코 가르시아 로르카', 'Federico García Lorca', '1898-06-05', null, null, '📜', '근대', '시인', '스페인'],
  ['hist-octavio-paz', '옥타비오 파스', 'Octavio Paz', '1914-03-31', null, null, '📜', '현대', '시인', '멕시코'],
  ['hist-chinua-achebe', '치누아 아체베', 'Chinua Achebe', '1930-11-16', null, null, '📜', '현대', '소설가', '나이지리아'],
  ['hist-wole-soyinka', '올레 소잉카', 'Wole Soyinka', '1934-07-13', null, null, '📜', '현대', '극작가', '나이지리아'],

  // ===== VIKING / NORDIC =====
  ['hist-leif-erikson', '레이프 에릭손', 'Leif Erikson', '0970-01-01', null, null, '📜', '중세', '탐험가', '노르웨이'],
  ['hist-ragnar-lothbrok', '라그나르 로스브로크', 'Ragnar Lothbrok', '0795-01-01', null, null, '📜', '중세', '바이킹왕', '스칸디나비아'],

  // ===== LAST BATCH - MODERN WORLD =====
  ['hist-mikhail-gorbachev', '미하일 고르바초프', 'Mikhail Gorbachev', '1931-03-02', null, null, '📜', '현대', '대통령', '소련'],
  ['hist-vaclav-havel', '바츨라프 하벨', 'Václav Havel', '1936-10-05', null, null, '📜', '현대', '대통령', '체코'],
  ['hist-lech-walesa', '레흐 바웬사', 'Lech Wałęsa', '1943-09-29', null, null, '📜', '현대', '대통령', '폴란드'],
  ['hist-kofi-annan', '코피 아난', 'Kofi Annan', '1938-04-08', null, null, '📜', '현대', '사무총장', '가나'],
  ['hist-desmond-tutu', '데즈먼드 투투', 'Desmond Tutu', '1931-10-07', null, null, '📜', '현대', '성직자', '남아프리카'],
  ['hist-wangari-maathai', '왕가리 마타이', 'Wangari Maathai', '1940-04-01', null, null, '📜', '현대', '환경운동가', '케냐'],
  ['hist-aung-san-suu-kyi', '아웅산 수치', 'Aung San Suu Kyi', '1945-06-19', null, null, '📜', '현대', '정치인', '미얀마'],
]
